def new_magic(date_data:str):
  split_data = date_data.split("\n")
  split_data = [data for data in split_data if data != ""]

  headlines = []
  articles = []
  dividers = []
  for index in range(len(split_data)):
    if (index+1) % 3 == 0:
      split_data[index] = "divider"

  split_data = [data for data in split_data if data != "divider"]

  headlines = []
  articles = []
  for index, headline in enumerate(split_data):
    if index % 2 == 0:
      headlines.append(split_data[index])
    else:
      articles.append(split_data[index])

  return articles, headlines


news_string = """
Australian Shares Rise in Post-Holiday TradeAustralia Stock Market
The S&P/ASX 200 Index rose 0.2% to around 7,120 in post-holiday trade on Wednesday, as hopes for an end-of-year rally countered downward pressure from surging bond yields worldwide and fears of a global recession next year. Local shares also got a boost after China said that it will end quarantine requirements for inbound travelers starting on Jan. 8, sparking hopes for a faster economic recovery in Australia’s top trading partner. Heavyweight iron ore miners and energy firms led the charge, with notable gains from BHP Group (1%), Fortescue Metals (1.2%), Rio Tinto (1.5%), Woodside Energy (1%) and Santos (1.4%). Gold stocks also advanced, with sector leaders Newcrest Mining and Northern Star Resources rising 0.6% and 2.4%, respectively. Meanwhile, technology, healthcare and financial stocks mostly declined.
28 minutes ago
New Zealand Equities MutedNew Zealand Stock Market
The stock market in New Zealand fell 11.85 points or 0.10% to 11,483.11 around midday on Wednesday, as traders returned from a holiday, extending losses from the prior session, amid the negative lead from Wall Street. US Stocks closed lower Tuesday, amid rising US treasury. The S&P and Nasdaq fell by 0.4% and 1.4%, respectively while the Dow Jones gained 0.1%. Locally,the business confidence plunged to a record low and weighed down market sentiment. Meanwhile, Asian markets Tuesday strengthened, after China announced Monday that starting early January to drop quarantine requirements for inbound visitors. Among losers were Rua Bioscience (-4.35%), followed by Synlait (-2.86%), Private Land and Property Fund (-2.48%), Smartbay Holdings Ltd (-1.89%), and Cannasouth (-1.69%).The NZX 50 on last Friday finished lower weighed down by a pullback on Wall Street Thursday after strong US economic data stoked fears of further rapid tightening by the Federal Reserve.
58 minutes ago
Brazilian Stocks Close Slightly LowerBrazil Stock Market
Brazil’s Ibovespa stock index closed slightly below the flatline at 108,580 on Tuesday, partially recovering from being down more than 1% in the session on another day of low-volume trading as investors awaited minister picks by President-elect Lula for the country's new government. Brazilian equities rebounded from intra-day losses on reports that the country’s Ministry of Planning and Budget Management will be led by moderate-leaning senator Simone Tebet, easing current concerns about fiscal risks. Worries that the country’s upcoming government will sharply increase public spending continued to support expectations of higher inflation and interest rates, driving the central bank to revise inflation expectations higher until 2025. Consequently, retail giants extended yesterday’s losses with Via Varejo and Magazine Luiza sliding 6.3% and 5.3%, respectively. On the other hand, news that the Chinese economy is reopening further supported mining giant Vale to add 5%.
2 hours ago
South Korea Business Morale Drops to 27-Month LowSouth Korea Business Confidence
The Business Survey Index (BSI) for the manufacturing sector in South Korea fell to 71 in December of 2022, the lowest since September 2020, from 74 in the previous month. Sentiment deteriorated further for sales (85 vs 90 in November), as manfucturers reported worse business conditions both for domestic demand-oriented (69 vs 74) and export-oriented (74 vs 75) businesses. Still, manufacturers noted a sharp decrease in raw material purchase prices (116 vs 125), driving sales prices to lower as well (96 vs 99). Looking forward, business conditions are expected to drop further in the next month.
3 hours ago
Crude Oil Erases Session GainsCommodity
WTI crude futures pared early gains to hover at $79.5 per barrel on Tuesday after forecasts of moderate weather and news that some US refineries are expected to resume operations quickly eased fears of low supply after Artic blasts in the region halted output. The retreat in prices was limited as the prospect of a production cut by Russia in response to Western sanctions kept supply concerns prevalent. The major exporter may reduce output by 5% to 7% in early 2023, the RIA news agency reported citing Deputy Prime Minister Alexander Novak. In the meantime, prices were also supported by China reversing Covid restrictions further by ending quarantine requirements for inbound travelers starting on Jan. 8, lifting the demand outlook in the world’s top crude importer.
3 hours ago
Tech Losses Pressure Wall Street on TuesdayUnited States Stock Market
The S&P 500 closed 0.4% lower and the Nasdaq underperformed to slump 1.4% on Tuesday amid pressure from tech and high-growth stocks, as concerns of tighter monetary policy continued to hamper demand for rate-sensitive equities. News that Chinese authorities will extend its reopening efforts by lifting travel restrictions increased concerns about higher commodity prices, sharply lifting Treasury yields and backing the Federal Reserve’s pledge that interest rates need to stay higher for longer. Shares of Amazon and Alphabet declined 2% each, while Apple tumbled 1.2% to drop to its lowest level since June 2021. At the same time, Tesla extended heavy losses and sank 10.6% after demand worries in China drove the electric vehicle manufacturer to lower production plans. Still, gains in retail giants and telecoms supported the Dow to close 25 points above the flatline. All three benchmarks are heading for their worst annual performances since 2008.
4 hours ago
Argentinian Retail Sales Growth Slows to 7-Month LowArgentina Retail Sales YoY
Retail sales in Argentina rose by 120 percent year-on-year at current prices in October of 2022, the least since March of 2022 and easing from 124.6 percent in the prior month, largely due to soaring inflation in the Argentinean economy. Retail activity rose at the fastest pace for leisure and recreation (168.3 percent), food halls and restaurants (148.7 percent), and electronics and computers (135.9 percent). At constant prices, retail sales in Argentina rose by 8.2 percent year-on-year, easing from the 13.2 percent yearly increase in the prior month.
5 hours ago
Italian Shares Underperform on TuesdayItaly Stock Market
Italy’s FTSE MIB index pared earlier gains and closed marginally below the flatline at 23,855 on Tuesday, underperforming other major European equity benchmarks after investors returned from a long weekend as investors awaited the Senate’s vote on the Italian government’s Budget Law for 2023. The budget is worth over EUR 30 billion, within EU framework rules but well above previous plans as the government will ramp up financial support for households to combat higher energy bills. Tech and utility shares closed in the red with STMicroelectronics and ERG dropping 1% and 2%, respectively. On the other hand, Moncler shares jumped over 3% after top consumer China announced plans to reopen its economy from Covid restrictions.
7 hours ago
US Stocks WaverUnited States Stock Market
The blue-chip Dow recovered from a weak start to add 100 points on Tuesday, as investors welcomed the news that China will end quarantine for inbound visitors, thus paving the way for a swifter reopening of the world's second-largest economy. The S&P 500 and the tech-heavy Nasdaq underperformed by losing roughly 0.3% and 1.1%, respectively, as rising Treasury yields dented the appetite for tech and other high-growth stocks. While this last week of the year has been historically bullish for equities, concerns about the negative impact of rate hikes, including poor economic growth, job losses, and downward earnings revisions, kept investors on edge. Meanwhile, Tesla fell nearly 8% after planning to expand its light production schedule at its Shanghai plant in January. For December, the Dow is currently down around 3.7%, the S&P 500 lost 6%, and the Nasdaq 100 dropped 10%, with all three benchmarks heading for their worst annual performances since 2008.
7 hours ago
CAC 40 Outperforms European PeersFrance Stock Market
Equities in Paris enjoyed some respite on Tuesday, with the benchmark CAC 40 outperforming its European peers by adding roughly 0.7%, driven by gains in consumer discretionary and energy stocks, as investors welcomed the news that China will ease further its coronavirus restrictions. China-exposed luxury firms LVMH and Hermes were among the top performers, up over 2% each.
7 hours ago
European Stocks Close on High NoteGermany Stock Market
European equities gained ground on Tuesday, with the pan-European STOXX 600 closing around 430 points, driven by gains in the consumer discretionary sector, on optimism about China's reopening. The world's second-largest economy announced that it would stop requiring inbound travelers to go into quarantine starting from January 8th ahead of the Chinese New Year holidays, marking another significant step in the country's reopening efforts and boosting market sentiment. Investors are also hoping for an end-of-year rally after markets got whiplashed this month by hawkish signals from major central banks that fueled fears of a global recession next year. Domestically, the benchmark DAX 40 added 0.5% to end around 14,000 points, driven by gains among energy stocks.
8 hours ago
Russian Stocks Gain for 4th SessionRussia Stock Market
The ruble-based MOEX Russia index closed 0.6% higher at 2,151 on Tuesday with support from miners and metallurgists while investors continued to monitor dividend news, as Russia’s clouded macroeconomic backdrop provides limited opportunities for profits in equities despite strict capital controls to limit selling pressure. Norinickel, Severstal, and Mechel all added more than 1% in the session, benefiting from expectations of stronger base metal demand in top consumer China amid its Covid reopening. Metal exporters were also supported by the ruble’s slide past 70 per USD, making its goods more appealing to the foreign market. Banks also booked gains, extending yesterday’s rally triggered by signals of strong profits from major lender Sberbank.
8 hours ago
Texas Manufacturing Contracts for 8th MonthUnited States Dallas Fed Manufacturing Index
The Federal Reserve Bank of Dallas’ general business activity index for manufacturing in Texas fell to -18.8 in December of 2022 from -14.4 in the prior month, pointing to the eighth contraction in the activity. The company outlook posted its tenth straight negative reading at -12.8 from -15.2, and the uncertainty outlook index fell to 15.6 from 20.4. Also, capital expenditures sank sharply to -2.1 from 9.3, while finished goods inventories turned negative to -3.3 from 2.2. While improving slightly, the measure of new orders for manufacturers was negative for the seventh month at -9.2 from -20.9 in November, while production advanced to 9.7 from 0.8. Looking forward, general business expectations remained negative at -8.3 from -17.5.
8 hours ago
Brazilian Shares Extend RetreatBrazil Stock Market
Brazil’s Ibovespa stock index was nearly 1% down at 108,030 on Tuesday, extending the decline from the prior session in a lower volume of trading as investors awaited minister picks by President-elect Lula for the country's new government while monitoring the federal government’s increased fiscal risks. Worries that the country’s upcoming government will sharply increase public spending continued to support expectations of higher inflation and interest rates, driving the central bank to revise inflation expectations higher until 2025. Consequently, retail giants extended yesterday’s losses with Via Varejo and Magazine Luiza both dropping more than 4%.
9 hours ago
Wall Street Remains Under PressureUnited States Stock Market
The Dow lost roughly 100 points on Tuesday, while the S&P 500 and the Nasdaq were down 0.6% and 1.5%, respectively, as investors remained concerned about the negative impact of rate hikes, including poor economic growth, job losses, and downward earnings revisions. The Federal Reserve's commitment to holding rates at a higher level for a more extended period to tame inflation laid the foundation for a recession at some point in 2023. Rate-sensitive companies, including Microsoft, Amazon, Alphabet, Facebook, and Apple, were down between 1% and 2%. Meanwhile, Tesla fell nearly 5% after reports that the electric vehicle manufacturer plans to extend its light production schedule at its Shanghai plant in January. For December, the Dow is currently down 4.3%, the S&P 500 lost 6.6%, and the Nasdaq 100 dropped over 10%, with all three benchmarks heading for their worst annual performances since 2008.
9 hours ago
US Home Price Growth at 2-Year Low: Case-ShillerUnited States Case Shiller Home Price Index YoY
The S&P CoreLogic Case-Shiller 20-city home price index in the US rose by 8.6 percent from a year earlier in October 2022, the least since October 2020 and compared with market forecasts of an 8.2 percent increase. It was the sixth consecutive deceleration in home price growth as demand for housing has been hit by rising borrowing costs, low housing inventory, and stubbornly high inflation. The biggest gains were reported in Miami (21 percent), Tampa (20.5 percent), and Charlotte (15 percent). Meanwhile, prices grew the least in San Francisco (0.6 percent) and Seattle (4.5 percent). Compared to September, prices dropped by 0.8%, a fourth consecutive decline. "As the Federal Reserve continues to move interest rates higher, mortgage financing continues to be a headwind for home prices," Craig J. Lazzara, managing director at S&P DJI, said. "Given the continuing prospects for a challenging macroeconomic environment, prices may well continue to weaken."
10 hours ago
US Home Prices Stall in October: FHFAUnited States House Price Index MoM
The average price of single-family houses with mortgages guaranteed by Fannie Mae and Freddie Mac in the US was unchanged from a month earlier in October of 2022 after ticking up by 0.1 percent in the prior month. Among the different census regions, a 0.9% drop in home prices in the Pacific and a 0.2% decrease in the Mountain regions offset a 0.2% gain in South Atlantic and a 1.4% jump in New England. On a yearly basis, house prices rose by 9.8 percent, the lease since September of 2020 and easing from the upwardly revised 11.1 percent increase in the previous month. “Higher mortgage rates continued to put downward pressure on demand, weakening house price growth,” said Nataliya Polkovnichenko, Ph.D., Supervisory Economist, in FHFA’s Division of Research and Statistics.
10 hours ago
US Wholesale Inventories Growth AcceleratesUnited States Wholesale Inventories
Wholesale inventories in the US rose by 1.0 percent month-over-month to $933.6 billion in November of 2022, picking up from a revised 0.6 percent rise in the prior month, preliminary estimates showed. It was the 28th consecutive month of growth in inventories, as stocks rose for durable goods (1.3 percent vs. 0.8 percent in October) and non-durable goods (0.6 percent vs. 0.2 percent). On an annual basis, wholesale inventories grew by 21 percent in November.
11 hours ago
US Posts Smallest Goods Deficit in Nearly 2 YearsUnited States Goods Trade Balance
The US trade deficit in goods narrowed by 15.6 percent from a month earlier to USD 83.3 billion in November 2022, the largest decline since 2009, an advance estimate showed. It was also the smallest deficit since December 2020, as imports tumbled 7.6 percent to an over year low, as consumers have been shifting spending away from goods and toward services in recent months. Purchases fell for all categories: capital goods (-4.3 percent); consumer goods (-13.0 percent); industrial supplies (-6.0 percent); vehicles (-8.9 percent); and food, feeds and beverages (-5.5 percent). Meanwhile, exports were down at a slower 3.1 percent, dragged by sales of industrial supplies (-5.8 percent) and capital goods (-2.2 percent). Exports of consumer goods and vehicles, however, were up 4.0 and 1.0 percent, respectively.
11 hours ago
SENSEX Rises for Second SessionIndia Stock Market
Equities in India advanced for a second consecutive session on Tuesday, with the S&P BSE SENSEX adding more than 1% to close just shy of 61,000 points and tracking a broad rise in Asian markets on optimism about China reopening. Investors were also upbeat after the British Consultancy said in its annual World Economic League Table 2023 that India's GDP annual growth rate is expected to average 6.4% over the next five years. Metal stocks outperformed on news that China will further ease its strict coronavirus restrictions, with Tata Steel adding more than 6% to lead the SENSEX index.
12 hours ago
Wall Street Set to Open HigherUnited States Stock Market
Stock futures contracts tied to the three major indices were up more than 0.5% on Tuesday, with investors still hoping for an end-of-year rally after the market got whiplashed this month by a hawkish Federal Reserve outlook and expectations of a recession next year. Further evidence that inflation peaked, with the annual PCE price index hitting its lowest levels since October 2021, and optimism about China reopening brought a new wave of respite to markets. Still, the Federal Reserve's commitment to holding rates at a higher level for a more extended period to tame inflation at the expense of economic growth should limit any significant upside move. For December, the Dow is currently down 4%, the S&P 500 lost 5.8%, and the Nasdaq Composite dropped 8.5%, with all three benchmarks heading for their worst annual performances since 2008.
12 hours ago
French Unemployment Lowest Since 2011France Unemployed Persons
The number of people registered as out of work in mainland France fell by 64.7 thousand from the previous month to 2.810 million in November of 2022, the lowest since October 2011. Joblessness in the population aged 25 to 49 fell by 40.9 thousand to 1.641 million, and that of the population aged 50 or higher fell by 17.2 thousand to 0.804 million. Also, unemployment in the younger population decreased by 6.6 thousand to 0.366 million individuals. Compared to the same month of the previous year, the number of people registered as out of work fell by 311.3 thousand.
13 hours ago
The SENSEX Index increased 0.60%India Stock Market
In Mumbai the SENSEX Index went up by 361 points or 0.60 percent on Tuesday. The rise was driven by Tata Steel (6.14%), Tata Motors (2.73%) and Oil & Natural Gas Corporation (2.26%). Biggest losses came from Hindustan Unilever (-0.93%), Restaurant Brands Asia Ltd (-0.73%) and Nestle India Ltd (-0.61%).
14 hours ago
Palm Oil Rallies, Still Poised For Yearly FallCommodity
Malaysian palm oil futures were trading above the MYR 4,100 per tonne mark in December, as signs of strong export demand sent investors rushing to open new positions. Exports of Malaysian palm oil products for Dec. 1-25 rose 2.6% from a month earlier to 1,224,122 tonnes, cargo surveyors' data showed. On top of that, top buyer China relaxed its coronavirus restrictions further, raising hopes of a recovery in the world's second-largest economy while offering an upbeat outlook for demand. Meanwhile, investors continued to mull the European Union's move to stop companies from selling commodities linked to deforestation into its market. Palm oil is now down more than 10% in a rollercoaster 2022 that saw the Malaysian benchmark hit a record high of MYR 7,300 in March amid tight supplies due to Russia's invasion of Ukraine but paring those gains due to competition from rival Indonesia and concerns about a global recession.
15 hours ago
French Stocks Gain on TuesdayFrance Stock Market
The CAC 40 index rose 0.9% to trade around the 6,565 level on Tuesday, with almost all constituents trading in the green and tracking European peers higher, as investors welcomed China's announcement that inbound travelers will not be quarantined from January 8th, raising hopes of a recovery in the world's second-largest economy. Upbeat sentiment came despite hawkish messages from central banks and persistent fears of a global recession. Among top gainers, China-exposed luxury firms LVMH and Hermes advanced more than 2% each.
15 hours ago
Russian Stocks Edge HigherRussia Stock Market
The ruble-based MOEX Russia index traded marginally higher on Tuesday, as gains in oil & gas, utilities and telecom companies were almost all offset by losses across financials, chemicals and consumer goods and services. The oil market was slightly higher in thin trading following a long weekend, and metal prices were also higher as China reversed Covid restrictions further while winter storms across the US disrupted oil flows. Meanwhile, the rouble weakened to 70 against the dollar, on the prospect of lower export revenues after an oil embargo and price cap came into force.
15 hours ago
Copper Hits Over 6-Month High on China HopesCommodity
Copper futures surged to $3.9 per pound level, the highest level since June 22nd, amid hopes of demand revival in China after the world's second-largest economy announced it would stop requiring inbound travelers to go into quarantine starting from January 8th. Elsewhere, prospects of lower copper production in South America continued to drive shortage concerns. Output from top producer Chile slid 6.7% in the first three quarters of the year, with mine protests in Peru stifling the activity. Commodity trader Trafigura warned that global copper stocks have fallen to record lows, with current inventories being enough to supply world consumption for just 4.9 days. Finally, mining giant Glencore estimated a supply shortfall of 50 million tonnes in 2023. Still, copper is down more than 11% so far this year, as global recession concerns mounted after major central banks delivered hawkish outlooks on monetary policy to curb inflation.
15 hours ago
FTSE MIB Tops 24,000 MarkItaly Stock Market
Equities in Italy started a holiday-shortened week higher, with the FTSE MIB index breaking above the 24,000 mark on optimism about China reopening. The world's second-largest economy said it would drop its quarantine requirements for inbound visitors, easing three-year border controls and raising hopes of a recovery in economic activity. Juventus Football Club and Saipem were among the top gainers, up 3.4% and 2.6%, respectively.
15 hours ago
Czech Consumer Morale Falls in DecemberCzech Republic Consumer Confidence
The consumer confidence indicator in the Czech Republic fell by 1.3 points to 74.7 in December 2022, following a slight recovery of 76 in the previous month. Consumers’ rate their current financial situation as worse while the number of respondents expecting further deterioration over the next 12 months were unchanged. Also, households’ do not find the current time suitable for making large purchases. Meanwhile, consumers were less concerned about the deterioration of the overall economic situation, while expectations of further price growth have decreased.
15 hours ago
Czech Business Morale at Over 1-1/2 Year LowCzech Republic Business Confidence
The business confidence indicator in the Czech Republic decreased by 0.5 points from a month earlier to 92.5 in December of 2022, pointing to the new lowest reading since March a year earlier, as sentiment weakened among constructors (107.7 vs 115.6) and retailers (92.7 vs 99). On the other hand, sentiment improved among manufacturers (91 vs 90.4) while for those service providers remained unchanged (92.4).
16 hours ago
US Natural Gas Futures Rebound from 9-Month LowCommodity
US natural gas futures rose to $5.2/MMBtu in the last week of December, rebounding from a 9-month low of $4.8 hit before the Christmas break, due to lower production and supply constraints after wells and pipes froze due to extreme cold. Output fell to as low as 84.2 bcf on Dec 24th and was still around 10% below normal levels on Monday. Meanwhile, temperatures in Midland are seen rising while the Northeast is expected to continue to see below-freezing conditions. Natural gas prices in the US have been subdued amid forecasts for warmer weather and as investors continue to monitor the situation at the Freeport LNG plant. Also, the latest EIA report showed a smaller-than-expected storage draw as milder weather kept heating demand low and lots of wind power reduced the number of gas generators needed to produce electricity.
16 hours ago
Thailand Imports Unexpectedly RiseThailand Imports YoY
Imports to Thailand unexpectedly rose by 5.6 percent year-on-year to USD 23.65 billion in November of 2022, missing market forecasts of a 0.8 percent fall and rebounding from a 2.1 percent drop in the previous month. The ministry said that many imports will be used for producing goods to be shipped out again. For the first eleven months of the year, arrivals jumped 16.4 percent from the same period in 2021.
16 hours ago
European Shares Rise as China Eases COVID CurbsGermany Stock Market
European stock markets traded higher on Tuesday, joining a global stock rally, as investors welcomed news that China will stop requiring inbound travelers to go into quarantine starting from January 8th ahead of Chinese New Year holidays, marking another major step in the country's reopening efforts and boosting market sentiment. Investors are also hoping for an end-of-year rally after stocks got whiplashed this month by hawkish signals from major central banks that fueled fears of a global recession next year. The pan-European STOXX 600 added 0.4% and Germany's DAX 40 rose about 0.8% at 14,050, led by gains in travel and consumer goods shares.
16 hours ago
European Natural Gas Hovers at 6-1/2-Month LowCommodity
Dutch front-month gas futures were at €83/MWh in the last week of the year, close to their lowest level in 6-1/2 months and following a 28% drop in the previous week, amid mild weather and ample supplies. Natural gas prices in Europe are more than 75% below record levels of nearly €350 hit in August, as record LNG imports, increased wind generation, and fuller-than-normal stockpiles ease concerns about shortages. Storage facilities in Germany were 88.2% full as of December 25th and the EU average held at 83.1%, above the five-year seasonal average. At the same time, supplies from Russia sent through Ukraine have been stable and weather forecasts point to normal to above-average temperatures through early January. On the political front, EU leaders reached a deal to cap natural gas prices. The cap would take effect if prices on the front-month Dutch TTF contract exceed €180/MWh for three days, and if the price of LNG is above €35/MWh.
16 hours ago
Thailand Exports Fall More than ExpectedThailand Exports YoY
Exports from Thailand dropped by 6% from a year earlier to USD 22.3 billion in November of 2022, worse than market consensus of a 5.2% fall, following a 4.4% decline month earlier. This was the second straight month of decrease in exports, due to a global slowdown and China's lockdown restrictions, the commerce ministry said. Exports of farm and agro-industrial products fell for the second straight month, down 2% from a year earlier. Meanwhile, exports of industrial goods dropped by 5.1%. Among major markets, exports shrank to China (-9.9%), and Southeast Asia (-9.5%), while rose to the US (1.2%). Considering the first eleven months of the year, exports grew 7.6 % year-on-year, already exceeding the government’s full-year target of 4% growth.
16 hours ago
Lithuania Retail Sales Fall for 6th MonthLithuania Retail Sales YoY
Retail sales in Lithuania declined by 1.7 percent year-on-year in November of 2022, following an upwardly revised 3.2 percent fall in the previous month. This was the sixth straight month of decrease in retail trade, with sales declining for non-food products (-4.3 percent vs -2.3 percent) and food, beverages, and tobacco (-7 percent vs -8 percent in October). Meantime, sales grew at a faster pace for automotive fuel in specialized stores (13.1 percent vs 2.2 percent). On a monthly basis, retail sales fell by 1.1 percent, following a marginally revised 1.2 percent drop in October.
16 hours ago
Thailand Posts Largest Trade Gap in 3 MonthsThailand Balance of Trade
Thailand posted a trade deficit of USD 1.34 billion in November of 2022, shifting from a USD 1.32 billion surplus in the same month a year earlier and compared with market consensus of a USD 0.2 billion gap. This was the largest trade shortfall since August, as imports surged while exports plunged, due to a global slowdown and China's lockdown measures. Sales shrank 6 percent yoy, compared to market consensus of a 5.2 percent fall, while imports unexpectedly jumped 5.6 percent, missing market expectations of a 0.8 percent drop.
16 hours ago
Norway Retail Sales Rebound in NovemberNorway Retail Sales MoM
Norway's retail trade jumped 0.9% from a month earlier in November of 2022, following a downwardly revised 0.2% fall in the previous month, due to a rise in sales of automotive fuel (3.4% vs -3.5%), cultural & recreation goods (2.7% vs -0.7%), ICT-equipment (1.9% vs -1%), other household equipment (1.8% vs -0.2%), non-specialised stores (0% vs -0.2%) and trade not in stores (3.2% vs 2%). On the other hand, sales of food, beverages etc rose softer (0.1% vs 1.1%), while sales of other goods went down (-0.8% vs -0.2%). On a yearly basis, retail sales dropped 3.6 percent in November, after a 5 percent decrease in October.
16 hours ago
European Markets Head for Higher OpenGermany Stock Market
European equity markets were headed for a higher open on Tuesday, extending a global stock rally after China announced that it will end quarantine requirements for inbound travelers on Jan. 8, symbolizing an end to its zero-Covid policy and boosting market sentiment. Investors are also hoping for an end-of-year rally after stocks got whiplashed this month by hawkish signals from major central banks that fueled fears of a global recession next year. Meanwhile, there are no major earnings or data releases in Europe on Tuesday. DAX futures were up about 0.5% in early trade, while Stoxx 600 futures rose 0.4%.
17 hours ago
China Stocks Climb on Reopening BoostChina Stock Market
The Shanghai Composite rose 0.98% to close at 3,096 while the Shenzhen Component gained 1.16% to 11,107 on Tuesday, rising for the second straight session after China announced that it will end quarantine requirements for inbound travelers starting on Jan. 8, sparking hopes for a faster economic recovery. Investors also digested data showing industrial profits in China fell 3.6% year-on-year in the January-November period, reflecting economic disruptions brought by Covid restrictions. Property, industrial and commodity-linked stocks led the charge, with strong gains from Jiangsu Dagang (4.5%), SHN Zhenye (9.9%), China Southern Power (7.2%), Zhejiang Construct (7.6%) and Shandong Chiway (8.8%). Other heavyweight firms also advanced, including Sungrow Power (5.8%), Xi'an Catering (10%), East Money Information (2.2%), Shenzhen Infinova (3.5%) and Tongwei (2.8%).
17 hours ago
Norway Household Spending Rises the Most in 8 MonthsNorway Household Spending MoM
Household consumption of goods in Norway advanced by 2.6 percent month-over-month in November 2022, accelerating from an upwardly revised 0.9% gain in the previous month. It was the strongest growth in household spending since March, due to faster rises in purchases of vehicles and petrol (12.1 percent vs 3.6 percent), amid a rebound in food, beverages and tobacco (0,3% vs -0.6%). Meanwhile, spending on other goods grew by 0.5%, after a 0.6% growth in the prior month. By contrast, spending on electricity and heating fuels fell by 1.0%, reversing from a 3.8% increase in October.
17 hours ago
Finnish Consumer Morale Hits New Record LowFinland Consumer Confidence
The consumer confidence indicator in Finland fell to -18.50 in December of 2022, pointing to the lowest level since records began in 1995 and following a -16.90 reading in the previous month. Household sentiments about their own economy at present grew more pessimistic (-13.0 vs -6.4 in November), along with expectations concerning their own economy (-2.4 vs 0.2). Meanwhile, assessment of Finland’s economy at present further weakened (-55.2 vs -54.3), while expectations for Finland’s economy over the next 12 months improved (-25.7 vs -31), but remains at a very weak level. Also, worries over unemployment heightened (-19.7 vs -15.3), as the consumer’s perception of their financial situation dropped (22.3 vs 27.3), while expectations concerning inflation slightly decreased (6.2 vs 6.5).
17 hours ago
Chinese Yuan Climbs on Reopening BoostChina Currency
The offshore yuan appreciated toward 6.95 per dollar after China announced that it will end quarantine requirements for inbound travelers starting on Jan. 8, symbolizing an end to its zero-Covid policy and sparking hopes for a faster economic recovery. Health authorities also said that China’s Covid management will be downgraded to the less strict Category B from the current top-level Category A. Meanwhile, investors reacted to data showing industrial profits in China fell 3.6% during the first 11 months of the year to 7.7 trillion yuan, accelerating from a 3% drop in the January-October period. China’s economic growth was just 3% in the first three quarters of this year and is expected to stay around that rate for the full year, one of its worst years in almost half a century, as observed by Reuters.
17 hours ago
Finnish Business Mood Remains at 2-Year LowFinland Business Confidence
The manufacturing confidence indicator in Finland stood at -8 in December 2022, the same as in the previous month and remaining at its lowest reading since November 2020. Expectations about production for the coming months turned pessimistic while stocks of finished goods declined from the previous month’s level. Moreover, order books diminished from the November’s levels and were below normal levels. On a positive note, production capacity was fully utilized by 70% of the respondents.
18 hours ago
Japanese Shares Rise as Traders Mull DataJapan Stock Market
The Nikkei 225 Index rose 0.16% to close at 26,449 while the broader Topix Index gained 0.4% to 1,910 on Tuesday, extending gains from the previous session as investors digested data showing Japan’s unemployment rate edged down in November, while retail activity in the country grew less than expected. On Monday, the Bank of Japan also pushed back against speculations that the central bank would soon exit its ultra-loose monetary policy following a surprise adjustment to the 10-year yield target last week. Moreover, regional sentiment was lifted after China announced that it would drop Covid isolation measures for inbound travelers starting in early January, raising hopes for a wider economic reopening. Notable gains were seen from index heavyweights such as Mitsubishi UFJ (1.9%), Sumitomo Mitsui (1.7%), Fast Retailing (2.1%), Oriental Land (3%) and Shiseido Company (6.1%).
18 hours ago
Sensex Muted in Early DealsIndia Stock Market
The BSE Sensex rose 69.5 points or 0.1% to 60,635.9 in early deals on Tuesday, building gains from the previous session and tracking a broad rise in Asian markets, after China announced Monday that starting early January to drop quarantine requirements for inbound visitors. Investors were also upbeat after the British Consultancy said in its annual World Economic League Table 2023 that over the next five years, India's GDP annual growth rate is expected to average 6.4%. Almost all of the sectors were trading in the green, supported by the realty, metal index, auto, and banking sectors. Shares of Tata Steel jumped (3.6%), as did JSWS Steel (3.3%), Hindalco (3.0%), Tata Motors (2.5%), while Oil & Natural Gas Corporation rose 2%, amid a rise in oil prices.Meanwhile, Suven Pharma shares rose 3%, after the company announced that private equity major Advent International will acquire a 50.1% stake in Suven Pharmaceuticals from its promoter Jasty family.
18 hours ago
Thailand Industrial Output Drops More Than ExpectedThailand Industrial Production
Industrial production in Thailand dropped by 5.60% year-on-year in November of 2022, well above market expectations of a 3.70% decline and following an upwardly revised 3.96% decrease in October. It was the second consecutive month of contraction, as production dropped in most industrial groups namely; petroleum and refining products (-20.58%), basic iron & steel (-14.27%), food products (-1.62%), rubber & plastic products (-4.97%), apparel except for garment stores (-12.30%) and computers & peripherals (-47.67%). Meanwhile, output growth rose for automotive (12.95%) and electronic components & boards (3.08%). On a monthly basis, industrial output rose by 1.55%.
18 hours ago
Japan Housing Starts Unexpectedly FallJapan Housing Starts
Japan's housing starts unexpectedly dropped by 1.4 percent year-on-year in November 2022, missing market forecasts of a 1.5 percent rise and following a 1.8 percent decline in the prior month. This was the second straight month of decrease in dwelling starts, amid declines in new construction for owned (-15.1 percent vs -18.7 percent in October), issued (-23.6 percent vs 81.6 percent), built for sale (-0.8 percent vs 4.8 percent), prefabricated (-2.6 percent vs 12.0 percent), and two-by-four (-3.3 percent vs -5.3 percent). Meanwhile, dwelling starts of rented continued to grow (11.4 percent vs 7.3 percent).
19 hours ago
"""
articles, headlines =  new_magic(news_string)


news_cache = {"12/27/2022":{"headlines":headlines,"articles":articles}}