def new_magic(date_data:str):
  split_data = date_data.split("\n")
  split_data = [data for data in split_data if data != ""]

  headlines = []
  articles = []
  dividers = []
  for index in range(len(split_data)):
    if (index+1) % 3 == 0:
      split_data[index] = "divider"

  split_data = [data for data in split_data if data != "divider"]

  headlines = []
  articles = []
  for index, headline in enumerate(split_data):
    if index % 2 == 0:
      headlines.append(split_data[index])
    else:
      articles.append(split_data[index])

  return articles, headlines


news_string = """
Brazil Inflation Rate Eases to 21-Month LowBrazil Inflation Rate
The annual inflation rate in Brazil eased to 5.90 percent in November of 2022 from 6.47 percent in the prior month, almost in line with market expectations. It was the lowest reading since February 2021, as prices dropped for transport (-0.93 percent vs. 1.55 percent in October) while easing for housing (0.61 percent vs. 1.14 percent). On the other hand, food & non-alcoholic beverages prices increased (11.84 percent vs. 11.27 percent). Monthly, consumer prices rose by 0.41 percent, slightly below market forecasts of a 0.53 percent gain, following a 0.59 percent gain in October.
70 minutes ago
Wheat Rebounds Ahead of WASDE ReportCommodity
Chicago wheat futures were at $7.3 per bushel, rebounding from the 14-month low of $7.05 hit on December 6th as investors readjusted positions ahead of the USDA’s WASDE report due today. Still, prices hover well below levels before February as Russia’s invasion of Ukraine threatened global supply. Top exporter Russia achieved a record-high harvest in the current marketing year, extending competition into North America as poor export data divulged by the USDA without any production problems drove bids to decline in price. In the meantime, shipments from Ukraine continued after Russia agreed to extend the deal that guarantees a trade corridor for vessels carrying Ukrainian grain in the Black Sea for another four months. According to Ukrainian authorities, the country was able to export more than 11 million tonnes of grain by ships since the start of the deal on August 1st, significantly easing shortage concerns despite reporting a 6% drop in farm acreage due to destruction from the war.
84 minutes ago
North Macedonia Jobless Rate Down to 14.3% in Q3Macedonia Unemployment Rate
The unemployment Rate in North Macedonia decreased to 14.3 percent in the third quarter of 2022 from 14.5 percent in the previous period, as the number of unemployed declined by 2.0 thousand to 115.3 thousand and the number of employed was little-changed at 693.1 thousand. The employment rate was flat at 47.3 percent, while the activity rate edged down to 55.2 percent from 55.3 percent.
100 minutes ago
US Stock Futures RiseUnited States Stock Market
Stock futures contracts tied to the three major indices were up roughly 0.5% on Friday, putting Wall Street on track to extend gains as investors await a slew of economic data later today, including producer-price figures and the University of Michigan consumer report. Some signs that the labor market is starting to cool, with continuing jobless claims climbing to the highest since early February, brought some respite to markets rattled by uncertainty about the direction of the Federal Reserve's interest rate rises. The sentiment was also boosted by expectations of a recovery in China's economy, with the world's largest economy relaxing many of its stringent COVID-19 controls and signaling more support for the property sector. On the corporate side, DocuSign jumped over 10% on better-than-expected quarterly results, while Lululemon tumbled 7% after issuing a weak fourth-quarter guidance.
102 minutes ago
Belgium Industrial Output Slips in OctoberBelgium Industrial Production
Belgium’s industrial production slumped by 2.8% year-on-year in October of 2022, following an upwardly revised 1.3% increase in the previous month. Output decreased for all categories: mining & quarrying (-9.5% vs -0.8% in September); manufacturing (-2.7% vs 0.4%) and electricity gas, steam, and air conditioning (-2.8% vs 14.9%). On a monthly basis, industrial output declined 2%, after an upwardly revised 7.6% rise in the prior month.
106 minutes ago
Albania Inflation Rate Slows to Four-Month LowAlbania Inflation Rate
The annual inflation rate in Albania slowed to 7.9 percent in November of 2022 from 8.3 percent in the previous month. It was the lowest reading since July, as prices advanced at a softer pace for housing & utilities (6.2 percent vs. 6.5 percent in October), furniture household & maintenance (6.2 percent vs. 6.5 percent), and transport (9.6 percent vs. 16.9 percent). On the other hand, prices rose faster for food & non-alcoholic beverages (5.8 percent vs. 5.7 percent) and miscellaneous goods & services (3.6 percent vs. 3.3 percent). Monthly, consumer prices declined 0.3 percent after a 0.4 percent increase in October.
119 minutes ago
Portugal Posts 2nd Largest Trade Gap on RecordPortugal Balance of Trade
Portugal's trade deficit widened to EUR 2.8 billion in October 2022, the second-largest on record, from EUR 2.0 billion in the same month last year. Imports increased 26.2 percent to EUR 9.6 billion, mainly due to purchases of industrial supplies (19.1 percent) mostly from Ireland and Spain, and machinery and other capital goods (34.0 percent) mostly from China. Meanwhile, exports advanced at a softer 21.1 percent to EUR 6.7 billion, on the back of rising sales of machinery and other capital goods (43.6 percent) and industrial supplies (14.0 percent), mostly to Spain. Considering January to October, the trade gap widened sharply to EUR 25.5 billion from EUR 14.7 billion in the same period of 2021.
2 hours ago
Greece Industrial Output Falls the Most in 6 MonthsGreece Industrial Production
Industrial production in Greece shrank 2.5% year-on-year in October of 2022, following an upwardly revised 1.2% fall in the previous month. It marks the second consecutive month of a downturn in industrial activity and at the steepest pace since April, led by electricity supply (-21.6%). Meanwhile, production increased for mining & quarrying (2.8%), manufacturing (2.4%) and water supply (0.4%). On a monthly basis, industrial production rose by 0.6%, after an upwardly revised 3.2% slump in the previous month.
2 hours ago
Sensex Books Worst Week in 2 MonthsIndia Stock Market
The BSE Sensex closed nearly 400 points lower at 62,180 on Friday, dropping 1% on the week to mark its poorest week in over two months as concerns of a slowing economy pressured growth stocks in Mumbai. Tech shares tanked, led by a 6.5% decline for HCL Technologies in the session after the firm warned of incoming furloughs and spending cuts by clients in the US, driving its CEO to state the revenue growth outlook will likely be at the lower end of the company’s latest forecasts for the current financial year. Tech Mahindra and Infosys followed with each losing more than 3%. On the other hand, banks softened the blow and closed sharply in the green, led by a 0.9% increase for the State Bank of India. In the meantime, market consensus for domestic inflation to be released next week pointed to an inflation rate of 6.4%, set to remain above the RBI’s upper target of 6% for the 11th straight month.
2 hours ago
Greek Inflation Rate Eases to 9-Month LowGreece Inflation Rate
Greece's consumer price inflation eased for a second straight month to 8.5 percent in November 2022, down from 9.1 percent in the previous period. The rate hit its lowest level since February, but remained well above the European Central Bank's target of 2 percent. Prices rose at a softer pace for housing (4.8 percent vs 11.2 percent in October) and hotels, cafés and restaurants (8.0 percent vs 8.6 percent). On the other hand, inflation accelerated for food and non-alcoholic beverages (15.0 percent vs 14.8 percent), transport (14.5 percent vs 13.8 percent), clothing and footwear (10.9 percent vs 5.4 percent), household equipment (11.0 percent vs 10.6 percent), and miscellaneous goods and services (4.9 percent vs 4.2 percent). Meanwhile, the core inflation rate, which excludes volatile items such as unprocessed food and energy, hit an all-time high of 5.9 percent. On a monthly basis, consumer prices were unchanged in November, following a 1.2 percent drop in October.
3 hours ago
The SENSEX Index dropped 0.62%India Stock Market
In Mumbai the SENSEX Index fell 389 points or 0.62 percent on Friday. Leading the losses are Hcl Technologies (-6.59%), Tech Mahindra Ltd (-3.59%) and Infosys (-3.18%). Top gainers were Nestle India Ltd (2.29%), Sun Pharmaceuticals (1.39%) and Titan Company Ltd (1.11%).
3 hours ago
Slovenia Industrial Output Grows the Least in 8 MonthsSlovenia Industrial Production
Industrial production in Slovenia rose by 0.1 percent year-on-year in October of 2022, easing from an upwardly revised 1.1 percent gain a month earlier. It was the softest growth in industrial activity since February as mining and quarrying declined sharply (-28.2 percent vs 40.5 percent), while electricity, gas, steam and air conditioning supply have also dropped further (-40.8 percent vs -34.5 percent). Meanwhile, output growth in the manufacturing sector accelerated (4.7 percent vs 4.0 percent). On a seasonally adjusted monthly basis, industrial production fell by 0.3 percent in October, following a 1.7 percent drop in September.
3 hours ago
Italian Shares Hover FlatItaly Stock Market
The FTSE MIB index hovered close to the flatline at the 24,200 mark on Friday, tracking the muted sentiment in Europe as investors continued to weigh on expectations of tighter policy and the start of quantitative tightening in Europe against the reopening of the Chinese economy. Energy shares continued to underperform the broader sector as oil prices saw a sharp retreat on the week. Tenaris led the losses, dropping nearly 1%. On the other hand, Milan’s heavyweight financial sector led the gains, carried by a near 1% jump for UniCredit. In the meantime, defense manufacturer Leonardo was 0.6% higher following news that Italy will collaborate with the UK and Japan on the production of a new fighter jet. On the week, Italy's benchmark stock index is set to drop 1.5%.
3 hours ago
Bulgaria Retail Sales Growth Eases in OctoberBulgaria Retail Sales YoY
Bulgaria’s retail sales eased by 0.6% year-on-year in October 2022, following an upwardly revised 2.3% rise in the previous month, mainly due to the further decreases in sales from food, beverages and tobacco (-5.4% vs -2.8%), computers, peripheral units, software and telecommunication equipment (-4.9% vs -8.8%), and medical and orthopedic goods (-9.1% vs -5.6%). Meanwhile, sales accelerated primarily for information and communication equipment (1.7% vs -1.3%) and audio, video equipment, hardware, paints and glass; electrical household appliances (7.4% vs 4.9%). On a seasonally adjusted monthly basis, sales fell by 0.4%, after a downwardly revised 0.1% increase in September.
3 hours ago
Bulgaria Industrial Output Growth Slows to 1-1/2-Year LowBulgaria Industrial Production
Industrial output growth in Bulgaria eased to 5.7 percent year-on-year in October 2022, down from a downwardly revised 10.7 percent in the previous month. It was the softest growth since February 2021 as output declined sharply for electricity, gas, steam and air conditioning supply (-30 percent vs 1.6 percent). In the meantime, output continued to accelerate for manufacturing (14.2 percent vs 14 percent) while output fell at a softer pace for mining & quarrying (-2.1 percent vs -2.4 percent). Compared to the previous month, industrial production declined 2 percent, after a revised 2.6 percent fall in September.
3 hours ago
Slovakia Trade Surplus Narrows in OctoberSlovakia Balance of Trade
Slovakia’s trade surplus narrowed to EUR 199.5 million in October of 2022 from EUR 291 million in the same month of the previous year and against market expectations of EUR 174.2 million deficit. Imports increased by 21.6% to EUR 9.2 billion, mainly boosted by purchases of machinery and transport equipment (18%), and mineral fuels, which include imports of natural gas, oil and electricity. At the same time, exports rose by 18.3% to EUR 9.4 billion, also led by sales of machinery and transport equipment (22%), in particular automobiles, and mineral fuels. The majority of goods from both of these sections were directed towards the EU markets. Considering the first ten months of the year, the country posted a deficit of EUR 2.5 billion, compared with a surplus of EUR 2.1 billion in the same period a year earlier.
3 hours ago
Malta October Industrial Output Growth at 4-Month LowMalta Industrial Production
Industrial production in Malta advanced by 7.2% year-on-year in October of 2022, slowing from a downwardly revised 13.2% rise in the previous month. It marks the fourth consecutive month of growth in industrial activity but the weakest in the sequence of increases, as production slowed for intermediate goods (3.7% vs 9.6% in September), and to a lesser extent, for consumer goods (12.9% vs 17.1%) and capital goods (10.7% vs 12.3%). Additionally, output declined for energy (-6.2% vs 9.7%). On a seasonally adjusted monthly basis, industrial output shrank by 2.5%, the most in six months, following a 1.2% increase in the preceding month.
3 hours ago
French Stocks Fall to Over 3-Week LowFrance Stock Market
The CAC 40 index traded little changed around a three-week low of 6,627 on Friday, as trading activity remained subdued in Europe amid growing recession fears while investors await key monetary policy decisions from the ECB, the Fed and the BoE next week. On the corporate front, Saint Gobain was advancing the most, with gains of 1.4%. By contrast, Worldline (-4.4%) and Stellantis NV (-2.6%) posted the biggest losses. On the week, the CAC 40 in on track to lose more than 1.5%.
4 hours ago
Austria Industrial Production Growth at Near 2-Year LowAustria Industrial Production
Industrial production in Austria rose by 3.9% year-on-year in October 2022, easing from an upwardly revised 5.9% increase in the previous month. It was the softest growth since February 2021, as output production slowed for capital goods (4.5% vs 12.7% in September), consumer durables (7.4% vs 8.8%) and consumer non-durables (3.7% vs 4.1%). Conversely, production for intermediate goods accelerated (6.3% vs 3.9%), while energy recorded a decline (-0.5% vs 8.7%). On a seasonally adjusted monthly basis, industrial production fell by 0.6%, but a softer rate compared to a downwardly revised 1.2% drop in September.
4 hours ago
Russian Stocks Set to Close Week LowerRussia Stock Market
The MOEX Russia index was 0.3% lower at the 2,178 level on Friday, dropping for the fourth straight session and set to close the week marginally in the red with pressure from energy producers and banks. Heavyweight oil companies were set to be among the sharpest losers of the week, pressured by a darkening outlook for the sector amid the start of the EU’s oil embargo, the G7’s $60/barrel price cap, and retaliatory threats by the Kremlin that further pressure exports. Even though the Western price ceiling has not been triggered since market prices hover well below the cap, added risk due to heightened geopolitical tension has increased the cost for the use of tankers and insurance, dragging Urals oil prices to their biggest discount to Brent since August. Surgut led the losses and fell 0.6%. On the other hand, hopes of stronger demand from China amid eased Covid lockdowns supported metallurgists to close the week sharply higher, with Mechel and Rusal adding nearly 1% in the session.
4 hours ago
Madrid Stocks Cautiously HigherSpain Stock Market
The IBEX 35 index was trading slightly above the 8,240 level on Friday, after five consecutive sessions of decline, amid hopes that China's economy would pick up pace due to the de-escalation of COVID-19 strict measures, while traders awaited key monetary decisions from both the Federal Reserve and the ECB next week. On the corporate front, Amadeus was leading the gains, rising more than 3.5%, after Goldman Sachs upgraded it to "buy" from "neutral" and raised its target price to 70 euros. It also added the company's stock to its conviction list. Grifols followed it, rising over 2%. On the negative side, Indra, Repsol, CaixaBank and Acerinox were the worst performers, shedding over 1% each. The IBEX 35 was on track to decline for the second straight week, losing about 1.6%.
4 hours ago
Bulgaria Construction Output Rebounds in OctoberBulgaria Construction Output
Construction output in Bulgaria rose by 1.8 percent year-on-year in October of 2022, following an upwardly revised 1.4 percent slump in September, as both building construction (1.9 percent vs -1.6 percent in September) and civil engineering (1.8 percent vs -1.1 percent) increased significantly. On a seasonally adjusted monthly basis, construction output went up 0.7 percent, following a 0.2 percent rise in the previous month.
4 hours ago
South African Stocks Rise for 2nd DaySouth Africa Stock Market
The JSE FTSE All Share index was trading slightly above the 74,900 level on Friday, the second straight session of gains, mainly boosted by sharp gains in tech stocks amid hopes of a boost in the Chinese economy helped by the easing of its stringent Covid policy. Industrials and luxury retailer Richemont provided further support. Meanwhile, investors continued to weigh the chances of a recession amid prospects of continued monetary policy tightening until inflation is controlled. Locally, political uncertainty surrounding President Cyril Ramaphosa lingers as he faces a possible impeachment due to the Phala Phala scandal. The National Assembly will decide on December 13 whether to adopt the report and set up its own inquiry. Meanwhile, Eskom spokesperson Sikonathi Mantshantsha warned that the current intense load shedding is unlikely to improve in the next six to 12 months. The benchmark index is set to rise 0.8% this week, on track to post its third straight weekly gain.
4 hours ago
Copper Approaches 5-Month HighCommodity
Copper futures rose to $3.9 per pound, hovering close to levels last seen in June amid worries of incoming shortages and expectations that industrial demand will rise in top consumer China. Lower supply in South America continued to drive concerns of shortages in the near future, as output from top producer Chile slid 6.7% in the first three quarters of the year and mine protests in Peru hamper production. Commodity trader Trafigura warned that global copper stocks have fallen to record lows with current inventories enough to supply world consumption for just 4.9 days, and mining giant Glencore estimates a supply shortfall of 50 million tonnes in 2023. Eased covid restrictions in China also supported prices by raising hopes of improved demand. Also, the PBoC cut its reserve ratio by 25bps to stimulate industrial activity and combat increasing signs of a slowing economy.
4 hours ago
UK Natural Gas Hovers Near Three-Month Peak, Poised for Fourth Weekly GainCommodity
UK natural gas futures were trading around the 350 pence a therm mark, up more than 90% since their October lows and hovering close to levels not seen since mid-September, amid prospects of higher heating demand on forecasts for an Artic blast over the next two weeks, with temperatures in the UK dropping below freezing. On top of that, low domestic wind output also boosts natural gas demand for electricity generation. Keeping a lid on prices were healthier supplies, with natural gas storage facilities in the UK remaining 100% full. At the same time, the US has agreed to increase natural gas exports to the UK as part of a joint effort to reduce costs and limit Russia's impact on western energy supplies. For the week, the benchmark rose more than 3%, on track to post a fourth consecutive weekly gain.
4 hours ago
Japan 10Y Bond Yield Hits 6-week HighJapan Government Bond 10Y
Japan 10 Year Government Bond Yeld increased to a 6-week high of 0.257%
4 hours ago
Slovak Industrial Output Falls Less than Expected in OctoberSlovakia Industrial Production
Industrial production in Slovakia shrank by 2.6 percent from a year earlier in October of 2022, from 1.9 percent slump in the previous month and less than the market expectations of 2.7 percent fall. It marked the fifth consecutive month of declines in industrial activity as output fell for manufacturing (-1.8 percent vs 3.3 percent), due to the decline in manufacture of machinery & equipment (-3.2 percent vs 0.5 percent) and a sharp slowdown in output growth of both transport equipment (1.7 percent vs 22.8 percent) and pharmaceutical, medicinal chemical & botanical products (20.1 percent vs 52 percent). On the other hand, output increased sharply for mining & quarrying (179.3 percent vs 1.8 percent) while output declined at a softer pace for electricity, gas, & steam (-28.3 percent vs -33.7 percent). On a seasonally adjusted monthly basis, industrial output rose to 1.3 percent, rebounding from 0.8 percent fall in September.
4 hours ago
Iron Ore Advances to 4-Month HighCommodity
Prices for iron ore cargoes with a 63.5% iron ore content for delivery into Tianjin rose to $110 in December, the highest since mid-August, as eased Covid curbs and measures to stimulate the economy in top consumer China increased expectations for higher demand. Key Chinese cities lose lockdown rules after protests, raising hopes that other industrial hubs would follow. Also, the country’s largest commercial banks agreed to extend $162 billion in fresh credit lines to private developers to fight the sector’s liquidity crunch, and the PBoC further cut banks' reserve requirement ratio. Earlier, the national bond authority expanded a key financing program by $35 billion to support the sales of bonds after a period of defaults increased the cost of credit for residence builders. Still, prices are 33% below their March peak as concerns are still in place about the debt-ridden property sector in China and as supply from Ukraine remains steady despite the war.
5 hours ago
FTSE 100 Remains Under Pressure, Set for a Weekly DeclineUnited Kingdom Stock Market
Equities in London extended losses for a fourth consecutive session on Friday, with the benchmark FTSE 100 hovering around the 7,450 mark, as losses in the energy sector offset gains among materials. Oil giants BP and Shell were among the biggest laggards, down roughly 1.5% and 1%, respectively. Conversely, Rio Tinto added almost 2% to lead the FTSE 100. In a week soft in terms of economic data, sentiment remained dominated by worries about the pace of interest rate rises to combat inflation on a backdrop of slowing growth. Still, signs that China is gradually moving away from its stringent COVID-19 controls, with the government making it easier to travel domestically, keep businesses operating, and allow patients to quarantine at home, offered investors some respite. Given the above, the export-oriented index is down more than 1% this week, on track to post its first weekly decline in four.
5 hours ago
Norway Producer Inflation Picks Up in NovemberNorway Producer Prices Change
Producer prices in Norway rose 22.3 percent year-on-year in November of 2022, following a 19.8 percent increase in the prior month, as prices accelerated for both extraction of oil & natural gas (21.8 percent vs 12.9 percent) and energy goods (26.7 percent vs 21.3 percent). Meanwhile, prices rose at softer pace for manufacturing (20.7 percent vs 21.4 percent) and electricity, gas, & steam (43.2 percent vs 61.6 percent). On a monthly basis, producer prices were up 5.2 percent, reversing sharply from a 16.5 percent fall in October.
5 hours ago
Steel Rises to 2-Month HighCommodity
Steel rebar futures were at CNY 3,760 per tonne in mid-December, the highest since mid-October, as eased pandemic-related lockdowns and measures to stimulate China’s vital construction sector offset data pointing to a slowing economy. The country’s top commercial banks have agreed to extend $162 billion in new credit lines for private developers, officials lifted a ban on equity refinancing for listed developers, and the PBoC cut the reserve requirement ratio by 25bps to support lending to the debt-ridden sector. In the meantime, major cities started to ease Covid lockdown rules, raising hopes of further reopening measures to follow. Still, further signs of a slowing economy laid some pressure on steel prices. The NBS PMI pointed to the sharpest contraction in factory activity in seven months in November, while trading activity contracted sharply in the period.
5 hours ago
Hong Kong Equities Finish at More than 4-Month HighHong Kong Stock Market
The Hang Seng surged 450.64 points or 2.32% to close at over four-month peak of 19,900.87 on Friday, building gains from the prior session and posting a 6.6% jump for the week which was the second straight weekly gain, boosted by a rebound in US stocks Thursday ahead of key inflation print later in the day. The producer price index for November is one of the final pieces of data the Federal Reserve will see before its monetary policy meeting next week. Traders shrugged off weak China's factory-gate and consumer prices for November, as they remain optimistic that the worst of Chinese economic woes from COVID is over. All sectors contributed to the rally, with the property index soaring almost 7%, on expectations Beijing may add support for the sector at a key economic meeting next week. China Resources Land climbed 11.1%, followed by Sino Land (4.7%), Sun Hung Kai Properties (4.3%), Swire Properties (4.2%), Tencent Hlds (2%), Meituan (5.7%), and CK Infrastructure Hlds (1.6%).
5 hours ago
European Shares Mostly Higher on FridayGermany Stock Market
European shares traded mostly higher on Friday, as investors across the world await US producer price inflation figures due later in the day, which could shed light on the state of inflation and influence longer-term expectations for interest rates. Meanwhile, traders continued to assess the macroeconomic outlook and the trajectory of monetary policy ahead of key policy meetings next week. The US Fed, European Central Bank and Bank of England will likely deliver fresh rate hikes on Wednesday and Thursday, but by a smaller margin than the months before. On the corporate front, Primark owner Associated British Foods reiterated a November forecast that profit would fall in its 2022-23 financial year, while Manchester United raised its 2023 total revenue guidance on the back of strong matchday revenue and British high-end homebuilder Berkeley Group Holdings retained its annual profit outlook. For the week, European stocks are still on track for their first weekly loss in two months.
5 hours ago
Spain Industrial Output Growth Below ForecastsSpain Industrial Production
Industrial production in Spain rose by 2.5% year-on-year in October of 2022, following a 3.6% increase in the previous month and slightly below market estimates of a 2.8% advance. It marks the weakest growth in industrial activity since April, as production slowed significantly for consumer goods (1.2% vs 2.7% in September) and energy (3.6% vs 8.5%) while it decreased for intermediate goods (-2.9% vs -3.5%). On the other hand, output continued to rise solidly for capital goods (11% vs 12%). On a seasonally adjusted monthly basis, industrial output went down by 0.4%, after a downwardly revised 0.1% fall in the previous month.
5 hours ago
Lithuania Producer Inflation Eases to 8-Month LowLithuania Producer Prices Change
Producer inflation in Lithuania eased to an eight-month low of 23.9 percent year-on-year in November 2022, from a downwardly revised 28.1 percent advance in the previous month, as prices rose at a softer rate for all industries. Costs eased considerably for electricity, gas, steam and air conditioning supply (87.2 percent vs 104.2 percent), followed by manufacturing (19.0 percent vs 22.6 percent), mining and quarrying (23.1 percent vs 24.9 percent) and water supply, sewerage, waste management and remediation activities (5.7 percent vs 7.7 percent). On a monthly basis, producer prices dropped by 1.6 percent, the sharpest fall since April 2020.
5 hours ago
European Markets Head for Higher OpenGermany Stock Market
European equity markets were headed for a higher open on Friday, extending a global stock rally as risk sentiment improved, while investors continued to assess the macroeconomic outlook and the trajectory of monetary policy. Markets are preparing for US producer price data that could shed light on the state of inflation and influence longer-term expectations for interest rates, with the Federal Reserve set to hike rates again next week. Investors are also bracing for a slew of European data due today to gauge the economic health of the region, as well as the European Central Bank and the Bank of England’s monetary decisions next week. DAX and Stoxx 600 futures were up about 0.3% in early trade.
6 hours ago
Norway Inflation Rate Below ForecastsNorway Inflation Rate
Norway’s annual inflation rate eased to 6.5% in November 2022, from October's 35-year top of 7.5%, and below the market forecast of 7%. Cost increased at softer rates for housing & utilities (4.9% vs 7.2%); food & non-alcoholic beverages (12.7% vs 13.1%); transport (9.6% vs 10.8%); furnishings, household equipment & routine maintenance (7.6% vs 8.2%); communications (1.8% vs 2.5%) and recreation & culture (5.6% vs 5.9%). On the other hand, inflation increased for clothing & footwear (2.1% vs 1.6%). Meanwhile, the CPI adjusted for tax changes and excluding energy products, surged 5.7% year-on-year in November 2022. On a monthly basis, consumer prices dropped 0.2%, after a 0.3% rise in October.
6 hours ago
Lithuania Trade Gap Hits Fresh HighLithuania Balance of Trade
Lithuania’s trade deficit surged to a new record peak of EUR 0.85 billion in October 2022 from EUR 0.33 billion in the same period a year earlier, as imports grew faster than exports, amid rising commodity prices. Imports jumped by 42.6% to EUR 5.06 billion, remaining close to its record high, mainly boosted by mineral fuel, mineral oils and their distillation products (260%), vehicles (53.3%), and fertilizer (210%). Meanwhile, exports increased at a slower 30.6% to EUR 4.21 billion, mainly driven by demand of mineral fuel, mineral oils and their distillation products (200%), vehicles (220%). Considering January to October of the year, the trade deficit widened sharply to EUR 6.89 billion from EUR 2.46 billion in the same period of 2021.
6 hours ago
China Stocks Rise Amid Soft Inflation DataChina Stock Market
The Shanghai Composite rose 0.3% to close at 3,207 while the Shenzhen Component gained 0.98% to 11,502 on Friday, as investors digested soft Chinese inflation data which came largely within expectations. Latest data showed that China’s annual consumer prices rose 1.6% in November, the slowest pace in eight months, while producer prices fell 1.3% for the second straight month of contraction. The benchmark indexes also ended the week higher, as China’s loosening Covid restrictions sparked hopes of wider economic reopening that could boost growth. Meanwhile, investors remain cautious about a weakening macroeconomic outlook and uncertainty around monetary policy in major economies. Consumer, healthcare and property stocks led the advance, with strong gains from Wuliangye Yibin (4.9%), Andon Health (10%) and China Vanke (5.6%).
6 hours ago
Danish Current Account Surplus Falls in OctoberDenmark Current Account
Denmark's current account surplus edged down to DKK 33.2 billion in October 2022 in seasonally adjusted terms from a downwardly revised 35.3 billion in the previous month. The services surplus narrowed to DKK 18.4 billion from DKK 21.9 billion in September while the primary income surplus fell to DKK 9.0 billion from DKK 9.9 billion. At the same time, the goods surplus increased to DKK 9.1 billion from DKK 7.1 billion. Meanwhile, the secondary income deficit edged down to DKK 3.2 billion from DKK 3.6 billion in September. From January to October, the current account surplus jumped to DKK 306.9 billion from DKK 183.3 billion in the same period in 2021.
6 hours ago
Danish Posts Smallest Trade Surplus in 4 MonthsDenmark Balance of Trade
Denmark's goods and services trade surplus declined to a seasonally adjusted DKK 27.4 billion in October 2022 from a downwardly revised DKK 29.0 billion in the previous month. It was the smallest trade surplus since June, as exports dropped more than imports. Exports fell 4.9% to DKK 159.2 billion, while imports went down 4.8% to DKK 131.8 billion. For the first ten months of the year, the trade surplus surged to DKK 262.7 billion from DKK 150.9 billion in the same period in 2021.
6 hours ago
China Vehicle Sales Fall 7.9% YoY in NovemberChina Total Vehicle Sales
Auto sales in China dropped by 7.9% yoy to 2.33 million units in November of 2022, reversing from a 6.9% growth a month earlier, data from the China Association of Automobile Manufacturers (CAAM) showed. It was the first decline in car sales since May, as a hoped-for buyers' rush before expiry of the incentives failed to appear. Meanwhile, sales of new energy vehicles, which include pure electric vehicles, plug-in hybrids and hydrogen fuel-cell vehicles, surged 72.3% from the previous year. For the first eleven months of the year, auto sales rose by 3.3% yoy, compared with a 4.5% rise a year earlier. For 2023, the industry will sell 27.6 million cars, up 3% from a year earlier. In July, CAAM slashed its auto growth projection for 2022 to 3% from an earlier estimation of 5.4%, reflecting disruptions in production due to a prolonged global shortage of semiconductors earlier in the year.
7 hours ago
Finnish Industrial Output FallsFinland Industrial Production
Industrial production in Finland declined by 0.6 percent year-on-year in October 2022, reversing from an upwardly revised 4.2 percent rise a month earlier and falling for the first time since March 2021. The output of mining and quarrying slumped (-29.6% vs -9.2% in September), while electricity gas, steam, and air conditioning supply dropped for the first time in seven months (-3.1% vs 11.3%. Meantime, manufacturing growth slowed to a 19-month low(0.6% vs 3.7%).
7 hours ago
The Nikkei 225 Index rose 1.25%Japan Stock Market
In Tokyo the Nikkei 225 Index rose 346 points or 1.25 percent on Friday. Leading the gains are Furukawa Electric (5.35%), Advantest (5.14%) and Tokyo Electric Power (4.91%).
7 hours ago
Estonian Trade Gap Widens in OctoberEstonia Balance of Trade
The trade deficit in Estonia increased to EUR 238 million in October 2022 from EUR 156 million in the same month a year earlier, as exports grew less than imports. Shipments rose 11% yoy to EUR 1,842 million, driven by agricultural products and food preparations, and mechanical appliances. Finland was the main trading partner for Estonia’s exports ((15% of total sales), followed by Latvia (14%) and Sweden (9%). Meantime, imports increased at a faster 15% to EUR 2,080 million, boosted by motor fuels, natural gas, electricity, automobiles, and mechanical appliances. The top partner countries for Estonia’s imports were Finland (16% of total arrivals), Latvia (12%), and Lithuania (11%). Considering the January to October period, the trade shortfall jumped to EUR 2,662 million from EUR 1,421 million in the same period in 2021.
7 hours ago
Dutch Manufacturing Drops 0.4% in OctoberNetherlands Manufacturing Production MoM
The manufacturing production in the Netherlands fell 0.4 percent month-on-month in October of 2022, reversing from an upwardly revised 0.7 percent rise in the previous month. Output contracted for transport (-1.8 percent vs 12.0 percent in September), food industry (-1.5 percent vs 2.1 percent), and metal products (-0.9 percent vs 1.9 percent) while output of chemical products shrank faster (-3.7 percent vs -1.8 percent). By contrast, there were rebounds in the output of both machinery (1.9 percent vs -2.5 percent) and repair and installation (16.3 percent vs -2.1 percent). On a yearly basis, the manufacturing production expanded 3.3 percent, slowing from an upwardly revised 5.2 percent growth in September.
8 hours ago
Aussie Rises as Risk Sentiment ImprovesAustralia Currency
The Australian dollar appreciated to around $0.68, marching toward its strongest levels in three months as an improving risk sentiment weighed on the greenback and lifted risk-sensitive currencies. China’s loosening Covid restrictions also lent optimism to the market, though renewed global recession fears and uncertainty around US Federal Reserve policy tightening kept sentiment in check. Meanwhile, latest data showed that Australia’s economy expanded less than expected in the third quarter as persistent inflation and rising interest rates dampened domestic consumption, while the country’s trade surplus narrowed in October. The Reserve Bank of Australia raised its policy rate by 25 basis points to 3.1% at its December meeting, taking borrowing costs to a level not seen in a decade. The RBA has now lifted the cash rate for the eight consecutive month and said that it expects to tighten further to bring down inflation.
8 hours ago
Sensex Set for Weekly LossIndia Stock Market
The BSE Sensex fell 164.4 points or 0.2% to its lowest in a week of 62,406.3 in morning trade on Friday, swinging from a rise in the prior session while heading for a 0.7% fall weekly after gaining in the previous week, amid growing global recession fears. Meantime, Reuters forecast that India's inflation in November likely slowed to a nine-month low of 6.4% yoy, due to further moderation in food prices, while remaining above the central bank's 2-6% target range. Policymakers signaled at least one more rate hike ahead as high inflation persisted. In China, fresh data showed that the annual inflation eased to an eight-month low last month while producer prices fell further. Among single stocks, HCL Tech plunged 6.3%, after the company said it expects revenue for the full year to be at the lower end of its guidance. Other early losers were Infosys (-2.9%), Tech Mahindra (-2.3%), Adani Total Gas (-1.8%), Reliance Industries (-1.1%), and Axis Bank (-0.7%).
8 hours ago
Malaysia Retail Growth Eases to 6-Month LowMalaysia Retail Sales YoY
Retail trade in Malaysia slowed to 26.0 percent year-on-year in October 2022, from 30.0 percent in the previous month. It was the slowest expansion in retail activity since April, as sales slowed down in non-specialized stores (25.7% vs 31.9%); specialized stores (40.9% vs 43.4%); and other household equipment (19.1% vs 23.1%). At the same time, sales of motor vehicles declined faster (-5.7% vs 40.4%). Meanwhile, wholesale trade rose by 7.3 percent in October, easing from a 13.3 percent growth in September. On a monthly basis, retail trade increased by 1.1 percent in October, slowing from a 1.2 percent rise a month earlier.
9 hours ago
Malaysia Jobless Rate Down to 3.6% in OctoberMalaysia Unemployment Rate
The unemployment rate in Malaysia declined to 3.6 percent in October 2022 from 4.3 percent in the same month a year earlier, pointing to the lowest reading since February 2020. The number of unemployed dropped 14.20 percent from a year earlier to 605.0 thousand, while employment increased 3.4 percent to 16.08 million. Meantime, the labor force gained 2.58 percent to 16.68 million. In September 2022, the jobless rate was at 3.6 percent.
9 hours ago
Gold Climbs on Dollar WeaknessCommodity
Gold rose above $1,790 an ounce on Friday, benefiting mainly from the dollar’s weakness as investors cautiously awaited key US inflation data and the Federal Reserve’s policy decision next week. The US producer price data due for release later today and the consumer price data scheduled for next week could shed light on the state of inflation and influence longer-term expectations for monetary policy. The Fed is expected to deliver a more moderate 50 basis point rate hike next week after raising rates by a hefty 75 basis points in the past four meetings, and traders will be watching for signs on whether the central bank is getting ready to pause or continue tightening. Gold is highly sensitive to the rates outlook as higher interest rates raise the opportunity cost of holding non-yielding bullion and dent its appeal, and vice versa.
10 hours ago
South Korea 10Y Bond Yield Hits 15-week LowSouth Korea Government Bond Korea
South Korea 10 Year Government Bond Yeld decreased to a 15-week low of 3.488%
10 hours ago
Indonesia Retail Sales Growth Slows to 5-Month LowIndonesia Retail Sales YoY
Retail sales in Indonesia rose by 3.7 percent year-on-year in October 2022, after a 4.6 percent gain a month earlier. This was the softest increase in retail trade since May, amid the impact of a steep fuel price hike. Sales growth slows for fuels (0.5% vs 8.0% in September), cultural & recreational goods (3.7% vs 7.1%), and clothing (25.3% vs 34.6%). In addition, sales fell faster for both home appliances (-14.8% vs -6.8%) and automotive parts & accessories (-5.2% vs -0.1%), while sales of information & communication continued to drop (-20.7% vs -22.1%).
10 hours ago
Asian Stocks AdvanceChina Stock Market
Asian equity markets rose on Friday, tracking gains on Wall Street overnight as investors continued to assess the outlook for growth and the trajectory of monetary policy. Markets are bracing for US producer and consumer price data that could shed light on the state of inflation and influence longer-term expectations for monetary policy, ahead of the US Federal Reserve’s policy meeting next week. Investors also digested data showing China’s annual consumer prices rose 1.6% in November, the slowest pace in eight months, while producer prices fell 1.3% for the second straight month of contraction. Shares in Australia, South Korea, Japan, Hong Kong and mainland China all advanced.
10 hours ago
"""
articles, headlines =  new_magic(news_string)


news_cache = {"12/09/2022":{"headlines":headlines,"articles":articles}}