dec_4_2022 = """
Gold Hits 5-Month HighsCommodity
Gold edged above $1,800 an ounce on Monday, hitting its highest levels in five months as the dollar continued to decline, making greenback-priced bullion more attractive for buyers holding other currencies. The metal came under pressure on Friday on hotter-than-expected US jobs data, but has since reversed those losses as expectations that the US Federal Reserve will slow the pace of interest rate hikes starting this month remained intact, with Fed Chair Jerome Powell expressing support for such a move. China’s continuing shift away from strict Covid restrictions also boosted risk sentiment and weighed on the dollar. Investors now look ahead to a slew of US economic reports such as services activity, consumer sentiment and inflation data, as well as the Fed’s monetary decision next week.
1 day ago
Dollar Extends Fall as Sentiment ImprovesUnited States Currency
The dollar index fell toward 104 on Monday, sliding for the fourth straight session as China’s policy shift on its Covid response boosted risk assets at the expense of the greenback. Investors also shook off a stronger-than-anticipated US jobs report as expectations that the Federal Reserve will slow the pace of interest rate hikes starting this month remained intact, with Fed Chair Jerome Powell expressing support for such a move. The US economy added 263K jobs in November, higher than market forecasts for a 200K increase and following an upwardly revised 284K additions in October. Investors now look ahead to more US economic reports this week including services activity, consumer sentiment and producer inflation data, as well as consumer inflation data next week. The Fed is also scheduled to meet next week, where it is expected to deliver a smaller 50 basis point rate hike after raising interest rates by 75 basis points in the past four meetings.
1 day ago
China Stocks Rise on Easing Covid CurbsChina Stock Market
The Shanghai Composite rose 1.1% to around 3,190 while the Shenzhen Component gained 1% to 11,332 on Monday, with mainland stocks marching toward multi-month highs as China continued to shift away from strict Covid restrictions, sparking hopes of further economic reopening. In the latest developments, the major Chinese cities of Shanghai and Hangzhou scrapped testing requirements to enter public venues or use public transportation, joining other metropolises in relaxing virus curbs that have weighed on the economy and caused public outcry. Investors also reacted to data showing November services activity in China contracted the most in six months. Nearly all sectors advanced, with notable gains from index heavyweights such as Shijiazhuang Yilin (3.4%), East Money Information (5%), Kweichow Moutai (2.5%), China United Network (7%) and Ping An Insurance (4.3%).
1 day ago
Asian Stocks Mostly AdvanceChina Stock Market
Asian equity markets mostly rose on Monday, with Hong Kong and mainland China stocks leading the advance as investors cheered easing Covid restrictions in China that sparked hopes of further reopening. Investors also digested a stronger-than-expected US jobs report released on Friday, though expectations that the Federal Reserve will slow the pace of interest rate hikes this month remained intact. Meanwhile, markets reacted to a raft of economic reports in Asia, headlined by services activity data in China that contracted the most in six months. Shares in Australia also gained, while South Korean and Japanese shares wobbled.
1 day ago
China Services Sector Shrinks the Most in 6 MonthsChina Services PMI
The Caixin China General Services PMI fell to 46.7 in November 2022 from 48.4 in October, pointing to the 3rd straight month of drop. This was also the steepest contraction in the service sector since May, amid anti-COVID containment measures that weighed on demand and operations. New orders fell the most in six months, employment shrank at the steepest rate since the survey began in November 2005, while backlogs rose at the fastest rate in six months. Meantime, export orders returned to growth as overseas demand picked up following an easing of international travel rules. On prices, input cost inflation eased for the third month in a row, and was among the weakest in over two years. Also, firms registered a slower rise in prices charged, with some of them citing efforts to boost sales. Finally, sentiment hit an eight-month low, significantly below its long-term average, amid concerns over how long it will take to contain the virus and the impact of curbs on their businesses.
1 day ago
China Composite PMI Drops to 6-Month LowChina Composite PMI
The Caixin China General Composite PMI fell to 47.0 in November 2022 from 48.53in October, pointing to the lowest print since May as the Chinese economy was currently bracing for the third wave of COVID infections. The decline was broad-based, with factory activity shrinking for the fourth month in a row and the services sector contracting the most in six months. New orders declined at a stronger pace, though mild overall, which was driven by a steeper fall in sales across the service sector. Meantime, after rising slightly in October, employment fell and at the fastest rate since February 2020. Cost pressures remained relatively subdued, with average input costs rising modestly. Prices charged were broadly stable for the second month in a row. "The market is in urgent need of policies to promote employment and stabilize domestic demand," said Dr. Wang Zhe, senior economist at Caixin Insight Group.
1 day ago
Japanese Shares Mixed in Cautious TradeJapan Stock Market
The Nikkei 225 Index rose 0.1% to around 27,810 while the broader Topix Index fell 0.1% to 1,952 in mixed trade on Monday, with investors turning cautious as the market entered a quiet period ahead of the US Federal Reserve’s December policy meeting. Investors also digested a stronger-than-expected US jobs report released on Friday, though expectations that the Fed will slow the pace of interest rate hikes remained intact. Domestically, a top Japanese official said on Sunday that Japan should put off raising capital gains tax to avoid sending the wrong message as the country aims to encourage financial investment. Notable gains were seen from select index heavyweights on Monday such as Fast Retailing (2.8%), Eisai Co (2.3%) and Nippon Steel (2%), while losses were seen from Nippon Yusen (-1.6%), Toyota Motor (-1.2%) and Sumitomo Mitsui (-1.3%).
1 day ago
Japan Composite PMI Lowest in 9 MonthsJapan Composite PMI
The au Jibun Bank Japan Composite PMI stood at 48.9 in November 2022, unchanged from the flash reading but was down from a final 51.8 in the prior month. This was the first contraction in private sector activity since August and the steepest pace since February, due to sharp drops in output and new orders at manufacturing firms as inflationary pressures persisted. In contrast, the services sector posted a third month where business activity improved. Jobs in the private sector expanded mildly, while backlogged work declined for the first time in seven months. On inflation, cost burdens increased at a marked pace, but one which was the slowest in eight months. Meanwhile, in a bid to protect profit margins from cost increases, private sector firms went up selling prices at a rate that was among the sharpest on record.
1 day ago
Irish Services Growth Slows in NovemberIreland Services PMI
The AIB Ireland Services PMI dropped to 50.8 in November 2022 from 53.2 in the previous month. It was the 21st month of successive expansion in the sector, but the weakest growth in the current sequence and below the 22-year long-run trend level of 55.1 for the fourth straight month, due to economic uncertainty and high inflation. New business growth eased to a 21-month low, with both business services and transport, tourism, and leisure posting outright contractions in new work. The rate of growth in new export business also slowed sharply. This saw a marked easing of capacity pressures, with backlogs of outstanding business rising at the slowest pace in 21 months. Meanwhile, the rate of job creation eased to the weakest in 2022 so far. On the pricing front, input cost inflation accelerated slightly, while output cost inflation slowed to a three-month low. Finally, business sentiment weakened, amid recession fears, the energy crisis and rising living costs.
1 day ago
Hong Kong Private Sector PMI Down to 8-Month LowHong Kong Manufacturing PMI
The S&P Global Hong Kong PMI fell to 48.7 in November 2022 from 49.3 in October, pointing to the lowest print since March. The latest result also marked the third straight month of contraction in private sector activity amid rising COVID cases and a worsening economic backdrop, with both output and new orders shrinking at faster rates. Firms also reduced their workforce levels; while backlogged work slipped the most in eight months, reflecting a drop in demand and work cancellations. Meantime, export sales declined the least in six months, while buying activity grew modestly. Vendor performance improved as lead times shortened for the first time since April 2021. On the pricing front, input prices went up the most in eight months, on higher purchase cost and wage inflation. As a result, selling prices continued to rise but the rate of increase softened. Finally, sentiment was upbeat for the first time in four months, linked to easing pandemic curbs and hopes for improved sales.
1 day ago
Singapore Private Sector Growth Eases in NovemberSingapore Composite PMI
The S&P Global Singapore PMI declined to 56.2 in November 2022 from October's of 57.7. This was the third straight month of expansion in the sector but the softest pace in the sequence, due to a slowdown in demand expansion amid COVID-19 disruptions.
1 day ago
US Futures Ease as Traders Await More DataUnited States Stock Market
US stock futures eased on Monday as the market entered a quiet period ahead of the Federal Reserve’s December policy meeting, while awaiting more US data to gauge the health of the economy. Futures contracts tied to the three major indexes all fell about 0.1%. In regular trading on Friday, the Dow rose 0.1%, while the S&P 500 and Nasdaq Composite shed 0.12% and 0.18%, respectively, closing little changed after recouping most of the earlier losses triggered by a stronger-than-expected November jobs report. Meanwhile, expectations that the Fed will slow the pace of interest rate hikes starting this month remained intact, with Fed Chair Jerome Powell expressing support for such a move. Investors now look ahead to more US economic reports this week including services activity, consumer sentiment and producer inflation data.
1 day ago
Australia Q3 Corporate Profits Unexpectedly FallAustralia Corporate Profits
Corporate profits in Australia unexpectedly plunged by 12.4% qoq on in Q3 of 2022, missing market expectations of a 0.3% growth, and following an upwardly revised 7.8% rise in Q2. This was the first decline in corporate profits since the fourth quarter of 2020. Through the year to Q3, corporate profits rose by 8.5 percent, easing sharply from an upwardly revised 28.8 percent surge in Q1.
1 day ago
Japan Services PMI Revised HigherJapan Services PMI
The au Jibun Bank Japan Services PMI was revised higher to 50.3 in November of 2022, compared to preliminary estimates of 50.0, and following a final 53.2 in the prior month, signalling a third consecutive expansion in the sector r but one which was only marginal and the weakest in the current positive sequence.
1 day ago
Australia MI Monthly Inflation Gauge at 4-Month HighAustralia MI Inflation Gauge MoM
The Melbourne Institute’s Monthly Inflation Gauge showed prices rose to a four-month high of 1.0% in November 2022, accelerating from a 0.4% rise in the previous month and marking the third straight month of increase. The latest result came ahead of the Reserve Bank's monetary policy meeting for the final time this year. The board is expected to lift key interest rates by another 25bps to 3.1%, the highest level since June 2012, amid continued efforts to contain high prices.
1 day ago
Oil Rises as OPEC+ Stands Pat, China Curbs EaseCommodity
WTI crude futures edged above $81 per barrel on Monday after OPEC+ decided to maintain production at current levels as more Western sanctions on Russian oil are set to kick in, while easing Covid curbs in China buoyed the demand outlook. OPEC+ decided to stick to their existing policy of reducing oil output by 2 million barrels a day from November through 2023, as the group took stock of market developments. The European Union is set to ban most seaborne Russian oil imports from Monday, while the G7 agreed to impose a cap of $60 per barrel on Russian crude. Deputy Prime Minister Alexander Novak condemned the cap and said that Russia was willing to cut output if needed. On the demand side, more Chinese cities including Shanghai and Hangzhou have dialed back Covid restrictions over the weekend, raising hopes that authorities are directing the country toward economic reopening that could boost energy demand.
1 day ago
Australian Shares Rise as Miners GainAustralia Stock Market
The S&P/ASX 200 Index rose 0.3% to around 7,320 on Monday, recouping some losses from the previous session, helped by gains in mining stocks amid firmer iron ore prices. Investors also shook off a stronger-than-expected US jobs report released on Friday as expectations that the US Federal Reserve will slow the pace of interest rate hikes remained intact. Moreover, the Reserve Bank of Australia is set to decide on monetary policy this week, where it is expected to deliver another modest 25 basis point rate increase as domestic inflation trended lower. Gains in the mining sector were led by BHP Group (1.8%), Fortescue Metals (1.9%) and Rio Tinto (0.8%). Financial firms also advanced, with the “Big Four” banks all trading in positive territory.
1 day ago
Australia Composite PMI Lowest since January: S&P GlobalAustralia Composite PMI
The S&P Global Australia Composite PMI was revised slightly higher to 48 in November of 2022 from a preliminary of 47.7, but continued to point to the second month of contraction in private sector activity, and the biggest since January. The services sector was the main drag, also falling at the sharpest pace since January (47.6) while manufacturing growth slowed (51.3). Deterioration of economic conditions, flooding issues and a higher interest rate environment led to falling demand for Australian services while incoming new orders for manufactured goods slowed. Firms nevertheless hired at a solid pace across the private sector. In terms of prices, inflationary pressures intensified on the back of higher wages, input and energy costs, which firms continued to pass on to clients. Business confidence dimmed as firms grew less optimistic with regards to the year ahead outlook in light of the challenging current economic backdrop.
1 day ago
Australia Services PMI Revised Higher but Still Points to Falling ActivityAustralia Services Sentiment
The S&P Global Australia Services PMI was revised slightly higher to 47.6 in November of 2022 from a preliminary of 47.2, but continued to point to the biggest decline in services sector activity since January. Demand for Australian services fell at the sharpest pace in over a year, due to a weaker economic backdrop, flooding issues and as a result of rising interest rates. Foreign demand performed no better, similarly declining for a second straight month. Capacity issues also weighed on activity as labour shortages continued to be reported, despite firms hiring at an above-average pace as they sought to re-establish pre-pandemic workforce levels. Moreover, vendor performance also deteriorated amid supply chain issues, input and manpower constraints. Also, input prices rose at the fastest pace in three months as steeper wages and fuel while selling prices rose at a softer pace. Finally, business confidence eased to the third lowest on record.
1 day ago
Week AheadUnited States GDP
In the US, the spotlight will be taken by ISM Non-Manufacturing PMI, the University of Michigan's consumer sentiment, and PPI data. Investors will also follow interest rate decisions in Australia, Canada, Brazil, and India and inflation rates from China, Brazil, Turkey, Russia, Philippines, Netherlands, and Mexico. Finally, German factory orders and trade data from China, Canada, and the US should provide some insides into the state of global demand.
1 day ago
"""

dec_5_2022 = """
Canada Building Permits Unexpectedly Fall for 2nd MonthCanada Building Permits
The total value of building permits in Canada decreased by 1.4% over the month to CAD 10 billion in October of 2022, following an upwardly revised 18.5% surge in the prior month, against market expectations of a 3.9% rise. Losses in the residential sector more than offset gains from the non-residential sector.
0 days ago
Brazil Business Activity Contracts for First Time Since May 2021Brazil Composite PMI
The S&P Global Brazil Composite PMI fell to 49.8 in November of 2022 from 53.4 in the previous month. It was the first contraction in business activity since May 2021, with manufacturing production and new orders falling the most since May 2020. The services sector remained somewhat resilient, with sales growth fairly sustained. Meanwhile, the pace of job creation was broadly stagnant in November, as a fall in the manufacturing sector was offset by an increase in services. On the price front, input costs rose at the quickest rate in three months due to soaring inflation among service providers. Output charges, however, increased at a softer pace, mainly due to discounts in manufacturing.
0 days ago
Brazil Services PMI Falls to 18-Month LowBrazil Services PMI
The S&P Global Brazil Services PMI fell to 51.6 from 54 in the prior month. It was the slowest pace of growth in 18 months, pressured by heightened market uncertainty. Both new orders and business activity expanded at the lowest rate in one year and a half, with firms able to secure new clients as political and economic turmoil curbed demand. Employment also rose at the slowest pace since June 2021 as increased hiring to keep up with the slight upturn in new business and replace voluntary leavers offset the reduced headcount to lower expenses. On the price front, companies surveyed said a weaker real and higher labor and transportation costs drove input prices to accelerate and halt a period of slowing inflation. In turn, prices charged continued to rise as well. Looking forward, hopes of contained inflation, looser monetary policy, and stronger marketing efforts supported business confidence to remain optimistic.
0 days ago
Italian Bond Yields Hover at 3-Month LowItaly Government Bond 10Y
The yield on the Italian 10-year BTP fell under 3.7% in December, hovering at levels last seen in August and tracking the broad retreat for bond yields in the Eurozone as investors assessed the outlook of monetary policy in the currency bloc. ECB policymakers have expressed the suitability of a 50bps rate hike for the central bank’s next policy decision, slowing from the two consecutive 75bps increases prior, stating that it would be appropriate to make hikes more flexible at a slower pace. Domestic inflation remained at a 37-year high of 11.8% in November, while Eurozone figures slowed more than expected to 10% from last month’s all-time high of 10.6%. At the same time, investors continued to assess expectations that the ECB will outline plans to reduce its balance sheet and not reinvest bonds. The spread between the 10-year BTP and the Bund remained at 190bps, well above the 6-month low of 175bps touched on Dec 1st and pointing to higher perceived credit risk for Italian debt.
0 days ago
Wall Street Set to Open LowerUnited States Stock Market
Stock futures contracts tied to the three major indices were down roughly 0.5% on Monday, putting Wall Street on track to start the week on a sour note as investors await a slew of economic data to gauge the economy's health and the Fed's next move. Last week wrapped up with a stronger-than-expected payroll report, which has thrown some cold water into expectations for a less aggressive tightening despite markets still seeing an 80% chance that the US central bank will hike rates by 50 basis points in December. Now, all eyes are on a report from the ISM that is expected to show that the services sector grew slower in November as tighter financial conditions dented business activity. Meanwhile, Tesla dropped more than 4% after warning about a cut in the December output of the Model Y at its Shanghai plant. On the flip side, US-listed Chinese companies, including Alibaba Group and JD.com, enjoyed some respite of hopes for a swifter reopening of China's economy.
0 days ago
Mexico Consumer Confidence Improves in NovemberMexico Consumer Confidence
The consumer confidence indicator in Mexico rose to 41.7 in November of 2022 from a revised 41.1 in the previous month. Expectations improved for the current assessment of households' financial situation (46.9 vs. 46.5 in October) and Mexico's macroeconomic situation (37.9 vs. 36.5) as well as the country's macroeconomic situation in 12 months (44.9 vs. 44.4). At the same time, respondents expressed they were slightly more likely to purchase durable goods (23.6 vs. 23.5). However, sentiment deteriorated regarding households' financial situation in 12 months (54.3 vs. 54.4)
0 days ago
Indian 10-Year Bond Yield Rebounds from 2-Month LowIndia Government Bond 10Y
The yield on the Indian 10-year government bond was above 7.25%, rebounding from the over two-month low of 7.2% touched on December 1st as oil prices consolidated and risked higher inflation for the import-dependent economy, increasing the likelihood of higher interest rates. The RBI is expected to raise its key rate by 25bps to 50bps this week, adding to the 190bps in hikes since May as inflation has remained above the central bank’s upper target of 6% for 10 straight months. Recent data showed that the Indian economy expanded by 6.3% year-on-year in the third quarter, slightly above market forecasts of 6.2% and raising expectations that the RBI could opt for a sharper rate hike. Still, the rebound in yields was capped by reports that spending by the central government should be less than the amount budgeted this financial year for the first time since 2019/20, underscoring the government’s aim to rein in fiscal deficit and reducing credit risk for Indian debt.
0 days ago
Zambia Private Sector Shrinks for 2nd MonthZambia Composite PMI
The Stanbic Bank Zambia PMI was at 49.1 in November of 2022, broadly in line with October's reading of 49.0 and signalling a modest deterioration in operating conditions in the Zambian private sector for the second month running. Both output and new orders decreased for the second straight month, mainly impacted by money shortages in the economy. In turn, firms reduced their purchasing activity and employment. Meanwhile, backlogs of work were unchanged following a fall in October. On the price front, there remained a lack of inflationary pressure with both input costs and output prices ticking down. Looking forward, firms remained optimistic regarding the year-ahead outlook for output, although sentiment dipped to a four-month low and was weaker than the series average.
0 days ago
South Korean Won Hovers Near Five-Month PeakSouth Korea Currency
The South Korean won was changing hands below $1,300, closing in on its lowest level since July, as prospects of further government intervention brought relief to markets. South Korean President Yoon Suk-yeol has recently pledged to direct resources toward increasing exports, stating in a speech that exports are a vital driver for economic growth and employment. South Korea's central bank also announced some supportive measures in October to improve banking system liquidity and mitigate the fallout from the Gangwon Jungdo Development default. Meanwhile, the Bank of Korea delivered a smaller 25 basis point rate hike in a widely expected move at its November meeting. That was the ninth rate increase since the central bank started tightening policy in August 2021, bringing the key rate to the highest since June 2012.
0 days ago
Colombia November Inflation Rate Hits New 2-Decade HighColombia Inflation Rate
The annual inflation rate in Colombia accelerated for the sixth straight month to 12.53% in November of 2022, the highest since March of 1999, from 12.22% in the prior month. The reading came above market expectations of 12.37%, with a weaker currency weighing on the prices of products and services. The CPI components that pushed up inflation the most were food and beverages (27.08% vs 27.02% in October); furnishings & household equipment (17.33% vs 16.74%); restaurants & hotels (16.84% vs 16.55%); miscellaneous goods & services (12.20% vs 11.48%); transportation (11.19% vs 10.23%) and clothing & footwear (10.11% vs 9.07%). Meanwhile, prices slowed down a bit for housing & utilities (6.86% vs 7.04%). On a monthly basis, consumer prices increased by 0.77%, up from a 0.72% rise in October and above market estimates of a 0.63% increase.
0 days ago
Kazakhstan Raises Base Rate to 16.75%Kazakhstan Interest Rate
The National Bank of Kazakhstan raised its benchmark interest rate by 75 bps to 16.75% on December 5th of 2022, citing spiraling inflation, high food prices and geopolitical uncertainty. The central bank said that approached the end of the rate-raising cycle and stated keeping the base rate at its current value for a long period of time will help to stabilise inflation and gradually reduce it in the medium term.
0 days ago
Indian Rupee Retreats Sharply Ahead of RBI DecisionIndia Currency
The Indian rupee weakened past 81.8 per USD from the two-week high of 81.1 touched on December 1st, pressured by heavy selling activity amid the rebound in crude oil prices and comparatively slow tightening by the Reserve Bank of India. Markets expect the RBI to raise its key rate by at least 25bps in its decision this week, adding to the 180bps in hikes since the start of the cycle in May but easing the tightening pace from the three consecutive 50bps hikes. Policymakers have stated that there are signs that inflation is slowing, but global headwinds and uncertainty regarding oil prices could leave price growth stubbornly high. Trade imbalances and relatively slow tightening by the RBI when compared to its US counterpart drove the rupee to depreciate nearly 9% year-to-date.
0 days ago
Latvia Industrial Output Shrinks for 4th MonthLatvia Industrial Production
Industrial production in Latvia fell 2.7 percent year-on-year in October of 2022, following an upwardly revised 3.8 percent decline in the previous month. It was the fourth consecutive month of falling industrial activity, as output continued to decrease for manufacturing (-1.4 percent vs -1.7 percent in September) and electricity and gas supply (-18 percent vs -26 percent). Meanwhile, production slowed for mining & quarrying (2.7 percent vs 6.6 percent). On a seasonally adjusted monthly basis, industrial activity showed no growth, after a 0.9 percent fall in September.
0 days ago
French 10-Year Bond Yield Holds Near 2-1/2-Month LowFrance Government Bond 10Y
The yield on the French 10-year OAT hovered at 2.3%, close to its lowest level since mid-September, tracking a similar trend in other Eurozone government bond yields as investors continued to assess the outlook for monetary tightening in the region amid continued signs of a slowing economy. Consumer and producer prices across the currency bloc eased, though in France the annual inflation remained steady at a record high. Meanwhile, Bank of France Governor Francois Villeroy de Galhau and Bundesbank President Joachim Nagel reiterated their commitment to bring inflation back to 2% by the end of 2024 or 2025. Elsewhere, final estimates showed the French economy slowed in Q3 while PMI data indicated manufacturing has been shrinking since September and the services sector slipped into contraction in November.
0 days ago
Lebanese Private Sector Contracts the Most in 7 MonthsLebanon Manufacturing PMI
The BLOM Lebanon PMI slightly fell to a seven-month low of 48.1 in November of 2022, down from 49.1 in October. The latest reading pointed to the third consecutive month of deterioration in private sector operating conditions in Lebanon and at the fastest pace since April. Output, new orders and exports decreased significantly, linked to weak client purchasing power. At teh same time, both purchasing activity and staff numbers were reduced. The business outlook also remained pessimistic due to uncertainty surrounding the domestic political and economic climate. On the price front, cost pressures eased, leading to a slower rate of increase in selling charges.
0 days ago
Dollar Remains SubduedUnited States Currency
The dollar index consolidated slightly below the 105 mark, hovering at the lowest since late June, and erasing more than half of this year’s gains as prospects of a less aggressive tightening from the Federal Reserve spooked investors away from the greenback. The pledge by Fed Chair Powell to scale down the pace of rate increases has somewhat overshadowed last week's stronger-than-anticipated US jobs report. Money markets are pricing an 80% chance that the US central bank will hike rates by 50 basis points in December after delivering four successive 75 basis point rate increases. Still, investors see a loftier chance that the peak for the Fed funds will be higher than expected. The dollar was mostly steady against the euro and the British pound but it came under pressure against the Chinese yuan as bets of a swifter reopening of China's economy lent optimism to yuan bulls.
0 days ago
UK 10-Year Bond Yield Holds at 3.1%United Kingdom Government Bond 10Y
The yield on the UK’s 10-year Gilt stood at 3.1%, remaining close to its lowest level since early September, on hopes that the Bank of England might not end up hiking as aggressively as feared and as the UK's budget announced last month helped calm the markets following the turmoil triggered by Liz Truss's mini-budget. Board member Dhingra warned that higher interest rates could lead to a deeper and longer recession, and said that there were few signs that demands for higher wages risked a wage-price spiral. Dhingra's dovish stunt came as no surprise to investors after she voted for a 50 bps rate increase last month, while most of her colleagues backed a 75 bp hike. Meanwhile, Deputy Governor Ramsden said last month he was backing more interest rate hikes, but would consider cutting rates if the economy developed differently to his expectation, while Tenreyro said she saw rates on hold next year and then falling in 2024. Markets are betting on a 50 to 75 bps hike at the Dec meeting.
0 days ago
French Stocks Edges Lower on MondayFrance Stock Market
The CAC 40 index was trading lower around the 6,720 level on Monday, tracking a general cautious mood in Europe, as investors weigh weak economic data, recession fears and prospects of further monetary policy tightening. Fresh PMI data showed economic activity in major Euro Area economies shrank in November. At the same time, signs of some easing covid curbs in China prevented further losses. On the corporate front, Bouygues was the top loser, down 3.5%. Orange (-2.9%) and Michelin (-1.3%) were also among the worst performers. By contrast, ArcelorMittal (+2.1%) and Saint-Gobain (+1.1%) advanced the most, followed by Safran (+0.7%)
0 days ago
Qatar Business Activity Remains SubduedQatar Manufacturing PMI
Qatar Financial Centre PMI rose slightly to 48.8 in November 2022 from 48.4 in October. The latest reading pointed to subdued business activity, although some signs of recovery emerged as the FIFA World Cup Qatar 2022TM kicked off in the second half of the month. Wholesale, retail, and service providers experienced rapid activity growth, while sales prices rose to an all-time high amid increasing tourism demand from the tournament. Finally, firms were more optimistic about the one-year outlook than they had been since October 2020 on growing speculation about post-tournament business opportunities.
0 days ago
German 10-Year Bond Yield Stabilizes Around 1.8%Germany Government Bond 10Y
Germany's 10-year bund yield steadied slightly above the 1.8% mark, remaining close to a near three-month low of 1.76% hit last week, on hopes that major central banks will start slowing the pace of interest rate hikes this month amid easing inflation pressures and as Europe's economy heads into recession. European Central Bank official Villeroy de Galhau said on Sunday that the central bank should raise interest rates by 50 bps on December 15th after back-to-back 75 bp hikes in the previous months. In addition, Villeroy de Galhau and policymaker Joachim Nagel said in a joint interview that the ECB was determined to "bring inflation back to 2% by the end of 2024 or 2025." Germany's yield curve remained close to its deepest inversion since 1992, suggesting that investors expect the ECB to pause its rate hikes or even cut them next year to support the bloc's economy. Elsewhere, the US Fed is also expected to slow its aggressive interest-rate hikes soon despite Friday's strong jobs data.
0 days ago
Sensex Closes Below FlatlineIndia Stock Market
The BSE Sensex closed marginally below the flatline at 62,835 on Monday, holding losses from the prior session after touching a record-high last week as losses for auto manufacturers and tech companies outweighed gains for metallurgists and banks. Policy-sensitive auto and tech stocks trailed after eased Covid lockdowns in China supported higher crude oil prices, lifting the risk of higher inflation in India. Tata Motors and Tech Mahindra both dropped more than 1.3%. On the other hand, signs of stronger demand for industrial activity supported commodity-backed stocks, with Tata Steel and Coal India jumping 3% and 2%, respectively. In the meantime, investors awaited the RBI’s monetary decision on Wednesday, with markets expecting an interest rate hike between 25bps and 50bps.
0 days ago
Swedish Service Sector Growth Lowest in Over 2 YearsSweden Services PMI
The Services PMI in Sweden fell to 54.3 in November 2022, the lowest reading since June 2020 and slipping from a downwardly revised 56.6 in the previous month. The downturn was considerably due to declines from business volume and delivery times, pulling the index down by a combined 2.4 points, along with order intake which weighed by 0.6 points. Meanwhile, the employment index added 0.7 points, as the labor market continued to strengthen in the services sector. On the price front, the input price index dropped to 71.1 from 80.4 in October, but remained high compared to its historical average of 57.9. The PMI analyst at Swedbank noted that the economy continued to move downward but remained in the growth zone supported by strong employment, with an increased risk of setbacks further down the line as companies lowered production and the slowdown in order intakes.
0 days ago
Gasoline Futures Trade HigherCommodity
Gasoline futures traded above $2.3 per gallon, up from a 9-week low of $2.22 reached on November 28, and tracking gains in other energy markets as investors continued to weight demand-supply balances. OPEC+ hold production steady at a meeting on December 4th, despite some rumors for another cut, as EU sanctions on crude exports from Russia and China’s covid rules brought volatility to the market. Still, gasoline prices are more than 40% below their June peak of $4.1 due to softer demand and rising domestic output. The latest EIA data showed that the US stockpiles increased by 2769 thousand barrels in the week ending November 25th, the third straight week of gains. Meanwhile, US companies rose output by 4-5% from last year, and the Energy Department projects a similar rate of increase in 2023.
0 days ago
Slovenia Trade Deficit Widens in OctoberSlovenia Balance of Trade
Slovenia trade deficit increased to EUR 483.4 million in October 2022, from EUR 441.9 million in the same month a year earlier. Exports jumped 22 percent to EUR 4,355.9 million, boosted by sales to non-EU countries (34.7 percent) and the EU (16.2 percent). In the meantime, imports went up by 20.6 percent to EUR 4,839.4 million, driven by increased purchases from non-EU countries (22.9 percent) and from the EU (19.2 percent). Considering the first ten months of 2022, the country posted a trade deficit of EUR 3,255.2 million.
0 days ago
UK Natural Gas Futures Rise on MondayCommodity
UK natural gas futures rose toward 350 pence a therm, following an over 16% gain in the previous week, as colder weather and low wind conditions have increased demand. National Grid data showed gas generated 36.8% of British electricity on Saturday, more than wind 32.6%. Still, gas storage facilities in the UK remain 100% full as of December 3rd, higher than the EU average of 91.56%. Europe and the UK imported a record high of 11.14mm tonnes of LNG in November, and are on course to receive 12.2mn tonnes in December. Meanwhile, gas flows on the Yamal-Europe pipeline to Poland from Germany fell to zero while flows via Ukraine continued despite the EU’s bar on seaborne Russian oil imports and an oil price cap on Russian oil coming into effect.
0 days ago
Italian Stocks Trade FlatItaly Stock Market
The FTSE MIB index hovered around the flatline at the 24,620 mark on Monday, holding losses from the prior week as investors monitored commodity prices following the start of the EU’s oil embargo and the decision regarding the price cap on Russian oil. The EU agreed to place a price ceiling of $60/barrel for the use of European tankers and insurance services, below current market prices according to the Urals oil benchmark. Energy shares in Milan were among the top gainers, with Saipem and Tenaris adding 3% and 1%, respectively. Luxury brands also traded in the green, supported by eased Covid restrictions in China with Moncler jumping 0.6%. On the other hand, policy-sensitive tech and auto stocks dragged further after Friday's stronger-than-expected US jobs report, led by a 1% drop for Nexi and Pirelli.
0 days ago
European Shares Little-Changed on MondayGermany Stock Market
European stock indexes swung between small gains and losses on Monday, starting the first full week of December in cautious mood, as investors digested key PMI surveys and European retail sales data. Eurozone business activity declined for a fifth month in November, suggesting the economy was sliding into a mild recession, while retail sales in October came in weaker-than-expected. Elsewhere, the market entered a quiet period ahead of the Federal Reserve’s December policy meeting next week, amid expectations that US policymakers will slow the pace of interest rate hikes despite the hotter-than-anticipated US jobs report. On a brighter note, news that more Chinese cities announced an easing of coronavirus curbs provided some support to China-exposed stocks like miners. On the corporate front, online German broker Flatex cut its guidance, while Vodafone's CEO Nick Read stepped down and will be replaced by finance chief Margherita Della Valle.
0 days ago
Armenia Inflation Rate at 7-Month LowArmenia Inflation Rate
Armenia’s annual inflation rate slowed to 8.8% in November of 2022, the lowest reading since April of 2022, and from 9.5% in the previous month. Costs rose at softer pace for food & non-alcoholic beverages (11.1% vs 12.5%), clothing & footwear (7.5% vs 8.7%), and recreation & culture (10.6% vs 14.1%). Meanwhile, housing & utilities inflation accelerated (8% vs 7.8%). On a monthly basis, consumer prices increased 1.1%, from 0.3% growth in the previous month. Considering January to November, consumer prices rose 8.7% compared to the same period a year earlier.
0 days ago
Eurozone Retail Sales Fall the Most in 10 MonthsEuro Area Retail Sales MoM
Eurozone retail sales dropped by 1.8 percent from a month earlier in October 2022, following an upwardly revised 0.8 percent growth in September and compared with market expectations of a 1.7 percent fall. It was the largest decrease in trade since December 2021, as rising borrowing costs, high inflation and a deepening energy crisis hit consumer demand. Sales of non-food products declined 2.1 percent (vs 1.2 percent in September), with on-line trade falling 0.9 percent (vs 2.8 percent), while purchases of food, drinks and tobacco were down 1.5 percent (vs 0.6 percent in September). Meanwhile, fuel sales edged up 0.3 percent, after a 0.7 percent decrease in the previous month. On a yearly basis, retail sales dropped 2.7 percent in October, a fifth consecutive month of unchanged or lower trade.
0 days ago
Georgia Q3 Industrial Output Rises at Slower PaceGeorgia Industrial Production
Industrial production in Georgia rose 17.6% year-on-year in the third quarter of 2022, easing from 23.10% growth in the previous period. Production increased at a slower pace for both electricity, gas, steam & air-conditioning supply (17.4% vs 48.0%) and manufacturing (17.8% vs 20.9%). Meanwhile, output continued to grow for both mining & quarrying (17.0% vs 9.7%) and water supply sewerage, waste management & remediation activities (14.4% vs 6.6%).
0 days ago
Madrid Stocks Almost FlatSpain Stock Market
The IBEX 35 index was trading near the flatline around 8,388 on Monday, with investors cautiously monitoring key economic data for major economies in Europe. The final PMI data showed euro zone business activity declined for a fifth month in November, suggesting the economy was sliding into a mild recession as consumers cut spending amid surging inflation. Domestically, Spain's private sector rebounded slightly more than expected in November, ending a two-month sequence of contraction. Market sentiment was tempered by optimism around the easing of Covid-19 restrictions in China. On the corporate front, Indra was leading the losses, down over 2%, while Grifols jumped 7% after Morgan Stanley raised the company to "overweight" from "equal-weight" and raised its target price to 14 euros from 13 euros.
0 days ago
US Natural Gas Falls to 5-Week LowCommodity
US natural gas futures fell to below $6MMBtu, the lowest since October 28th on predictions of warmer weather over the next two weeks and expectations of higher supply. Freeport is set to again delay the restart of its LNG export plant to the end of the year from mid-December, leaving more gas in the domestic market. Also, average gas output in the US Lower 48 states rose to a record 99.5 bcfd in November, up from 99.4 bcfd in October. At the same time, the US government is stepping up efforts to reduce the risk of a railroad worker strike that could disrupt coal deliveries and force power generators to burn more gas. Still, US gas futures are up nearly 75% so far this year as overseas demand for LNG remains strong especially from Europe after the war in Ukraine has disrupted gas supply.
0 days ago
Taiwan Forex Reserves Largest on RecordTaiwan Foreign Exchange Reserves
Taiwan's foreign exchange reserves increased to USD 552.2 billion in November of 2022 from USD 542.79 billion in the previous month. It was the largest amount of foreign exchange reserves since records began in 1961, due to returns from foreign exchange reserves management, as well as exchange rate movements of other reserve currencies against the USD. In addition, the central bank has stepped in to smooth out volatile capital flows to maintain an orderly foreign exchange market. In November 2021, the reserves stood at USD 547.33 billion.
0 days ago
Czech Republic Wages Fall as ExpectedCzech Republic Wage Growth
The average real monthly wages in the Czech Republic dropped 9.8 percent year-on-year in the third quarter of 2022, the same pace as in the previous period and in line with market forecasts. Nominal wages advanced by 6.1 percent to CZK 39,858, but inflation accelerated to 17.6 percent. The wage volume increased by 7.2 percent, and the number of employees rose by 1 percent. Compared to the previous quarter, the seasonally adjusted average wage went up by 1.8 percent.
0 days ago
Hungary Retail Sales Growth Smallest in 1-1/2 YearHungary Retail Sales YoY
Retail sales in Hungary rose by 0.6% year-on-year in October 2022, the smallest growth since March 2021 and easing sharply from a 3% advance in the previous month, as trade declined in both non-food (-0.9% vs 2.7% in September) and food shops (-5.6% vs -2.8%). Meanwhile, automotive fuel sales accelerated by 19.7% from 18.6% a month earlier. In the January-October period, retail trade grew by 7%, compared to the same period of 2021.
0 days ago
South African Stocks Up on MondaySouth Africa Stock Market
The JSE FTSE All Share index was trading more than 1% higher above the 75,300 level on Monday, mainly pushed up by tech stocks and financials. Investors were upbeat about the easing of Covid-19 restrictions in mainland China, with the reopening of the economy expected to boost the global economy. Domestically, a meeting of the executive committee of the country's governing party kicked off to decide the future of President Cyril Ramaphosa. The president is facing a possible impeachment threat after a panel of experts found he may have violated his oath of office on allegations he hid large sums of foreign currency that he failed to report as stolen in 2020. On the data front, a fresh PMI survey showed South African private sector activity recovered slightly in November, after two consecutive months of declines.
0 days ago
Brent Crude Rises on Demand OptimismCommodity
Brent crude futures rose more than 1% to around $87 per barrel on prospects of a recovery in Chinese demand. The world's top crude importer has been signaling a softening stance in the fight against the coronavirus, raising hopes for a pivot in its strict zero-COVID policy and lifting the outlook for growth and demand. Among the latest announcements, China's health authorities eased testing requirements across major cities over the weekend. On the supply side, OPEC+ decided to stick to their existing policy of reducing oil output by 2 million barrels a day from November through 2023 to gauge the demand-supply dynamics better. The European Union will ban most seaborne Russian oil imports from today onwards while tentatively imposing a cap of $60 per barrel on Putin's crude. The US and other members of the G7 leading economies are also signaling support for a price cap on the oil Russia continues to sell worldwide.
0 days ago
Russian Stocks Rebound After Price Cap DecisionRussia Stock Market
The ruble-based MOEX Russia index was 1% higher to edge above the 2,200 mark on Monday, erasing losses from the prior week as investors digested the new price ceiling on Russian oil and assessed the initial impact of the EU’s seaborne oil embargo. The EU set a price ceiling of $60/barrel for the use of European tankers and insurance services on deliveries to Asia, below initial proposals but well above the current market price according to Urals oil contracts at Russian ports. Still, Moscow said it will not participate in any deals that have the cap triggered in the future. Oil giants Rosneft and Lukoil were up by 0.8% and 0.3%, underperforming the broader index slightly as the start of the European Union’s oil embargo on Russian seaborne crude deliveries came into effect today. In the meantime, metal companies rallied as easing Covid curbs in China drove base metal prices higher.
0 days ago
UK Services PMI Confirmed at 48.8United Kingdom Services PMI
The S&P Global/CIPS UK Services PMI was confirmed at 48.8 in November of 2022, the same as in the preliminary estimate and matching October's reading, which was the lowest since January of 2021. The reading pointed to a second straight month of falling services activity, as levels of incoming new work continued to decrease amid ongoing economic uncertainty and cost of living challenges weighing on discretionary spending. Cost pressures showed little signs of abating, with operating expenses again rising sharply, although pricing power was limited to some degree by rising competition and falling sales. Firms continue to hire additional staff as they sought to address skills shortages at their units, but confidence in the outlook remains historically subdued, despite improving noticeably since October.
0 days ago
UK Private Sector Output Continues to Fall in NovemberUnited Kingdom Composite PMI
The S&P Global/CIPS UK Composite PMI was unchanged at at 48.2 in November 2022, slightly down from a preliminary estimate of 48.3 and signaling a fourth successive monthly fall in private sector output. Service sector business activity continued to fall modestly, whilst manufacturing output fell at a faster pace. Incoming new business contracted the most in 22 months, while employment increased modestly. On the price front, input cost inflation eased again in manufacturing, dropping to its lowest level for three months, but rose at a faster rate in services. Both sectors, however, recorded slower output charge inflation in November, with the overall rate dropping to a 15-month low.
0 days ago
Austria's Q3 GDP Revised to Show ExpansionAustria GDP Growth Rate
The Austrian economy rose by 0.2% on quarter in the third quarter of 2022, compared to a preliminary estimate of a 0.1% contraction and following a 1.9% growth in the previous quarter. It marks the third consecutive quarter of expansion but the weakest since the last quarter of 2021, as government spending flattened (vs 2.3% in Q2) while fixed investment declined further (-3.1% vs -1.2%). At the same time, household consumption decreased slightly (-0.4% vs -0.8%) and net external demand contributed negatively to the GDP as exports fell more (-1.6% vs 3.4% in Q2) than imports (-1% vs -1.5%). On an annual basis, economic growth came in at 1.7% in the third quarter, slowing from a downwardly revised 6.1% rise in the previous period.
0 days ago
Germany Composite PMI Revised Slightly DownGermany Composite PMI
The S&P Global Germany Composite PMI was revised slightly lower to 46.3 in November of 2022 from a preliminary of 46.4, pointing to a fifth consecutive month of falling private sector activity, although the decline was less marked than in October (45.1). Both services (46.1) and manufacturing (46.2) shrank. The decline in factory new orders also eased, although it remained sharp and contributed to a further steep drop in overall new business. Total employment growth was unchanged from the modest pace seen in October. Additional workforce numbers in turn helped alleviate business capacity pressures, as evidenced by a solid and accelerated decline in outstanding work. Turning to prices, latest data showed further steep, albeit slower, rises in both input costs and output charges. The increase in input costs was the least marked for a year-and-half. Business expectations remained pessimistic but improved further from September's recent low.
0 days ago
Eurozone Service Sector Contracts for 5th MonthEuro Area Services PMI
The S&P Global Eurozone Services PMI came in at 48.5 in November 2022, little-changed from 48.6 recorded in both the preliminary estimate and October's final reading. The figure signaled a fourth straight month of falling output levels across the service sector, at a rate that was the fastest since February 2021. Incoming new business contracted for a fifth month running, with the pace of decline unchanged from October’s 20-month record. Meanwhile, the rate of job creation was the weakest in just over a year-and-a-half, while the level of work pending completion dropped for the second time in the past three months. On the price front, input costs and output charges both increased sharply, although rates of inflation were at their weakest in three months in both instances. Looking ahead, business confidence picked up, but remained subdued.
0 days ago
Euro Area Composite PMI Confirms Further Private Sector ContractionEuro Area Composite PMI
The S&P Global Eurozone Composite PMI was confirmed at 47.8 in November of 2022, pointing to a fifth straight month of falling private sector activity and the second-sharpest since May 2013, excluding months hit by COVID-19 restrictions. Although the rate of contraction eased for the first time over this sequence due to a slower fall in manufacturing production (47.1 vs 46.4), this masked an accelerated decline in services sector (48.5 vs 48.6). November also saw a softer deterioration in demand for goods and services, although backlogs of work fell at a stronger pace in a sign of alleviating capacity constraints. Employment continued to rise, although the rate of job creation was the weakest in almost two years. A pronounced softening of cost pressures in manufacturing helped bring the overall rate of input price inflation down to its lowest since September 2021. Finally, business confidence improved slightly but remained weak.
0 days ago
Italy Services PMI Stronger Than ExpectedItaly Services PMI
The S&P Global Italy Services PMI rose to 49.5 in November of 2022 from 46.4 in the previous period and well above market expectations of 48.3. Production and new business declined at a much softer pace, with the former showing the weakest contraction since August. At the same time, job creation was sustained and at the quickest pace since July. On the price front, inflation continued to pressure companies with higher energy, fuel, and transportation prices. While the rate of increase in input prices was the slowest in three months, it remained stubbornly elevated. As a result, firms continued to pass on these costs to clients, with the inflation rate hitting a new record in November. Finally, business confidence remained positive overall, recovering from October’s almost two-year low.
0 days ago
French Private Sector PMI Revised Slightly DownFrance Composite PMI
The S&P Global France Composite PMI was revised slightly down to 49.7 in November of 2022 from a flash estimate of 48.8, below 50.2 in the prior month. The latest reading indicated the first decline in French private-sector business activity since February 2021, amid poor performance in both manufacturing activity (PMI at 48.3 vs 47.2 in October) and the services sector (PMI 49.3 vs 51.7). New business intakes fell for a fourth successive month and at the quickest pace in 21 months. Backlogs of work subsequently fell as companies turned more focus to their incomplete business. Also, the rate of job creation was modest and among the weakest in two years. On the price front, strong inflationary pressures persisted, although both input costs and output charges slowed a bit. Lastly, business confidence fell to a two-year low in November.
0 days ago
Italy Private Sector Activity Slows for 5th MonthItaly Composite PMI
The S&P Global Italy Composite PMI Output Index was at 48.9 in November of 2022, rising from the 22-month low of 45.8 in the prior month and beating market estimates, but still pointing to the fifth straight contraction in the Italian private sector activity. The period witnessed slower downturns for both the manufacturing (48.4 vs 46.5 in October) and services (49.5 vs 46.4) sectors with a broad-based decline seen for new orders, driven partly by lower demand from foreign markets. Consequently, backlogs of work fell for the sixth consecutive month and Italian firms showed signs of more capacity. Still, employment grew at the sharpest rate in five months. On the price front, both input price inflation and output charge inflation slowed from the prior month as supply bottlenecks eased, but price growth remained high by historical standards.
0 days ago
EU Natural Gas Prices Rise by 5%Commodity
Dutch front-month natural gas rose by almost 5% to above €140 MWh, close to 2-month highs of €164.9 MWh hit on December 1st, as temperatures across Europe continued to fall raising demand for heating and reducing stockpiles. Storages in the EU were 91.6% full as of December 4th, below 91.9% the day before. Meanwhile, gas flows on the Yamal-Europe pipeline to Poland from Germany fell to zero while flows via Ukraine continued despite the EU’s bar on seaborne Russian oil imports and an oil price cap on Russian oil coming into effect. Also, last week negotiations started on a European Commission proposal for a cap on gas prices, and members are racing to reach a deal by December 13th. The energy situation in Europe remains challenging though, with many analysts suggesting demand will need to fall further and more imports of LNG will be needed to pass through winter months. In November, gas demand in the EU was cut by a quarter and governments have already warned about possible power cuts.
0 days ago
German Services Activity Falls Further in NovemberGermany Services PMI
The S&P Global Germany Services PMI was revised lower to 46.1 in November 2022 from a preliminary estimate of 46.4, and down from October's 46.5. The latest reading signaled a fifth month of contraction in the service sector, and at a solid and accelerated rate. Inflows of new work dropped sharply, at the second-quickest pace in the past two-and-a-half years, due to a squeeze on client budgets from high energy cost and inflation generally, alongside a reluctance among customers due to an uncertain economic outlook. Meanwhile, the rate of job creation hit a three-month high, but remained only modest and much slower than seen on average over the first half of the year, while backlogs of work fell. On the price front, input and output cost inflation rates eased to three-month lows, but remained among the quickest on record. Finally, business confidence remained weak, due to concerns over high inflation, risk aversion among clients and a broader economic slowdown.
0 days ago
French Services Sector Shrinks Slightly More than Early EstimateFrance Services PMI
The S&P Global France Services PMI was revised slightly down to 49.3 in November of 2022 from a flash estimate of 49.4 and below 51.7 in the previous month. The latest reading pointed to the first contraction in the country's services sector since March 2021, ending a 19-month sequence of continued expansion. There was a renewed decline in new business during November, as weakening economic conditions, high inflation and tighter financial conditions hit client demand. Also, the rate of job creation eased markedly to an 18-month low. On the price front, slower rises were seen in input costs and output charges, but price pressures remained historically elevated. Lastly, business confidence slid to a two-year low in November, amid expectations of an imminent recession prompted by the ongoing energy crisis.
0 days ago
Slovak Retail Sales Fall 4.4% in OctoberSlovakia Retail Sales YoY
Slovakia's retail trade fell by 4.4 percent from a year earlier in October 2022, following a 4.9 percent decrease in the previous month, and marking the third consecutive month of decline, mainly due to sales went down in stores, stalls or markets, which also include mail-order sale (-11.8 percent vs -9.9 percent in September), hypermarkets & supermarkets (-2.4% percent vs -4.4 percent) and other household equipment in specialized stores (-11.4 percent vs -10.5 percent). Sales were also down for cultural & recreation goods in specialized stores (-6.8 percent vs -0.8 percent) and automotive fuel (-5.1 percent vs -5.4 percent). By contrast, sales of food, beverages and tobacco were up 3.7 percent (vs 1.8 percent in September) and specialized stores, e.g. with footwear, textiles or drugstores (3.6 percent vs -0.8 percent). On a monthly basis, retail sales declined 1.7 percent.
0 days ago
Spain Private Sector Contracts for 3rd MonthSpain Composite PMI
The S&P Global Spain Composite PMI was up to 49.6 in November 2022 from 48.0 in the previous month, signaling a third month of contraction in private sector activity. A sharp decline in output and new orders in manufacturing was partially offset by growth in activity and new business in services. Meanwhile, employment was little changed overall, while business confidence remained historically subdued but did improve in November to reach a five-month high. On the price front, input price inflation fell noticeably in manufacturing but remained elevated in services. Both sectors experienced strong rates of charge inflation.
0 days ago
Iron Ore Extends Rally to 2-1/2-Month HighCommodity
Prices for iron ore cargoes with a 63.5% iron ore content for delivery into Tianjin rose to $106.5 in December, the highest since late August as eased Covid curbs and measures to stimulate the economy in top consumer China increased expectations for higher demand. Key Chinese cities lose lockdown rules after protests, raising hopes that other industrial hubs would follow. Also, the country’s largest commercial banks agreed to extend $162 billion in fresh credit lines to private developers to fight the sector’s liquidity crunch, and the PBoC further cut banks' reserve requirement ratio. Earlier, the national bond authority expanded a key financing program by $35 billion to support the sales of bonds after a period of defaults increased the cost of credit for residence builders. Still, prices are 33% below their March peak as concerns are still in place about the debt-ridden property sector in China and as supply from Ukraine remains steady despite the war.
0 days ago
Romanian Jobless Rate Edges Higher in OctoberRomania Unemployment Rate
Romania’s seasonally adjusted unemployment inched up to 5.5 percent in October 2022, from 5.4 percent in the previous month, as the number of people registered as unemployed rose by 7.7 thousand to 453.2 thousand. Meantime, the jobless rate for men slightly increased to 6.1 percent from 6 percent, while that for women remained unchanged at 4.7 percent.
0 days ago
FTSE 100 Hovers Near Six-Month HighUnited Kingdom Stock Market
Equities in London fluctuated between small gains and losses on Monday, with the benchmark FTSE hovering near a six-month peak of 7,550 points, as gains in the materials and technology sectors off losses in energy. Sentiment remained somewhat upbeat amid growing speculation that China will gradually move away from its strict zero-COVID policy after health authorities eased testing requirements across major cities over the weekend. Asia-focused Prudential rallied more than 2% to lead the FTSE 100, while Persimmon, down almost 3%, was among the biggest laggards. In other corporate news, Britain's Vodafone Group said Chief Executive Nick Read would step down at the end of this year.
0 days ago
Steel Rebounds on Eased Covid RestrictionsCommodity
Steel rebar futures rebounded to above CNY 3,720 per tonne, tracking the rise in base metals and approaching the one-month high of CNY 3,757 hit on November 16th as the partial easing of strict pandemic curbs in China set hopes for further economic reopening in the world’s top consumer. Bullish sentiment has also been supported by efforts to stimulate the Chinese property sector. The country’s top commercial banks agreed to extend $162 billion in fresh credit lines for private developers, officials lifted a ban on equity refinancing for listed developers, and the PBoC cut the reserve requirement ratio by 25bps to turn up lending to the debt-ridden sector. Still, further signs of a slowing economy capped the rebound for steel, with the NBS PMI pointing to the sharpest contraction in factory activity in seven months.
0 days ago
Spain Service Sector Returns to GrowthSpain Services PMI
The S&P Global Spain Services PMI rose to 51.2 in November 2022 from October’s 49.7, easily beating market expectations of 50.5. The index recorded its highest reading since July to snap a two-month sequence of contraction, with both activity and new business expanding amid reports of firmer market demand. Still, new export orders were down for a fifth consecutive month. Employment levels increased for a second month in a row, while backlogs of work declined for a fourth successive month and at a solid and accelerated rate. On the price front, input price inflation remained elevated, and little changed on October’s four-month high, while prices charged increased to the sharpest degree since June, and for the 20th straight month. Looking ahead, business confidence improved in November, but remained historically subdued.
0 days ago
Investors in Europe Start Week in Cautious MoodGermany Stock Market
European stock indexes traded flat to lower on Monday, starting the first full week of December in cautious mood, as investors eye the release of services PMI surveys and European retail sales data later today. At the same time, the market entered a quiet period ahead of the Federal Reserve’s December policy meeting next week, amid expectations that US policymakers will slow the pace of interest rate hikes despite the hotter-than-anticipated US jobs report. On a brighter note, China-exposed stocks like miners should be supported by news that more Chinese cities announced an easing of coronavirus curbs. On the corporate front, online German broker Flatex cut its guidance, while Vodafone's CEO Nick Read stepped down and will be replaced by finance chief Margherita Della Valle.
0 days ago
Australia Construction Activity Sinks for 6th MonthAustralia Construction PMI
The Australian Industry Group Construction PMI increased to 48.2 in November of 2022 from 43.3 in October, but continued to point to contraction in activity across the construction sector for a sixth month, as demand side pressures, including rising interest rates and economic uncertainty, are dampening construction sales and new orders. Also, supply side constraints, especially a shortage of skilled trades, continue to inhibit activity, but there are signs of materials supply chain pressures easing. Meanwhile, the employment index rose into weak expansion as absenteeism eased. The selling prices indicator expanded at a slower rate compared to the previous two months. Input prices jumped up to 91.9 points, indicating the gap in growth between prices widened. Capacity utilisation rose slightly to 82.9% and remains elevated as it has been since the start of 2021.
0 days ago
Turkey Producer Inflation Eases from Record HighTurkey Producer Prices Change
The annual producer inflation in Turkey eased to 136.02% in November 2022 from an all-time high of 157.69% in the previous month, as prices notably slowed from three of the four main sectors. Costs in mining and quarrying eased to 146.43% (vs 162.06% in October), manufacturing (107.64% vs 122.97%) and electricity, gas, steam and air conditioning (442.97% vs 554.56%). Meanwhile, prices rose faster in water supply (114.41% vs 109.45%). On a monthly basis, producer prices grew by 0.74%, the least since June 2020.
0 days ago
Kenya Private Sector Growth AcceleratesKenya Manufacturing PMI
The Stanbic Bank Kenya PMI increased to 50.9 in November of 2022 from 50.2 in October, as output returned to grow while new orders rose for the third straight month, and at a moderate pace that was faster than in October. Employment increased marginally with the backlogs of work declining for the first time since April while purchasing activity rose for the third month in a row. On the cost side, input costs rose, amid reports of rising import costs due to a weaker exchange rate, as weel as higher taxation and transport costs. Meanwhile, output cost inflation eased. Finally, business sentiment weakened from October's 15-month high.
0 days ago
Turkish Inflation Eases for 1st Time in 18 monthsTurkey Inflation Rate
The annual inflation rate in Turkey slowed for the first time in 18 months to 84.4 percent in November 2022, from 85.5 percent in the previous month, and in line with market forecasts of 84.7 percent. Prices rose much less for transportation (107 percent vs 117.2 percent in October) and there was also a slowdown in cost of housing & utilities (82.9 percent vs 85.2 percent), furnishings, household equipment, routine maintenance (92.8 percent vs 93.6 percent), clothing & footwear (37 percent vs 41.3 percent) and hotels, cafes & restaurants (80.3 percent vs 81.9 percent). On the other hand, prices increased faster for food & non-alcoholic beverages (102.6 percent vs 99.1 percent). On a monthly basis, consumer prices rose by 2.9 percent, easing from the 3.5 percent jump in the previous month.
0 days ago
South Africa Private Sector Activity Rebounds in NovemberSouth Africa Composite PMI
The S&P Global South Africa PMI increased to 50.6 in November of 2022 from 49.5 in October, pointing to the first increase in private sector activity in three months, as demand recovered slightly leading to an increase in new business volumes. However, some firms continued to report weak economic conditions both domestically and worldwide, as well as a negative impact from the load shedding programme. Also, with supply conditions remaining weak and firms beset by load shedding, output fell for the third straight month. On a positive note, inflationary pressures showed further signs of softening, as purchase prices rose at the slowest rate since August 2021, leading to a weaker uplift in output charges. Employment also went up and businesses remained markedly upbeat about future activity amid expectations that disruption from load shedding will ease and price pressures will continue to soften.
0 days ago
European Markets Head for Muted OpenGermany Stock Market
European equity markets were headed for a muted open on Monday as the market entered a quiet period ahead of the Federal Reserve’s December policy meeting, though easing Covid restrictions in China buoyed sentiment. Investors digested a hotter-than-anticipated US jobs report, but expectations that the Fed will slow the pace of interest rate hikes starting this month remained intact. Meanwhile, investors looked ahead to a raft of European economic reports including final eurozone manufacturing and services activity data for November, as well as regional retail sales figures for October. DAX and Stoxx 600 futures fluctuated around the flatline in early trade.
0 days ago
Swedish Q3 Current Account Surplus Narrows SharplySweden Current Account
Sweden's current account surplus declined sharply to SEK 31.7 billion in the third quarter of 2022 from SEK 76.6 billion in the same period last year, as the goods surplus plunged to SEK 21.1 billion from SEK 42.7 billion a year ago, while the services gap jumped to SEK 22.8 billion from 2.3 billion. Also, secondary income, which includes international cooperation and donations and contributions to the EU, presented a deficit of SEK 26.0 billion, up from SEK 20.3 billion a year earlier. Meantime, primary income, which consists mainly of compensation of employees and investment income, presented a surplus of SEK 59.4 billion in the third quarter, up from SEK 56.5 billion.
0 days ago
Uganda Private Sector Activity Rises in NovemberUganda Composite PMI
The Stanbic Bank Uganda PMI rose to 50.9 in November 2022 from 50.0 in the previous month. The latest reading was still below the series average but showed signs of improvement in business activity for the fourth consecutive month, as output and new orders continued to expand. At the same time, employment increased for the second month and firms were able to deplete backlogs of work. Also, purchasing activity increased in November, ending a two-month period of decline. On prices, input costs rose, attributed to the rising electricity and water costs, as well as increases in both purchase prices and staff costs, although a report said that cost for fuel started to cool down. Selling prices were up for the fifteenth month running as a response to the rise in input costs. Finally, sentiment remained positive, on hopes of continued growth in new orders and moderation of prices.
0 days ago
Mozambique Standard Bank PMI Improves from 9-Month LowMozambique Composite PMI
The standard Bank Mozambique PMI rose to 50.8 in November 2022 from a 9-month low of 50.1 in the previous month. The upturn was prompted by new work inflows which strengthened for the first time since July, as demand increased and new customers arose; although the growth was marginal and limited to construction and service sectors. Meanwhile, the overall employment rate pointed to its six-month low, despite the increase in job numbers in an attempt to fulfill higher workloads and strengthen capacity. On prices, input demand was hit by firms' cost-cutting efforts on purchasing, pushing the input price to grow at its slowest in eight months. Concurrently, output charges also rose marginally and the least in ten months. Finally, sentiments ticked lower but remained positive, as firms expect activity to increase next year, amid hopes of expansion, new products and rise in client numbers.
0 days ago
India Equities Down for 2nd SessionIndia Stock Market
The BSE Sensex fell 246.1 points or 0.4% to 62,622.7 in morning deals on Monday, extending losses for the second straight session, amid a rise in oil prices after OPEC+ decided to maintain production at current levels. The rises in oil prices will drive India's retail inflation, which imports almost 85% of its oil. Meantime, US stock futures fell ahead of the Fed’s December policy meeting next week. Elsewhere, COVID zero in China may formally remain in place until April, though the risk of an earlier but managed exit has increased, according to a strategist at Goldman Sachs. Market participants now await the result of the RBI's monetary policy review on Wednesday. The central bank is expected to deliver its fifth straight hike by a smaller 35 basis points to 6.25%, as inflation slowed amid moderation in food prices. The IT sector, oil and gas, and consumer goods led the declines, amid notable losses from Persistence (-2.2%), L&T Technology (-1.3%), and Hindustan Petroleum (-1.2%).
0 days ago
Aussie Climbs Ahead of RBA DecisionAustralia Currency
The Australian dollar appreciated past $0.68, scaling its highest levels in nearly three months as top trading partner China continued to shift away from strict Covid restrictions, while solid US jobs data failed to counteract expectations that the Federal Reserve will slow the pace of interest rate hikes. Investors also geared up for the Reserve Bank of Australia’s policy decision this week, where it is expected to deliver another modest 25 basis point rate increase to 3.1% as domestic inflation trended lower. Analysts also reduced the implied peak for rates to around 3.6% from as much as 4.31% back in September. The monthly CPI indicator in Australia slowed to 6.9% in the ten months to October from 7.3% in September and defied expectations for a slight acceleration to 7.4%.
0 days ago
Russia Private Sector Activity StagnatesRussia Composite PMI
The S&P Global Russia Composite PMI increased to 50.0 in November 2022 from October's six-month low of 45.8, with a further contraction in service sector output counteracting a solid rise in manufacturing production. New orders were broadly unchanged as service sector weakness dampened a quicker monthly expansion in manufacturing demand. However, export orders continued to fall sharply amid weak global demand. Meantime, employment fell for the fourth month running, amid a further decline in backlogs of work. Further, confidence was buoyed by stronger expectations at manufacturers and renewed optimism at service sector firms.
0 days ago
Russia Services Sector Shrinks at Softer PaceRussia Services PMI
The S&P Global Russia Services PMI increased to 48.3 in November 2022 from October’s 7-month low of 43.7. The reading pointed to the second straight month of contraction in the sector, amid a softer decline in both output and new orders, as some firms noted the acquisition of new customers. Meanwhile, employment declined, with backlogs of work decreasing at a solid pace. On the pricing front, input cost inflation eased fractionally, while output cost inflation slowed to the softest pace since February 2021. Lastly, sentiment returned to a positive, due to hopes of greater client demand and a reduction in competition.
0 days ago
Stocks in China Hit 10-week HighChina Stock Market
CSI 300 increased to a 10-week high of 3945
0 days ago
Stocks in China Hit 11-week HighChina Stock Market
SHANGHAI increased to a 11-week high of 3208
0 days ago
Singapore Retail Sales Growth Eases to 7-Month LowSingapore Retail Sales YoY
Singapore's retail sales increased by 10.4% yoy in October 2022, easing from an upwardly revised 11.3% growth in the prior month.This was the 8th straight month of increase in retail trade but the softest pace since March, with sales moderating for petrol services (9.9 vs 14.0% in September), computer & telecommunications (0.6% vs 24.9%). At the same time, sales of motor vehicles fell further (-15.8% vs -20.2%). By contrast, sales growth accelerated for food & alcohol (61.0% vs 52.3%), recreational goods (23.5% vs 17.6%), cosmetics, toiletries (20.8% vs 12.5%), wearing apparel (52.9% vs 52.3%), optical goods & books (15.3% vs 9.3%), department stores (43.7 vs 35.3%), and others (22.9% vs 17.1%). On a monthly basis, retail sales edged up 01%, after a downwardly revised 3.2% rise in September.
0 days ago
India Services Growth Strongest in 3 MonthsIndia Services PMI
The S&P Global India Services PMI was up to 56.4 in November 2022 from 55.1 in October, exceeding market forecasts of 55.4. The reading pointed to the strongest expansion in the services sector since August, supported by a sharp expansion in output and further job creation. New orders grew, with export orders rising for the first time since the onset of COVID-19 in early-2020. Meanwhile, employment rose at a solid pace that was among the fastest in over three years, with backlog of work rising at a slower pace. Regarding inflation, input cost inflation accelerated to the second-fastest since July, while output cost inflation rose the strongest since July 2017, as companies transferred part of their additional cost burdens on to consumers. Finally, business confidence improved.
0 days ago
Saudi Arabia Non-Oil Private PMI Highest in 14 MonthsSaudi Arabia Manufacturing PMI
Riyad Bank Saudi Arabia PMI rose to 58.5 in November 2022 from 57.2 in October, above the long-run series average of 56.8. This was the highest reading since September 2021, as output rose the most in seven years, new orders growth accelerated to a 14-month high, and export sales rose the most in seven years. Also, input buying rose at the second-fastest rate since August 2015, amid a slight rise in employment with many companies reportedly keeping staffing unchanged. Meantime, backlogs of work declined for the sixth month in a row. On the pricing front, inflationary pressures picked up due to high material prices, a greater impact of inflationary pressures, and a renewed rise in staff costs. These brought input cost and output prices hit their highest since July. Lastly, business sentiment improved to the highest since January 2021, supported by solid new orders and the government's Vision 2030 Initiative.
0 days ago
Egypt Non-Oil Private Sector Shrinks for 24th MonthEgypt Manufacturing PMI
The S&P Global Egypt PMI dropped to a five-month low of 45.4 in November 2022 from 47.7 in October. The latest print was the second lowest since June 2020, extending the current sequence of deterioration in the non-oil private sector to two years, amid rapid falls of the pound and intense cost pressures. Both output and new orders fell the most since the initial COVID-19 lockdown in May 2020, while export sales were weak due to slowing global conditions. Also, firms rapidly cut input buying levels, due to rising import cost and falling orders. Meantime, employment grew for the fourth time in five months, and at the quickest rate in over three years. However, backlogged orders increased again, with some firms reportedly facing fresh disruptions to supply chains from import curbs. On the cost side, purchase price inflation hit a 52-month high, reflecting weakness in the local currency; while output prices quickened. Looking ahead, sentiment recovered slightly from October's series low.
0 days ago
Chinese Yuan Jumps on Easing Covid CurbsChina Currency
The offshore yuan appreciated past 7 per dollar, hitting its strongest levels in nearly three months as China continued to shift away from strict Covid restrictions, sparking hopes of further economic reopening. In the latest developments, major Chinese cities including Shanghai and Hangzhou scrapped testing requirements to enter public venues or use public transportation, joining other metropolises in relaxing virus curbs that have weighed on the economy and caused public outcry. Investors also reacted to data showing November services activity in China contracted the most in six months. Moreover, the yuan benefited from a weaker dollar as investors shook off hotter-than-anticipated US jobs data and continued to cling on bets that the US Federal Reserve will slow the pace of interest rate hikes starting this month.
0 days ago
"""
news_cache = {"12/05/2022-0 days ago":dec_5_2022}
