def new_magic(date_data:str):
  split_data = date_data.split("\n")
  split_data = [data for data in split_data if data != ""]

  headlines = []
  articles = []
  dividers = []
  for index in range(len(split_data)):
    if (index+1) % 3 == 0:
      split_data[index] = "divider"

  split_data = [data for data in split_data if data != "divider"]

  headlines = []
  articles = []
  for index, headline in enumerate(split_data):
    if index % 2 == 0:
      headlines.append(split_data[index])
    else:
      articles.append(split_data[index])

  return articles, headlines


news_string = """
Shares in Singapore Fall from Near 5-Month HighsSingapore Stock Market
Equities in Singapore dropped 29 points or 0.9% to 3,277 around midday on Tuesday, retreating from near 5-month tops hit in the prior session, dragged down by mounting worries over the impact of rising goods and services tax (GST) on the 2023 inflation figures and growth momentum in the city-state. Previously delayed due to the pandemic, the GST rises to 8% from 7% starting from January 1st of this year. Traders were also cautious ahead of US CPI data this week, with Fed San Fransisco President Mary Daly and her Atlanta counterpart Raphael Bostic saying Monday the US central bank would likely hike interest rates to above 5%. Meantime, Goldman Sachs said it expects pressure on US profit margins, changes to US corporate tax policies, and the likelihood of a recession in 2023. Jardine Matheson Hlds. shed almost 3%, followed by Fraser Logistics & Commercial Trust (-2.5%), Emperador Inc. (2%), Singapore Telecommunications (-2%), Wilmar Intl. (-1.2%), and DBS Group Hlds. (-1.1%).
37 hours ago
Malaysia Jobless Rate Drops to 3.6%Malaysia Unemployment Rate
The unemployment rate in Malaysia dropped to 3.6 percent in November of 2022 from 4.3 percent in the same month a year earlier. The number of jobless persons declined by 15.6 percent from a year earlier to 600.9 thousand, while employment increased by 3.2 percent to 16.11 million. At the same time, the labor force rose 2.5 percent to 16.71 million. In October, the jobless rate was at 3.6 percent.
37 hours ago
Indonesia Equities Down to Near 8-Month LowIndonesia Stock Market
Indonesia's stock market fell 53 points or 0.8% to 6,638 on Tuesday morning deals, trading at near eight month-low, pressured by hawkish comments from two US Fed officials Monday ahead of key inflation data. Meantime, worries deepened that any optimism from China's reopening may be short-lived, with a COVID surge threatening Chinese villages as Lunar New Year approaches and millions are expected to travel home. Locally, political uncertainties built as parties in Indonesia are preparing for the general elections next year. On fresh data, retail sales growth in Southeast Asia's biggest economy was at a 4-month low in November, amid persistent cost pressures and the impact of higher borrowing costs. Financial stocks lead the losses, with sharp falls from Bank Mandiri (-3.9%), Bank Rakyat Indonesia (-2%), and Bank Central Asia (-1.8%). Other notable losses were Astra Intl. (-0.5%), Bumi Resources (-0.7%), Aneka Tambang (-0.5%), Transcoal Pacific (-4.6%), and Merdeka Copper (-0.9%).
38 hours ago
Oil Eases on Rate Hike ConcernsCommodity
WTI crude futures fell toward $74 per barrel on Tuesday, snapping a three-day advance as hawkish remarks from US Federal Reserve officials outweighed hopes for a demand recovery in China. San Francisco Fed Bank President Mary Daly said she expects the central bank to raise rates to somewhere over 5%, while Atlanta Fed Bank President Raphael Bostic noted that policymakers should hike above 5% by early in the second quarter and hold them there for a long time. Investors also turned cautious ahead of the Lunar New Year in China, amid fears that increased travel could lead to a surge in Covid cases in the world’s top crude importer. Meanwhile, Beijing recently provided refiners and traders with a generous import quota in its second allocation for 2023, as China gears up for growth after rapidly dismantling strict Covid restrictions, as reported by Bloomberg.
38 hours ago
Indonesia Retail Sales Rise the Least in 3 YearsIndonesia Retail Sales YoY
Retail sales in Indonesia grew by 1.3 percent year-on-year in November 2022, easing from a 3.7 percent rise in October. This was the fourteenth month of increase but the softest pace since November 2019 amid soaring cost pressures and higher interest rates. Sales rose slower for food, beverages, and tobacco (4.8% vs 8.0% in October) and clothing (17.1% vs 25.3%), and declined for automotive parts & accessories (-9.5% vs -5.2%), fuels (-5.7% vs 0.5%), home appliances (-14.2% vs -14.8%), and information & communication (-16.3% vs -20.7%). On the contrary, they accelerated for cultural & recreational goods (5.8% vs 3.7%).
38 hours ago
China Stocks Slip as Financials DragChina Stock Market
The Shanghai Composite fell 0.3% to below 3,170 while the Shenzhen Component lost 0.1% to 11,440 on Tuesday, easing from recent highs as investors took some profits following a strong rally driven by China’s economic reopening, with heavyweight financial firms leading the retreat. Investors also turned cautious ahead of the Lunar New Year amid fears that increased travel could lead to a surge in Covid cases. Moreover, a weak session on Wall Street overnight dented sentiment as concerns about growth, inflation and a higher peak for rates continued to grip financial markets. Losses in the financial sector were led by Ping An Insurance (-1.9%), China Merchants Bank (-1.3%) and Ping An Bank (-1.2%). Other heavyweight firms also declined, including BYD Company (-1.7%), Zijin Mining (-1.1%) and Guangdong Zhongshe (-1.5%).
38 hours ago
Hang Seng Trades LowerHong Kong Stock Market
The stock market in Hong Kong fell 119 points or 0.55% to 21,270 in morning trade on Tuesday, retreating from near 6 month-peaks touched the day before after Wall Street's benchmark indexes gave up earlier gains overnight to end mixed ahead of a speech by Fed Chair Powell later today and US inflation data Thursday. Traders secured their profits, amid worries that COVID cases in China could spread to rural areas as millions are expected to travel for the Lunar New Year celebration later this month. Elsewhere, China's stock regulator is set to stop local businesses in some sectors, including food and beverage, and pandemic testing companies, from listing on the country's main stock exchanges, the Financial Times said. Tech stocks and consumer cyclicals mainly declined, with bottom movers from Orient Overseas Intl. (-2.3%), NetEase Inc. (1.8%), Alibaba Group Hlds. (-1.7%), Meituan (-1.6%), and Zhongsheng Group (-1.4%). China Education Group sank around 9%, on the discounted share sale.
39 hours ago
Wheat Hits 1-month LowCommodity
Chicago wheat futures dropped to $7.35 per bushel, a level not seen since December 9th, amid signs of strong supply and lower demand. Agribusiness economist at National Australia Bank said that wheat production is expected to rise to a record 42 million tonnes. In December, the Australian Bureau of Agricultural and Resource Economics estimated wheat production in the world's second-largest exporter of grain, at 36.6 million tonnes in the 12 months to June 30, 2023. The USDA on Monday reported weekly grain export inspections for wheat near the low-end of a range of trade estimates. On the demand side, the latest WASDE report revised its world consumption projections downwards by 1.6 million tonnes to 789.5 million for the current marketing year, mainly due to lower feed and residual usage in the EU and Ukraine.
39 hours ago
Philippines Imports Fall for 1st Time in Near 2 YearsPhilippines Imports YoY
Exports from the Philippines rose 13.2% year-on-year to USD 7.10 billion in November 2022, after a marginally revised 20.3 percent increase a month earlier, pointing to the third straight month of growth amid sustained foreign demand and easing supply chain disruptions. Sales mainly increased for other mineral products (51.0%), ignition wiring sets and other wiring sets used in vehicles, aircraft, and ships (23.1%), electronic products (22.9%), cathodes and sections of cathodes (8.7%), and other manufactured products (4.8%). In contrast, exports fell for coconut oil (-35.2%), metal components (-19.2%), chemicals (-15.1%), electronic equipment (-4.7%), and machinery & transport equipment (-0.2%). Shipments rose to Hong Kong (39.1%), the US (13.8%), Japan (6.7%), Singapore (2.4%), Taiwan (32.8%), South Korea (44.4%), Netherlands (18.8%), Germany (7.2%), the ASEAN countries (0.8%), and the EU (10.7%), while dropping to China (-1.3%), Vietnam (-43.6%), and India (-0.4%).
40 hours ago
Philippines Exports Grow for 3rd MonthPhilippines Exports YoY
Exports from the Philippines rose by 13.2% year-on-year to USD 7.10 billion in November 2022, after a marginally revised 20.3 percent increase a month earlier, pointing to the third straight month of growth amid sustained foreign demand and easing supply chain disruptions. Sales mainly increased for other mineral products (51.0%), ignition wiring sets and other wiring sets used in vehicles, aircraft and ships (23.1%), electronic products (22.9%), cathodes and sections of cathodes (8.7%), and other manufactured products (4.8%). In contrast, exports fell for coconut oil (-35.2%), metal components (-19.2%), chemicals (-15.1%), electronic equipment (-4.7%), and machinery & transport equipment (-0.2%). Shipments rose to Hong Kong (39.1%), the US (13.8%), Japan (6.7%), Singapore (2.4%), Taiwan (32.8%), South Korea (44.4%), Netherlands (18.8%), Germany (7.2%), the ASEAN countries (0.8%), and the EU (10.7%). By contrast, sales dropped to China (-1.3%), Vietnam (-43.6%), and India (-0.4%).
40 hours ago
Philippines Trade Deficit NarrowsPhilippines Balance of Trade
The trade deficit in the Philippines fell to USD 3.68 billion in November 2022 from USD 4.71 billion in the same month a year earlier, as exports grew while imports shrank. Shipments increased 13.2% from a year earlier to USD 7.1 billion as supply chain issues eased following the removal of tough COVID restrictions in many countries. Meantime, purchases were down 1.9% to USD 10.78 billion, the first drop since January 2021, due to weak domestic demand on the back of intense price pressures and a weak peso. Considering the first eleven months of the year, the trade gap soared to USD 53.71 billion from USD 37.15 billion in the same period in 2021.
40 hours ago
Japanese Shares Climb on Tech BoostJapan Stock Market
The Nikkei 225 Index climbed 1% to above 26,200 while the broader Topix Index added 0.9% to 1,893 on Tuesday, rising for the third straight session, helped by gains in technology stocks. Japanese shares also tracked US tech stocks higher, though investors remain cautious as hawkish remarks from Federal Reserve officials brought down hopes that the central bank might dial back its aggressive monetary tightening. Meanwhile, investors assessed data showing the core inflation rate in Tokyo exceeded forecasts in December, while household spending in Japan unexpectedly fell in November. Gains in the technology sector were led by SoftBank Group (3.2%), Tokyo Electron (2.4%), Lasertec (3%), Keyence (2%) and Murata Manufacturing (2.3%). Other index heavyweights also advanced, including Eisai Co (6.7%), Sony Group (1.3%) and Daikin Industries (4.5%).
41 hours ago
UK Retail Sales Jump in Dec, Lagging Behind InflationUnited Kingdom BRC Retail Sales Monitor YoY
Retail sales in the United Kingdom increased 6.5% on a like-for-like basis in December 2022 from a year ago, accelerating from a 4.1% rise in November amid higher cost of goods and the Christmas boost. However, the growth rate still lagged behind inflation. December’s figure was also the highest since January but remained well below the pace of UK inflation +10.7% in November, close to a 4-decade high of 11.1% recorded in October. Helen Dickinson, chief executive at the British Retail Consortium, said: “After an exceptionally challenging year which saw inflation climb and consumer confidence plummet, the uptick in spending over Christmas gave many retailers cause for cheer. Nonetheless, despite the stronger sales, growth remained below inflation, making December the 9th consecutive month of falling volumes.” She added that retail faces headwinds in 2023 as consumer spending will be constrained by increasing living costs.
41 hours ago
Tokyo Core Inflation Exceeds ForecastsJapan Tokyo Core CPI
The core consumer price index for the Ku-area of Tokyo in Japan jumped 4% in December 2022, rising at the fastest pace in four decades and exceeding forecasts of a 3.8% increase as a sign of broadening inflationary pressure. Tokyo’s core inflation rate, a leading indicator for nationwide price trends, surpassed the Bank of Japan’s 2% target for the seventh month since businesses continued to pass on higher costs to consumers. This will likely bolster expectations of the BOJ exiting its ultra-easy monetary policy through yield target adjustments. Still, BOJ Governor Haruhiko Kuroda continued to deny speculations of a hawkish tilt, highlighting the bank must keep supporting the economy until the current cost-push inflation turns into a demand-driven one accompanied by wage growth.
41 hours ago
US Futures Flat After Mixed SessionUnited States Stock Market
US stock futures were little changed in Asian trade on Tuesday after the major averages ended mixed during Monday’s regular session, as hawkish remarks from Federal Reserve officials brought down hopes that the central bank might dial back its aggressive monetary tightening. Futures contracts tied to the three major indexes all traded near breakeven. In regular trading on Monday, the Dow and S&P 500 erased early gains to end 0.34% and 0.08% lower, respectively, as Fed’s Mary Daly said she expects rates to rise somewhere above 5% and Fed’s Raphael Bostic noted that policymakers should hike above 5% by early in the second quarter and hold rates there for a long time. Meanwhile, the Nasdaq Composite managed to close 0.63% higher despite downward market pressure, helped by a strong rally in Tesla and other technology stocks. Investors now look ahead to key inflation data on Thursday, as well as Fed Chair Jerome Powell’s speech later in the global day.
41 hours ago
Australian Shares Slip as Commodities WeighAustralia Stock Market
The S&P/ASX 200 Index fell 0.28% to close at 7,131 on Tuesday, snapping a four-day advance, weighed down by losses in the energy and mining sectors. A weak session on Wall Street overnight also dented sentiment as concerns about growth, inflation and a higher peak for rates continued to grip financial markets. Heavyweight energy and mining stocks led the retreat, with notable losses from Woodside Energy (-0.2%), Santos (-0.8%), Whitehaven Coal (-1.1%), BHP Group (-0.5%) and Pilbara Minerals (-1.3%). Gold stocks also declined, including Newcrest Mining (-2.2%), Evolution Mining (-2.7%) and Northern Star Resources (-2.3%). Elsewhere, technology stocks slumped as well, while healthcare firms advanced.
42 hours ago
South Korea Current Account Turns to DeficitSouth Korea Current Account
South Korea’s current account registered a deficit of $620 million in November 2022, after recording $880 million surplus in October. The balance of goods recorded a deficit of $157 million down from a surplus of $607 million in the same month of the previous year. The deficit in the service balance widened to $ 340 million from $280 million in the same month of the previous year mostly due to a narrower surplus of the transportation balance. Also, the secondary income account recorded a $140 million deficit compared to $150 million deficit in November 2021. In the meantime, the primary income account surplus increased to $143 million from $117 million in the same month of the previous year.
42 hours ago
Stocks in New Zealand SubduedNew Zealand Stock Market
New Zealand's equities were almost flat at 11,646 around midday on Tuesday after closing slightly higher the day before, tracking Wall Stret's S&P 500 that closed muted Monday, as traders digested remarks from two US Fed officials that interest rates in the world's largest economy could top 5%. Investors are awaiting a speech from Fed Chair Powell later today at a central bank conference and US CPI data Thursday. Domestically, household finances that were under strain and soaring prices last year are presenting big economic challenges to Prime Minister Jacinda Ardern who seeks a third term in this year's general election. Gains in commercial services, health technology, and non-energy minerals were offset by losses in energy minerals, consumer durables, and industrials. Skycity Entertainment gained 1.2% while Air New Zealand and Genesis Energy rose 0.7% and 0.6%, respectively, amid falls from Chorus Ltd. (0.9%), A2 Milk Co. (-0.5%), and Fletcher Buildings (-0.4%).
42 hours ago
Brazilian Equities at Over Two-Week HighBrazil Stock Market
Brazil’s Ibovespa stock index managed to close about 0.2% up at an over two-week high of 109,130 on Monday, with investors weighing the effects of the weekend's institutional attacks by supporters of former President Jair Bolsonaro as a way of contesting the new government. Meanwhile, concerns about the country's fiscal health persist, although President Luiz Inacio Lula da Silva said on Friday it was possible for Brazil to develop responsibly. On the economic front, Brazil's financial market downgraded the country's economic growth forecasts for this year and the next, from 3.04% to 3.03% for 2022, and from 0.80% to 0.78% for 2023. Inflation forecasts were kept at 5.62% for 2022, but raised to 5.36% from 3.70% for 2023 and to 5.31% from 3.65% for 2024. Major gains were AMERICANAS (+6.44%), CVC BRASIL (+4.98%),GOL PN (+4.07%), and JBS ON (+3.02%). On the other hand, the top losers were HAPVIDA (-11.02%), GRUPO SOMA (-3.16%), FLEURY (-3.08%).
43 hours ago
Canadian Stocks End at Near 4-Week HighCanada Stock Market
The S&P/TSX Composite index was up about 0.2% to close at a near four-week high of 19,857.1 on Monday, extending gains from the prior week. Base metals, technology companies and energy shares provided the main support. Meanwhile, investors weighed optimism around China reopening its borders against hawkish comments from two Fed officials suggesting interest rates will remain higher for longer. On the corporate front, Cannabis producer Tilray Brands Inc dropped 6.4% after it reported a second-quarter loss, which was at par with analyst expectations, On the other hand, financial services firm Canaccord Genuity Group Inc soared 29.5% after a group led by the company's management said it would launch a takeover bid at nearly C$1.13 billion.
44 hours ago
Wall Street Pares GainsUnited States Stock Market
US stocks erased almost all gains in the last hour of trading on Monday, with the Dow Jones turning negative after rising more than 200 points and S&P trading near the flat line after hawkish comments from two Fed officials brought down hopes that the Federal Reserve might dial back its aggressive monetary tightening. Fed Mary Daly said she expects the central bank to raise rates to somewhere above 5% and Fed Raphael Bostic noted that policymakers should hike above 5% by early in the second quarter and then go on hold for a long time. Still, the Nasdaq keep a 0.5% gain pushed by the Tesla rally as investors took advantage of low valuations.
44 hours ago
US Consumer Credit Growth Beats ForecastsUnited States Consumer Credit
Total consumer credit in the US rose by $27.96 billion in November of 2022, after an upwardly revised $29.12 billion increase in the previous month but above market expectations of a $25 billion rise. On an annual basis, consumer credit was up by 7.1 percent in November after a 7.4 percent gain in the prior month. Revolving credit, like credit cards, surged 16.9 percent, compared to a 10.3 percent rise in the prior month. Nonrevolving credit, typically auto and student loans, increased by 3.9 percent, following a 6.5 percent gain in the prior month.
45 hours ago
Wall Street Pares Some GainsUnited States Stock Market
US stocks pared some gains on Monday, with the Dow Jones almost erasing a 200-point gain after hawkish comments from two Fed officials partially offset hopes that the Federal Reserve might dial back its aggressive monetary tightening. Fed Mary Daly said she expects the central bank to raise rates to somewhere above 5% and Fed Raphael Bostic noted that policymakers should hike above 5% by early in the second quarter and then go on hold for a long time. Still, the S&P 500 added more than 0.5% and the Nasdaq was 1.5% higher. On the corporate side, Bed Bath & Beyond jumped around 40% in another bout of extreme volatility ahead of the company's earnings report later this week. Bed Bath & Beyond warned last week that bankruptcy is likely due to a massive drop in sales.
46 hours ago
Madrid Stocks Snap 5-Day RallySpain Stock Market
The IBEX 35 index closed slightly below the flatline at 8,695 on Monday, on some profit-taking after five consecutive sessions of gains. Investors welcomed the positive news that came from China with new measures to de-escalate the COVID -19 restrictions but watched with concern the anti-democratic riots that occurred on Sunday in the capital of Brazil, given the exposure of some Spanish companies in the country to potential shocks. Meanwhile, this week's focus will be particularly on Fed Chairman Jerome Powell's speech on Tuesday and US consumer price data due on Thursday. Among single stocks, Endesa (-1.7%) was the worst performer, followed by Unicaja (-1.7%). On the opposite side, Solaria (+4.4%), IAG (+3.4%) and Melia Hotels (+2%) posted the biggest gains.
2 days ago
French Stocks End at Near 11-Month HighFrance Stock Market
The CAC 40 index rose about 0.7% to close at 6,907 on Monday, a level not seen since February last year, supported by the reopening of China and expectations of a moderation in the rate hike cycle by major central banks. Investors now await U.S. CPI data and quarterly results of big American banks due this week for more clues about the economic outlook. Domestically, Prime Minister Elisabeth Borne is set to announce the French government’s pension reform plans on Tuesday, most likely by raising the retirement age to 64 or 65 from 62 currently. On the corporate front, tech stocks and luxury companies were among the top performers, while Societe Generale fell 1.7%, the most in the index, followed by Renault (-1.5%) after Citi downgraded the automaker's stock from "buy" to "neutral."
2 days ago
FTSE 100 Rises for Fifth SessionUnited Kingdom Stock Market
Equities in London extended gains for the fifth consecutive session on Monday, with the benchmark FTSE 100 closing near record levels above 7,700 points, driven by real estate, materials, and energy stocks. The export-oriented index benefited from optimism surrounding China's reopening, with heavyweights mining and oil companies tracking higher commodity prices. On top of that, last week, weaker-than-expected ISM manufacturing and services data fuelled concerns about a US recession, which, coupled with a payrolls report showing slowing wage growth, prompted bets on a less aggressive tightening from the Federal Reserve. Regarding individual share price movement, Antofagasta rallied more than 4% to lead the FTSE 100, while Flutter Entertainment and Entain were among the top gainers, up 3.9% and 3.6%, respectively.
2 days ago
Milan Shares Rise to 10-Month HighItaly Stock Market
The FTSE MIB index extended early gains and closed 1% higher at 25,440 on Monday, the highest since late February 2022, tracking other European equity benchmarks with continued support from China’s economic reopening and hopes of eased monetary tightening in the United States after cooler wage growth. In the meantime, the domestic unemployment rate fell to its lowest since the labor supply shock at the start of the pandemic, while that of the Eurozone remained at a record low to underscore the European labor market’s resistance to aggressive tightening from the ECB. Policy-sensitive tech shares led the gains for a second session, up more than 5% on average with STMicroelectronics adding 5.4%. Luxury brands with exposure to China also closed in the green, with Ferrari adding 3.3%.
2 days ago
European Stocks Rise to Over 7-Month HighGermany Stock Market
European equity markets extended gains on Monday, with the benchmark Stoxx 600 rising 1% to 449, the highest since end-April, led by gains in technology stocks amid growing optimism over China's borders reopening and easing interest rate hike worries in the US following Friday's data showing a slowdown in wage growth. Domestically, the German DAX added 1.4% to 14,817, the highest since March. On the corporate front, drugmaker AstraZeneca agreed to buy US-based CinCor Pharma in a $1.8 billion deal to strengthen its pipeline of heart and kidney drugs, while Vodafone said it was set to cash in €1.7 billion from the sale of its Hungarian unit. Meanwhile, videogame stocks Frontier Developments and Devolver Digital posted disappointing trading updates and engineering contractor Keller warned its annual operating profit would come in below expectations after uncovering financial fraud at its Australia business.
2 days ago
South African Stocks Hit Record High on MondaySouth Africa Stock Market
The JSE FTSE All Share index surged about 1.9% to close at a record high of 78,343 on Monday, extending gains for the fifth straight session. Almost all sectors posted gains, led by tech stocks, tracking Tencent in Hong Kong, which influences the JSE via Naspers and Prosus, after the Chinese government indicated it could end its crackdown on the domestic tech sector. Financials, resource-linked shares and industrials also advanced firmly on enthusiasm about China reopening its borders and hopes the U.S. Federal Reserve may slow the pace of interest rate hikes. Locally, African National Congress (ANC) president Cyril Ramaphosa speaking at the party's annual 8 January birthday celebration on Sunday said that the party's renewal agenda, economic recovery, as well as basic service delivery were the top priorities. Investors now wait for the release of South Africa's manufacturing numbers due tomorrow for insights into the country's economic performance.
2 days ago
Russian Shares Start Week with GainsRussia Stock Market
The ruble-based MOEX Russia held most of its early gains and closed 0.3% higher at 2,164 on Monday, halting three consecutive sessions of declines amid marginally higher trading volumes as investors are back from Christmas festivities in Russia. Banks led the gains, with TCS Group and Sberbank adding 2% and 1%, respectively. Miners and metal producers also rose sharply, with Seligdar, Mechel, and Alrosa closing in the green. Further, shares from coal producers rebounded slightly from Friday’s slump due to Bloomberg's report that the federal government proposed a one-time tax payment for coal and fertilizer producers. In the meantime, oil shares continued to underperform and closed with marginal losses, as energy sanctions from the West and soaring taxes for energy exporters continue to threaten the sector’s outlook.
2 days ago
US Inflation Expectations Hit New 2021-LowUnited States Inflation Expectations
US consumer inflation expectations for the year ahead declined for a second month to 5% in December, the lowest level since July of 2021 and compared to 5.2% in November. Expectations declined by 0.7 percentage points for gas (to 4.1%) and food (to 7.6%), and 0.2 percentage points for college education (to 9.2%) and rent (to 9.6%). The median expected change in the cost of medical care, on the other hand, rose by 0.1 percentage points (to 9.7%). Also, home price growth expectations increased by 0.3 percentage points to 1.3%. Meanwhile, the medium-term inflation expectations remained at 3% percent, while the five-year-ahead measure increased to 2.4% from 2.3%. Furthermore, household spending expectations fell sharply to 5.9% from 6.9%, while income growth expectations rose to a new series high of 4.6%.
2 days ago
Silver Approaches 8-Month HighCommodity
Silver prices rose to near $24 per ounce, approaching the eight-month high of $24.1 per ounce touched on December 20th and tracking the strong momentum for bullion benchmarks amid signs of strong demand and looming threats of low supply. Slower-than-expected wage growth in the United States threw cold water on a batch of data pointing to a tight labor market, raising expectations that the Fed might not be as hawkish as previously signaled. Eased tightening also supported demand for silver as an industrial input for goods with high electricity conduction needs, reflected by the sharp rebound for solar energy equities. On the supply side, shortage concerns drove silver to outperform gold and palladium in 2022. COMEX inventories fell nearly 70% in the last 18 months to just over 1 million tonnes, and London Bullion Market Association stockpiles fell sharply amid outflows to India.
2 days ago
US Natural Gas Bounces Off One-Year LowCommodity
US natural gas futures jumped more than 10% to above $4/MMBtu on Monday, recovering from an over one-year low of $3.5 hit in the prior session on a spike in oil prices and forecasts for higher gas demand next week than previously expected. Still, the US benchmark is down more than 10% since the beginning of 2023, the worst start of a year ever, as milder weather has delayed the wintering heating season. Pressuring prices further, the Freeport LNG export plant in Texas, forced to go offline in June following a fire, again delayed the restart to the second half of January, leaving more supply on the domestic market.
2 days ago
Canadian Shares Start Week in the GreenCanada Stock Market
The S&P/TSX Composite index was 0.4% higher to approach the 20,000 mark on Monday, extending sharp gains from the prior week with further support from commodity-linked sectors. Energy shares jumped nearly 2% on average to lead the gains in Toronto, tracking the rebound in crude oil prices as investors assessed demand from top consumer China amid their economic reopening. Miners also hovered in the green, trading 0.7% higher as gold and base metal prices both advanced to multi-month highs. In the meantime, real estate developers edged higher after a Statistics Canada report showed that building permits soared by over 14% month-on-month in December, surprising market forecasts of a 0.1% drop.
2 days ago
European Stocks Hit Fresh 7-Month HighsGermany Stock Market
European shares extended gains to new seven-month highs Monday afternoon, as sentiment was boosted by an improved outlook for the global economy due to growing optimism over China's borders reopening and easing interest rate hike worries in the US following Friday's data showing a slowdown in wage growth. On the corporate front, drugmaker AstraZeneca agreed to buy US-based CinCor Pharma in a $1.8 billion deal to strengthen its pipeline of heart and kidney drugs, while Vodafone said it was set to cash in €1.7 billion from the sale of its Hungarian unit. Meanwhile, videogame stocks Frontier Developments and Devolver Digital posted disappointing trading updates and engineering contractor Keller warned its annual operating profit would come in below expectations after uncovering financial fraud at its Australia business. The pan-European STOXX 600 added 0.6% to 447 points and Germany's DAX 40 gained 1% to 14,750 points, with both indexes hitting the highest levels since early June.
2 days ago
Wall Street Enjoys Wave of MomentumUnited States Stock Market
The Dow added 200 points on Monday, while the S&P 500 and the Nasdaq 100 were up 1.2% and 2%, respectively, as hopes grew that the Federal Reserve might dial back its aggressive monetary tightening. Signs that inflation could be easing and concerns about an imminent recession prompted bets that the Federal Reserve would slow down the pace of interest-rate hikes in February and that it would even be cutting rates later this year. Adding to the cheaper mood was optimism around China's reopening after the world's second-largest economy announced more financial aid to households and companies to shore up growth while moving away from a strict Covid-Zero policy. On the corporate side, Bed Bath & Beyond jumped around 40% in another bout of extreme volatility ahead of the company's earnings report later this week. Bed Bath & Beyond warned last week that bankruptcy is likely due to a massive drop in sales.
2 days ago
Baltic Exchange Dry Index Breaks 6-Day Losing RunCommodity
The Baltic Exchange's dry bulk sea freight index, which measures the cost of shipping goods worldwide, rose about 0.8% to 1,139 points on Monday, snapping a six-session losing streak that sent the index to the lowest in four months. The capesize index, which tracks iron ore and coal cargos of 150,000 tonnes, advanced by 5.6% to 1,596 points, after China's state planner has allowed three central government-backed utilities and its top steelmaker to resume coal imports from Australia, the first such move since Beijing imposed an unofficial ban on coal trade with Canberra in 2020. Meanwhile, the panamax index, which tracks about 60,000 to 70,000 tonnes of coal and grains cargoes, was down for the 11th consecutive day, slipping 3.8% to a four-month low of 1,250 points; and the smaller supramax index fell 14 points to its lowest in two and a half years to 825 points.
2 days ago
Lithium Extends Downturn to 3-Month LowCommodity
Lithium carbonate prices in China fell to CNY 502,500 per tonne in January, the lowest since late September, as stronger supply and expectations of lower demand drove industry players to project that the lithium market will return to a surplus this year. Soaring Covid cases in China and the consequent slowdown in its economy are expected to cool the surges in electric vehicle sales ahead of the next year. Meanwhile, Chinese authorities are set to cancel new energy subsidies for battery manufacturers this month, significantly driving down demand for the key input material. On the supply side, top producer Australia expects global output of lithium carbonate equivalent production to total 915,000 tonnes next year, a 32% rise from 2022’s estimate, while foreign sales are set to triple from the prior year. Still, decarbonization goals and a wave of electric vehicle sales drove lithium prices to nearly double in 2022.
2 days ago
Dollar Hovers Near Seven-Month LowsUnited States Currency
The dollar weakened sharply against a basket of major currencies on Monday, testing the 103 mark for the first time since last June amid prospects that the Federal Reserve could soon slow down the pace of its monetary policy tightening. Last week, weaker-than-expected ISM manufacturing and services data fuelled concerns about a recession, which, combined with the payrolls report showing slowing wage growth, paved the way for a less aggressive tightening stance from the US central bank. Now, all eyes are on the CPI report, due on Thursday, for further clues about the Fed's next move. The dollar weakened across the board, with the most pronounced selling activity against risk-sensitive currencies such as the Australian and New Zealand dollars.
2 days ago
Brazilian Equities VolatileBrazil Stock Market
Brazil’s Ibovespa stock index swung between small gains and losses after a negative start on Monday, with investors weighing the effects of the weekend's institutional attacks by supporters of former President Jair Bolsonaro and ongoing protests. Meanwhile, concerns about the country's fiscal health persist, although President Luiz Inacio Lula da Silva said on Friday it was possible for Brazil to develop responsibly. On the economic front, Brazil's financial market downgraded the country's economic growth forecasts for this year and the next, from 3.04% to 3.03% for 2022, and from 0.80% to 0.78% for 2023. Inflation forecasts were kept at 5.62% for 2022, but raised to 5.36% from 3.70% for 2023 and to 5.31% from 3.65% for 2024. Among single stocks, 3R Petroleum was leading the gains, followed by Embraer (+2.8%), Petrorio (+2.7%), and Gerdau (+1.8%). On the other hand, the top losers were Hapvida (-3%), Eztec (-2.6%), Grupo Soma (-2.2%) and Cyrela (-2%).
2 days ago
Brazilian Real Weakens on Political TurmoilBrazil Currency
The Brazilian real depreciated more than 1% against the dollar on Monday, testing the $5.3 level amid mounting worries about the security of Brazil’s political and judicial institutions after supporters of former President Jair Bolsonaro stormed the Congress, supreme court, and the presidential palace. At the same time, investors remained worried about Brazil’s fiscal health since President Lula da Silva took office earlier this year. The recently sworn-in President criticized the country’s budgetary rules and spending caps shortly before signing a provisional measure that guarantees BRL 600 in a monthly aid program, extending the national tax break on fuel and removing state-backed giants from privatization programs. Still, the real ended 2022 as one of the top-performing emerging market currencies amid a series of interest rate hikes by the central bank and an upbeat growth outlook.
2 days ago
Luxembourg Inflation Rate Down to Near 1-Year LowLuxembourg Inflation Rate
Annual inflation rate in Luxembourg fell to 5.4% in December of 2022 from 5.9% in November, hitting the lowest since January of 2022, due to an easing in prices of petroleum products. Transport cost rose at a slower 6.2% vs 8.1% in the previous month. Inflation also eased for housing and utilities (6.1% vs 6.3%). On the other hand, prices rose faster for food and non-alcoholic beverages (10.9% vs 10.4%) and clothing and footwear (4.6% vs 4.2%). Compared to the previous month, the CPI fell 0.6%, the biggest drop since February 2021, with diesel prices sinking 11.5% and gasoline 12.3%.
2 days ago
Albania Inflation Rate at 6-Month LowAlbania Inflation Rate
The annual inflation rate in Albania decreased to 7.4 percent in December of 2022, the lowest in six months, from 7.9 percent in the previous month. Cost slowed for food and non-alcoholic beverages (14.2 percent vs 14.7 percent in November); housing, water, electricity, gas and other fuels (2.8 percent vs 3.1 percent); transport (6 percent vs 9.6 percent); alcoholic beverages and tobacco (5.5 percent vs 5.8 percent); health (1.1 percent vs 1.3 percent); Hotels, coffee-houses and restaurants (5.2 percent vs 6.1 percent); and miscellaneous goods and services (3.3 percent vs 3.6 percent). On a monthly basis, consumer prices went up 0.4 percent, after a 0.3 percent decrease in November.
2 days ago
Canadian Building Permits Soar in NovemberCanada Building Permits
The total value of building permits in Canada soared by 14.1% from the previous month to CAD 11.03 billion in November of 2022, rebounding from the upwardly revised 5.3% decline in the corresponding period of the previous month and surprising markets that expected a 0.1% drop. Residential permits rose by 13.7%, supported by both multiple (19%) and single (7.1%) units. In the meantime, the value of non-residential permits rose by 14.9%, as sharp advances for those of industrial (32.4%) and institutional (40.6%) buildings offset the slight decrease for commercial units (-0.6%).
2 days ago
Macedonia Inflation Slows for 2nd Month in DecemberMacedonia Inflation Rate
The annual inflation rate in Macedonia was at 14.2 percent in December of 2022, retreating sharply from 19.5 percent in the prior month and extending the slowdown from the record-high 19.8 percent in October. It was the lowest rate of price growth in seven months, as inflation fell for food and non-alcoholic beverages (20.9 percent vs 29.8 percent), housing and utilities (13.3 percent vs 20 percent), and restaurants and hotels (15.5 percent vs 21.3 percent). On the other hand, prices accelerated for transportation (19.5 percent vs 16.5 percent). On a monthly basis, consumer prices fell by 0.2 percent, the first monthly decline since September 2021.
2 days ago
Chile Posts Widest Trade Surplus in Nearly 2 YearsChile Balance of Trade
Chile’s trade surplus jumped to USD 1,846 million in December of 2022 from USD 417 million in the same month of the previous year. This was the largest monthly trade surplus since April of 2021, as imports tumbled 17.7% year-on-year to USD 7.048 million, on lower acquisitions of consumer goods (-31.7%); intermediate goods (-16.9%) and capital goods (-8.6%). Meanwhile, exports fell 1% to USD 8.895 million, dragged down by mining products (-0.2%), of which copper (-13.2%); agricultural goods (-4.2%) and industrial products (-1.7%).
2 days ago
Wall Street Set to Open HigherUnited States Stock Market
US stock futures tracking the broader market were up roughly 0.5% on Monday, putting Wall Street on track to start the week higher as hopes grew that the Federal Reserve might dial back it's aggressive monetary tightening. Signs that inflation could be easing and concerns about an imminent recession prompted bets that the Federal Reserve would slow down the pace of interest-rate hikes in February and that it would even be cutting rates later this year. Adding to the cheaper mood was optimism around China's reopening after the world's second-largest economy announced more financial aid to households and companies to shore up growth while moving away from a strict Covid-Zero policy. On the corporate side, Bed Bath & Beyond jumped roughly 20% in premarket trading in another bout of extreme volatility after the WSJ reported that the company was preparing to file for bankruptcy within weeks.
2 days ago
Ireland Industrial Production Eases in NovemberIreland Industrial Production
Industrial production in Ireland jumped by 35.3 percent from the previous year in November of 2022, remaining well above the series average but easing from the upwardly revised 57.3 percent in the prior month. Manufacturing output jumped by 36.6 percent in the period, lifted by metals and fabricated metal products (21.1 percent), paper and paper products (40.3 percent), and textiles (19.8 percent). Output was also higher for electricity, gas, steam, and air conditioning supply (18.4 percent). On a monthly basis, industrial output rose by 6.4 percent, rebounding from the 8.7 percent contraction in October.
2 days ago
Cyprus Trade Gap Widens in NovemberCyprus Balance of Trade
The trade deficit in Cyprus widened to EUR 666 million in November 2022 from EUR 567 million in the same month last year, a preliminary estimate showed. Imports rose by 5 percent to EUR 983.5 million, as purchases were up by 9.5 percent from the EU. However, imports from non-EU countries went down by 0.9 percent. On the other hand, exports declined by 14.2 percent to EUR 317.3 million, as sales decreased in both EU countries (24 percent) and non-EU countries (10.4 percent). From January to November, the trade gap widened to EUR 6.8 billion from EUR 4.9 billion in the same period of 2021.
2 days ago
US 10-Year Treasury Yield Consolidates Around 3.5%United States Government Bond 10Y
The US 10-year Treasury note yield, seen as a proxy for global borrowing costs, consolidated around 3.5%, as signs of an imminent recession in the US and prospects of a less aggressive monetary tightening from the Federal Reserve lifted appetite for government debt. Data from the Institute for Supply Management showed a contraction in December in US manufacturing and services activity. At the same time, the Labor Department's closely watched employment report showed that nonfarm payrolls grew by 223K, the least since December 2020, while average hourly earnings slowed more than expected. Now, all eyes are on the CPI report, due on Thursday, for hints on how much further the Federal Reserve may tighten financial conditions as it seeks to cool an overheating economy. Money markets are betting that the US central bank will hike rates by 25 basis points in February 2023.
2 days ago
Mexico Inflation Rate Close to 6-Month LowsMexico Inflation Rate
Mexico’s annual inflation rate rose marginally to 7.82% in December of 2022, from 7.80% in the prior month, but holding close to six-month lows and below market forecasts of 7.86%. Prices increased slightly faster for food & non-alcoholic beverages (12.70% vs 12.41% in November); housing & utilities (2.26% vs 1.38%) and health (6.50% vs 6.33%). Meanwhile, there was a slowdown in prices of other CPI items such as alcoholic beverages & tobacco (9.02% vs 9.27%); furnishings & household equipment (8.21% vs 8.63%); transportation (6.52% vs 7.74%); recreation & culture (4.68% vs 5.50%) and clothing & footwear (6% vs 6.74%). The annual core inflation rate eased to 8.35% from an over 22-year high of 8.51% in the prior month and roughly in line with market expectations of 8.36%. On a monthly basis, consumer prices rose by 0.38% in December, the least in seven months and under market estimates of a 0.43% increase.
2 days ago
Portugal Trade Gap Widens in NovemberPortugal Balance of Trade
Portugal's trade deficit widened to EUR 2.4 billion in November 2022 from EUR 2.2 billion in the same month last year. Exports increased 18.9 percent from a year earlier to EUR 7,204 billion, mainly to sales of transport equipment (22.2 percent, primarily to the United Kingdom and Italy), capital goods & parts thereof (30.9 percent, mainly to Spain), and fuels & lubricants (100.4 percent), mostly towards Extra-EU markets. Meanwhile, imports rose 16.2 percent to EUR 9,637 billion, driven by purchases of transport equipment (35.6 percent), mainly from Canada and Spain, and fuels & lubricants (36.0 percent), mainly from Extra-EU suppliers.
2 days ago
Stocks in France Highest Since February 2022France Stock Market
The CAC 40 traded little changed at 6860 on Monday, holding around levels not seen since February last year, and tracking a global increase in investors' optimism after China reopened its borders during the weekend. Investors now await U.S. CPI data due this week for more clues regarding the pace of rate hikes. Domestically, France's trade gap widened to EUR 13.8 billion in November from EUR 11.6 billion in the previous month. Also, Prime Minister Elisabeth Borne will announce on Tuesday plans to make the French work longer, most likely by raising the retirement age to 64 or 65 from 62 currently. According to the Organisation for Economic Cooperation and Development, France is one of the lowest retirement ages in the industrialised world and spends more than most other countries on pensions at nearly 14% of economic output. Among single stocks, Dassault Systemes (-1.6%) posted the biggest loss; while Eurofins Scientifique (+2.3%) and Carrefour (+2%) were the top performers.
2 days ago
Sensex Starts Week on a Bright NoteIndia Stock Market
The BSE Sensex closed 850 points higher at 60,750 on Monday, nearly erasing last week’s slump and tracking the rally in Wall Street on Friday as slower wage growth and unexpected contraction in US services activity eased concerns of overtightening by the Federal Reserve. Policy-sensitive sectors booked the sharpest gains in the session, with Mahindra & Mahindra adding 3.7% to lead the auto manufacturers and HCL Technologies jumping 3.1% to set the pace for tech companies. Higher risk sentiment was also contributed by China’s economic reopening, lifting demand for Asian equities. At the same time, TCS closed 3.2% higher as investors expect strong corporate results from the consultant to be released after the closing bell.
2 days ago
Malta Trade Deficit Narrows in NovemberMalta Balance of Trade
The trade deficit in Malta narrowed to EUR 331.9 million in November of 2022 from EUR 356.5 million in the same month of the previous year. Exports advanced by 37.2% to EUR 453.4 million, amid higher shipments of miscellaneous transactions and commodities (483.8%), crude materials (371.1%), food products (61.5%) and beverages & tobacco (70.5%). At the same time, imports rose by 14.3% to EUR 785.3 million, as arrivals mainly grew in miscellaneous transactions and commodities (129.7%), chemicals (27.4%) and crude materials (22.3%). Considering the January-November period, the trade deficit widened to EUR 4,361 million, from EUR 2,795.7 million in the same months of 2021.
2 days ago
Greece Trade Deficit Widens in NovemberGreece Balance of Trade
Greece’s trade deficit widened to EUR 3.75 billion in November of 2022 from EUR 2.94 billion in the same month a year ago. Imports surged by 23.5% year-on-year to EUR 8.49 billion, boosted by purchases from the non-EU countries (40.9%) and the EU (4.6%). At the same time, exports rose 20.4% to EUR 4.74 billion, driven by shipments to the EU (36.9%) and non-EU countries (2.3%). Considering the first eleven months of 2022, the country’s trade deficit increased by 58.6% to EUR 85.3 billion, with imports and exports rising by 45.6% and 37.7%, respectively.
2 days ago
The SENSEX Index increased 1.41%India Stock Market
In Mumbai the SENSEX Index went up by 847 points or 1.41 percent on Monday. The rise was driven by Mahindra & Mahindra (3.68%), TCS (3.19%) and Hcl Technologies (3.12%).
2 days ago
Iron Ore Rallies to 5-Month HighCommodity
Prices for iron ore cargoes with a 63.5% iron ore content for delivery into Tianjin rose above $118 per tonne in January, the highest since August, amid expectations of stronger demand. In further actions to move past its strict zero Covid policy, China reopened the border between its mainland and Hong Kong and raised hopes of higher economic activity for the world’s top consumer. On top of that, commercial banks agreed to extend $162 billion in new credit lines for private developers and authorities lifted a ban on equity refinancing for firms in the sector, while the PBoC continuously injected liquidity into the economy. Still, the metal’s recent rally drove China’s state planner to pledge closer monitoring and producers’ efforts on malicious price regulation, limiting further increases.
2 days ago
Sri Lanka Trade Gap Shrinks in NovemberSri Lanka Balance of Trade
Sri Lanka’s trade deficit shrank to USD 450 million in November 2022 from USD 553 million in the corresponding month of the previous year. Exports fell by 17.9% to USD 994 million, as sales dropped in all categories namely, industrial products (-15.4%), agricultural products (-25.9%), mineral products (-50.5%) and unclassified goods (-36.5%). Meanwhile, imports decreased by 18.1%, driven by lower purchases of consumer goods (-27.2%), intermediate goods (-0.5%), investment products (-51.7%) and unclassified imports (-96.9%). For the first eleven months of the year, the country’s trade deficit shrank to USD 4,839, compared to USD 7,054 in the same period of 2021.
2 days ago
Eurozone Jobless Rate Holds at Record LowEuro Area Unemployment Rate
The Euro Area seasonally-adjusted unemployment rate stood at 6.5 percent in November 2022, unchanged from the previous month's all-time low and down from 7.1 percent in the same month last year. The number of unemployed decreased by 2 thousand from a month earlier to 10.849 million, the lowest level since comparable records began in 1995. Meanwhile, the youth unemployment rate, measuring job-seekers under 25 years old, edged up to 15.1 percent in November, from 15.0 percent in the previous month. Amongst the largest Euro Area economies, the highest jobless rates were recorded in Spain (12.4 percent), Italy (7.8 percent) and France (7.0 percent), while the lowest rates were recorded in the Netherlands (3.6 percent) and Germany (3.0 percent).
2 days ago
Russian Shares Rebound on MondayRussia Stock Market
The ruble-based MOEX Russia index was 0.5% higher to hover above 2,165 on Monday, rebounding from three consecutive sessions of declines with support from banks and metallurgists amid marginally higher trading volumes after Christmas festivities in Russia. Miners and metal producers led the gains, with Seligdar, Alrosa, and Polymetal sharply in the green as the economic reopening in neighboring China lifted base metal prices. In the meantime, NLMK booked gains following three sessions of losses, due to shareholders’ refusal of the dividend amounts for the first three quarters of 2022. Coal shares also rebounded slightly from Friday’s slump after Bloomberg reported that the federal government proposed a one-time tax payment for coal and fertilizer producers. In the meantime, oil shares continued to underperform and traded flat.
2 days ago
Oil Rallies on Demand OptimismCommodity
Brent crude futures rose more than 3% to above $81 per barrel on Monday, rebounding further from a nearly one-month low of $77.6 touched last week, on hopes for a recovery in demand from China and the prospect of a less aggressive monetary tightening from the Federal Reserve. The world's second-largest economy and top crude importer, China, announced more financial support to households and companies to shore up growth after the nation ended its Covid-Zero policy. In the meantime, a slowdown in wage growth and a surprise contraction in services activity in the US tempered expectations that the Fed will continue to hike rates aggressively. On the supply side, OPEC crude production rose in December, led by a recovery in Nigerian supply, despite the cartel's agreement to cut output to support the market.
2 days ago
South African Stocks Hit Record HighSouth Africa Stock Market
The JSE FTSE All Share index surged over 2% to trade above the 78,580 level on Monday, the highest on record, mainly pushed up by tech stocks, tracking Asia and Tencent, which influences the JSE via Naspers and Prosus, after the Chinese government indicated it could end its crackdown on the domestic tech sector. Resource-linked shares and industrials were also advancing firmly amid optimism around the reopening of the world’s second-largest economy. At the same time, hopes of a less aggressive monetary policy stance by the Federal Reserve continued to support market sentiment.
2 days ago
Czech Republic Forex Reserves Largest in 4 MonthsCzech Republic Foreign Exchange Reserves
Foreign exchange reserves in the Czech Republic increased to $141.01 billion in December of 2022, from $135.07 billion in the previous month. It was the highest record since August of 2022, as increases were seen in foreign currency reserves ($135.43 billion vs $129.44 billion), IMF reserve position ($0.75 billion vs $0.74 billion), SDRs ($3.39 billion vs $3.35 billion) gold reserves ($0.70 billion vs $0.68 billion). Meanwhile, other reserve assets decreased ($0.74 billion vs $0.87 billion).
2 days ago
Czech Jobless Rate Highest in 19 MonthsCzech Republic Unemployment Rate
The Czech unemployment rate rose to 3.7 percent in December 2022, from 3.5 percent in November and slightly below market estimates of 3.8 percent. It was the highest level since May 2021, as the number of job seekers increased by 14,616 to 271,803 over the previous month and rose by 13,360 compared to the same month last year. Meanwhile, the number of job vacancies fell by 3,323 from a month earlier to 288,647, and dropped by 54,501 year-on-year.
2 days ago
Euro Edges Higher on the 2nd Week of JanuaryEuro Area Currency
The euro edged higher to $1.07 in the second week of January, getting back to seven-month highs, benefitting from a softer dollar, after fresh economic data for the US including the December jobs report raised bets the Fed will deliver smaller rate increases. In Europe meanwhile, price pressures eased more than expected, with the annual inflation rate in the Eurozone hitting a four-month low. However, excluding energy, inflation continues to hold at record levels. The ECB is unlikely to change the ECB monetary policy path for now, with another increase in borrowing cost expected next month. However, some Governing Council members including Mario Centeno and Francois Villeroy de Galhau have been signalling the peak rate might be close.
2 days ago
Italy Unemployment Rate at Over 2-1/2-Year LowItaly Unemployment Rate
The unemployment rate in Italy fell to 7.8 percent in November of 2022 from the upwardly revised 7.9 percent in the previous month. It was the lowest since the pandemic-induced shock in the labor force in April of 2020, as the number of unemployed individuals fell by 16 thousand to 1.96 million, offsetting the 27 thousand decrease in employed individuals to 23.12 million. Meanwhile, the labor force participation rate ticked down by 0.1 percentage point to 65.5 percent. The youth unemployment rate, measuring job-seekers between 15 and 24 years old, fell to 23 percent from 23.6 percent in the previous month.
2 days ago
Italian Stocks Rise to Over 9-Month HighItaly Stock Market
The FTSE MIB index was trading above the 25,300 level on Monday, the highest since late March of 2022, outperforming its regional peers. Market sentiment was supported by optimism around the reopening of the Chinese economy and hopes of less tightening by the US Federal Reserve. On the domestic data front, Italy's jobless rate fell to an over 2-1/2-year low of 7.8% in November. Among single stocks, Telecom Italia was leading the gains in Milan, up nearly 6%, followed by Saipem (+3.9%) and Ferrari (+2.8%). By contrast, the biggest losses were posted by Erg (-2.3%) and Italgas (-1.1%). In corporate news, carmaker Stellantis announced it has signed a deal with Australian miner Element 25 for the supply of manganese sulphite for batteries for its electric vehicles (EVs).
2 days ago
Palm Oil Hovers Near One-Month PeakCommodity
Malaysian palm oil futures were trading near the MYR 4,100 per tonne mark, not far from a one-month high of roughly MYR 4,300 hit on January 3rd, amid expectations of lower production and tighter global supplies. Indonesia, the world's biggest palm oil producer, announced that palm oil producers can now export only six times the domestic sales requirement as it wants to ensure ample domestic supplies. At the same time, Indonesian officials anticipated weaker seasonal production in Q1 of 2023 while extending a policy to allow imports of vegetable oils such as palm oils. Domestically, production declined for a second month in December as unfavorable weather disrupted harvesting from the world's second-largest producer. Keeping a lid on prices were prospects of weak export demand from Malaysia, with shipments in December down 1% from the prior month, with cargo surveyors pointing to a slump in shipments to top consumer China.
2 days ago
Singapore Forex Reserves Fall in DecemberSingapore Foreign Exchange Reserves
Foreign exchange reserves in Singapore declined to SGD 388.3 billion in December of 2022 from SGD 399.1 billion in the prior month, mainly due to a decrease in gold and foreign exchange (SGD 377.7 billion vs SGD 388.5 billion in November). In December of 2021, the reserves stood at SGD 563.3 billion.
2 days ago
Steel Rises to 4-Month HighCommodity
Steel rebar futures rose past CNY 4,020 per tonne in January, the highest since late August, supported by signs of higher demand for industrial and construction inputs from the world’s top economies. Chinese authorities opened the country’s mainland border with Hong Kong and halted quarantine requirements for incoming travelers, cementing China’s move away from its strict zero Covid policy and raising expectations of higher economic activity. To ramp up demand in recent weeks, the PBoC injected CNY 85 billion via reverse repos to support liquidity and banks agreed to extend $162 billion in new credit lines for private developers. In the meantime, slower-than-expected wage growth from the US jobs report eased bets on how long the Fed will hold its terminal rate, further supporting prices.
2 days ago
Slovakia Trade Deficit Widens in NovemberSlovakia Balance of Trade
Slovakia’s trade deficit widened sharply to EUR 823.5 million in November of 2022 from EUR 20.2 million in the corresponding month of the previous year. Imports surged 20.5% to EUR 10.4 billion, primarily led by purchases of mineral fuels which include imports of natural gas, oil and electricity. At the same time, exports increased 11.2% to EUR 9.6 billion, mainly underpinned by sales of machinery and equipment, particularly automobiles. Considering the first eleven months of 2022, the country’s trade balance shifted to a deficit of EUR 3.2 billion from a surplus of EUR 2.1 billion in the same period of 2021.
2 days ago
Asian Shares Rise as China ReopensSouth Korea Stock Market
Stocks in Asia were in the green to kick off the second week of January, after China reopened its borders after three years of covid-related restrictions. Incoming travellers will no longer need to quarantine. The move by the Chinese authorities during the weekend lifted investors' sentiment, while increasing bets the Fed will deliver slower rate hikes following the last jobs reports and a weak ISM Services PMI reading also boosted the risk-on mood. The Kospi was the top performing stock index in the Asia-Pacific region, up by 2.6% to close at 2350, followed by the Hang Seng (1.9% to 21388), the Shanghai Composite (0.6% to 3176) and the ASX 200 (0.6% to 7151). Markets in Japan were closed for the Coming of Age Day holiday.
2 days ago
Czech Republic GDP Contraction Confirmed at 0.2% in Q3Czech Republic GDP Growth Rate
The Czech Republic's quarterly economic contraction was confirmed at 0.2% in the third quarter of 2022, following a downwardly revised 0.3% rise in the previous period. It was the first GDP decline since the first quarter of 2021 as soaring inflation and tighter financing conditions hit household consumption (-3.2% vs -0.1% in Q2). Additionally, fixed investment shrank for the first time in eight quarters (-0.3% vs 1.2%) and government spending continued to decrease (-1.3% vs -0.3%). On the external front, exports (4.7% vs 1% in Q2) rose more than imports (2.7% vs 0.9% in Q2). On an annual basis, the GDP expanded by 1.5%, slightly below the preliminary estimate of 1.7% but slowing sharply from a downwardly revised 3.5% growth in the previous three-month period.
2 days ago
France Current Account Widens in NovemberFrance Current Account
France’s current account deficit widened to EUR 6.8 billion in November 2022, from a downwardly revised EUR 3.4 billion in the previous month, due to the deterioration in the goods shortfall (EUR 11.8 billion vs EUR 9.9 billion in October). On the other hand, the surplus in primary and secondary income grew marginally to EUR 2.6 billion from EUR 2.5 billion, while the surplus for services account narrowed sharply to EUR 2.4 billion, compared to EUR 4 billion a month earlier.
2 days ago
FTSE 100 Hovers Near Record LevelsUnited Kingdom Stock Market
Equities in London extended gains for the fifth consecutive session on Monday, with the benchmark FTSE 100 hovering near record levels above 7,700, driven by real estate, materials, and energy stocks. The export-oriented index benefited from optimism surrounding China's reopening, with heavyweights mining and oil companies tracking higher commodity prices. On top of that, last week, weaker-than-expected ISM manufacturing and services data fuelled concerns about a US recession, which, coupled with a payrolls report showing slowing wage growth, prompted bets on a less aggressive tightening from the Federal Reserve. Regarding individual share price movement, BT Group rallied almost 3% to lead the FTSE 100, while Antofagasta and Glencore were among the top gainers, up roughly 1.5% each.
2 days ago
Austria Trade Gap Widens in OctoberAustria Balance of Trade
Austria posted a trade deficit of EUR 1,894 million in October of 2022, compared with EUR 1,494 million shortfall in the corresponding month of the previous year. Imports grew by 17.5 percent year-on-year to EUR 18,518 million, as purchases advanced in both non-EU countries (25.4 percent) and EU countries (13.4 percent). On the other hand, exports increased by 16.3 percent to EUR 16,624 million, as sales to EU countries grew 18.5 percent and to those countries outside EU surged 15.3 percent. Considering the January to October period, the trade deficit widened to EUR 15,999 million.
2 days ago
Copper Rises to Over 6-Month HighCommodity
Copper futures approached the $4 per pound mark in early January, the highest since June, supported by expectations of stronger demand and looming supply concerns. Chinese authorities reopened mainland borders with Hong Kong and relaxed quarantine for incoming travelers, further moving away from its strict zero Covid policy and raising expectations of higher economic activity and increased in demand for industrial inputs. On the supply side, production in top producer Chile fell nearly 7% year-on-year in November. Commodity trader Trafigura warned that global copper stocks have fallen to record lows, with current inventories being enough to supply world consumption for just 4.9 days. Also, mining giant Glencore estimated a supply shortfall of 50 million tonnes in 2023.
2 days ago
Hong Kong Stocks Extend Bullish MomentumHong Kong Stock Market
The Hang Seng surged 396.70 points or 1.89% to finish at 21,388.34 on Monday, its highest close since early July of 2022, continuing last week's upside drive, as a full reopening of the Chinese economy over the weekend raised expectations of a robust global recovery this year. Traders also welcomed remarks from China's central bank officials that policymakers will ramp up support to boost income and spur household consumption while easing a crackdown on tech companies. Meantime, Goldman Sachs and Morgan Stanley have upgraded their views on a slew of big tech names in China. In the US, equities last week saw their first rally of the new trading year, as expectations built that the Fed's tightening policy could ease following signs of a slowing economy. All sectors ended in the green, amid sharp gains from tech, consumers, industrials, and financials. Alibaba Hlds. soared 8.1%, followed by Xiaomi Co (7.3%), Galaxy Ent. (3.6%), Meituan (3.3%), Wuxi Biologics (2.5%), and KE Holdings (8%).
2 days ago
European Shares Hit 7-Month HighsGermany Stock Market
European stock markets started the second week of 2023 higher, with the pan-European STOXX 600 adding 0.4% to 444 points and Germany's DAX 40 rising 0.3% to 14,630 points, the highest levels since early June. The sentiment was boosted by growing optimism over China's reopening and easing interest rate hike worries in the US following Friday's data showing a slowdown in US wage growth. On the corporate front, UK drugmaker AstraZeneca agreed to buy US-based CinCor Pharma in a $1.8 billion deal to strengthen its pipeline of heart and kidney drugs, while Vodafone said it was set to cash in €1.7 billion from the sale of its Hungarian unit. Meanwhile, videogame stocks Frontier Developments and Devolver Digital posted disappointing trading updates and engineering contractor Keller reported a financial reporting fraud in its Austral Business unit in Australia. On the economic data front, Germany's industrial output growth in November slightly beat market forecasts.
2 days ago
Natural Gas Prices in Europe at Pre-War LevelCommodity
European natural gas prices were at pre-Ukraine war levels of €70/MWh in mid-January, down nearly 50% from their December peak and a fifth of records levels set in August, as warmer-than-expected temperatures eased concerns over shortages and the need for gas rationing. Yet, Europe is set for the warmest January in years. At the same time, record LNG imports, a rise in renewable capacity, namely from wind power in Germany, lower consumption and energy-saving measures helped to keep storages full. Gas storages across Europe are 83.2% full as of January 7th, well above the five-year seasonal norm of 70%. In Germany, storage facilities are about 91% full. Still, the outlook for 2023 remains challenging as the winter season is far from over. Also, Europe needs to increase its LNG import capacity while a rise in gas demand from China and other Asian countries could increase competition in the LNG market.
2 days ago
France Trade Deficit Widens in NovemberFrance Balance of Trade
France's trade deficit widened to EUR 13.8 billion in November of 2022 from EUR 11.6 billion in the previous month. Imports rose by 2.3 percent to EUR 64.8 billion. Meanwhile, exports went down 1.4 percent month-over-month to EUR 51 billion, on reduced sales of capital goods, while stable for consumer goods. The energy gap slightly narrowed to EUR 8.4 billion from EUR 8.7 billion in October. Excluding energy, the trade deficit went up to EUR 7.6 billion from EUR 5.1 billion.
2 days ago
Hungary Industrial Output Growth at 13-Month LowHungary Industrial Production
Industrial production in Hungary eased sharply to 0.5% year-on-year in November 2022, following a 5.9% rise in October and well below market forecasts of a 4.3% growth, preliminary estimates showed. It was the smallest increase since October 2021, as production dropped in the majority of manufacturing subsections namely, manufacture of computer, electronic & optical products and food, beverages & tobacco products. On the other hand, the manufacture of transport equipment and electrical equipment grew significantly. Considering January-November, production was 6% higher compared to the same period of 2021, but 0.7% lower over the previous month.
2 days ago
Danish Current Account Surplus at 6-Month LowDenmark Current Account
Denmark's current account surplus fell to DKK 31.8 billion in November 2022 in a seasonally adjusted terms from DKK 33.2 billion in the prior month. It was the smallest current account surplus since May, as the services surplus dropped to DKK 15.3 billion from DKK 18.6 billion in October. On the other hand, the goods surplus increased to DKK 10.4 billion from DKK 8.6 billion a month earlier. In addition, the primary income surplus edged up to DKK 9.2 billion from DKK 9.1 billion in October, while the secondary income deficit was down to DKK 3.1 billion from DKK 3.2 billion. Considering the first eleven months of 2022, the current account surplus widened to DKK 343.7 billion.
2 days ago
Hungary Trade Gap Above Expectations in NovemberHungary Balance of Trade
The trade deficit in Hungary jumped to EUR 1,283 million in November of 2022, widening sharply from EUR 41 million in the same month a year earlier and above market estimates of a EUR 653 million shortfall, preliminary estimates showed. Imports climbed by 29% year-on-year to EUR 14,415 million while exports rose at a slower 18% to EUR 13,132 million.
2 days ago
The Shangai Composite Index went up by 0.58%China Stock Market
In China the Shangai Composite Index gained 18 points or 0.58 percent on Monday. Gains were led by Zijin Mining Group (9.68%), Nari Tech Develop (5.17%) and China Molybdenum (4.76%). Biggest losers were Huaneng (-4.34%), GD Power Development (-3.46%) and Avic Aviation Engine (-3.25%).
2 days ago
Lithuania Inflation Rate Eases to 5-Month LowLithuania Inflation Rate
Lithuania’s annual inflation rate eased to 21.7 percent in December of 2022, from 22.9 percent in the previous month. It was the weakest inflation rate since July of 2022, as prices increased at a slower pace for food & non-alcoholic beverages (34.7 percent vs 35.6 percent), housing utilities (48.3 percent vs 55.7 percent), and transport (14.1 percent vs 18.2 percent). Meanwhile, costs picked up for alcoholic beverages & tobacco products (12.4 percent vs 10.4 percent), clothing & footwear (5.7 percent vs 5.6 percent), furnishings, household equipment & routine maintenance (15.1 percent vs 14.2 percent), and hotels & restaurants (20.2 percent vs 19.1 percent). On a monthly basis, consumer prices edged down to 0.3 percent in December, from 0.4 percent in November.
2 days ago
Denmark Trade Surplus Smallest in 7 MonthsDenmark Balance of Trade
Denmark’s goods and services trade surplus narrowed to a seasonally adjusted DKK 25.6 billion in November 2022, from a downwardly revised DKK 27.2 billion in the previous month. It was the smallest trade surplus since April, as exports dropped by 1.8 percent to DKK 156.9 billion, while imports fell at a softer 0.9 percent to DKK 131.3 billion. Considering January-November, the country registered a trade surplus of DKK 281 billion, compared to DKK 164.5 billion in the corresponding period of 2021.
2 days ago
Lithuania Trade Gap Widens in NovemberLithuania Balance of Trade
Lithuania’s trade deficit widened to EUR 0.47 billion in November 2022 from EUR 0.32 billion in the same period a year earlier. Imports surged by 19.3% to EUR 4.4 billion, mainly boosted by mineral fuel, mineral oils and their distillation products (53.2%), vehicles (45.7%) and fertilizer (93.3%). Meanwhile, exports increased at a slower 16.6% to EUR 3.6 billion, mainly driven by demand of mineral fuel, mineral oils and their distillation products (65.3%), vehicles (96.1%) and cereals (39.9%). Considering January to October of the year, the trade deficit widened sharply to EUR 7.4 billion from EUR 2.8 billion in the same period of 2021.
2 days ago
European Markets Head for Higher OpenGermany Stock Market
European equity markets were headed for a higher open on Monday, extending a global stock rally as weaker-than-expected US data tempered expectations that the Federal Reserve will continue to hike rates aggressively. China’s continued reopening also bolstered the outlook for the global economy and lifted risk assets, with Beijing opening sea and land crossings with Hong Kong and ending a requirement for incoming travelers to quarantine, symbolizing an end to the strict zero-Covid policy. Investors now await eurozone employment data for November, as well as French trade numbers and German industrial production figures. DAX and Stoxx 600 futures were up about 0.5% in early trade.
2 days ago
Romanian Jobless Rate Ticks Down to 5.4% in NovemberRomania Unemployment Rate
Romania’s seasonally adjusted unemployment edged lower to 5.4 percent in November 2022 from 5.5 percent in the prior month. The number of unemployed fell by 5.5 thousand to 447.7 thousand. Meantime, the jobless rate for men fell to its lowest in eight months (5.8 percent vs 6.1 percent in October) while that for women increased to its highest in seven months (4.9 percent vs 4.7 percent).
2 days ago
German Industrial Output Rises More than EstimatedGermany Industrial Production Mom
Industrial production in Germany grew by 0.2% month-over-month in November of 2022, reversing from an upwardly revised 0.4% fall in October and better than market forecasts of a 0.1% growth. Production increased for intermediate (1.2%) and capital goods (0.7%) but declined for consumer goods (-1.5%). Meanwhile, the output of energy was up 3% while that of construction fell 2.2%. Also, production in the energy-intensive industrial branches increased by 0.2%. Compared with November 2021, industrial output shrank 0.4%.
2 days ago
Romanian Trade Deficit Widens in NovemberRomania Balance of Trade
Romania’s trade deficit increased to EUR 2.59 billion in November 2022 from EUR 2.14 billion in the corresponding month of the previous year, as imports rose more than exports. Imports grew 19.3 percent from a year earlier to EUR 11.02 billion boosted by purchases from the EU (18.5 percent) and non-EU countries (21.5 percent). Meanwhile, exports increased by 18.8 percent year-on-year to EUR 8.43 billion, led by sales to both the EU (16.5 percent) and non-EU countries (25.5 percent). Considering the first eleven months of the year, the trade goods posted a deficit of EUR 31 billion, with exports surging by 25.1 percent while imports jumped at a faster 29.9 percent.
2 days ago
Swiss Jobless Rate Edges Up to 2.1%Switzerland Unemployment Rate
The Swiss unemployment rate ticked up to a non-seasonally adjusted 2.1 percent in December 2022 from 2.0 percent in the prior month, the highest reading since April. The number of unemployed people increased by 5,614, or 6.1 percent, to 96,941. Meanwhile, the youth unemployment rate, measuring job-seekers between 15 and 24 years old, was up to 2.0 percent from 1.9 percent in November, as the number of young unemployed rose by 140, or 1.6 percent, to 8,773. For the full 2022, the jobless rate fell to 2.2% from 3.0% the year before. Adjusted for seasonal factors, the unemployment rate inched lower to 1.9 percent in December from 2.0 percent in November.
2 days ago
Estonian Posts Largest Trade Gap in 7 MonthsEstonia Balance of Trade
Estonia’s trade deficit widened to EUR 352 million in November of 2022, from EUR 132.5 million in the same month a year earlier, pointing to the largest trade gap since April. Exports remained at the level of previous year to EUR 1,744 million, boosted by natural gas, communication equipment and prefabricated wooden buildings. The top partner countries for Estonia’s exports were Finland (17 percent of total exports), Latvia (13 percent), and Sweden (10 percent). Meanwhile, imports rose by 12 percent to EUR 2,096 million, largely driven by electricity, motor fuels and natural gas. The main partner countries for Estonia’s imports of goods were Finland (17 percent), Lithuania (11 percent), and Latvia (11 percent). For the first eleven months of the year, the trade shortfall surged to EUR 3,042 million, from EUR 1,554 million in the same period of 2021.
2 days ago
Singapore Equities Extend GainsSingapore Stock Market
Stocks in Singapore advanced 18 points or 0.54% to 3,295 in afternoon trade on Monday, hovering at near 5-month highs and building gains from last week after Wall Street rallied Friday following data showing a slowdown in US economic activity, which eased pressures for more rate hikes from the Federal Reserve. A pledge from a Chinese central banker to support the internet sector also lifted sentiment, amid reports that Ant Group saw its founder Jack Ma relinquish control of the fintech giant. Optimism among investors also came from a full reopening of the Chinese economy over the weekend, which fuels hopes of a rapid recovery this year in the mainland. Consumer durables moved higher, alongside tech, financials, transport, and utilities. Among large-cap, DBS Bank and Sembcorp Marine jumped 1.5%, each, while Thai Beverages added 1.4%, and OCBC Bank and Great Eastern were up 1.2%, respectively.
2 days ago
South Africa Forex Reserves Hit Record HighSouth Africa Foreign Exchange Reserves
Foreign exchange reserves in South Africa increased to an all-time high of USD 60.57 billion in December 2022 from USD 59.88 billion in the previous month. The rise was mainly attributed to the proceeds from foreign borrowings amounting to USD 318 million from the French Development Agency, as well as the increase in the US dollar gold price, valuation adjustments linked to the depreciation of the US dollar, and asset price movements. These factors were partially offset by foreign exchange payments made on behalf of the government.
2 days ago
Chinese Yuan Rallies on Economic OptimismChina Currency
The offshore yuan appreciated past 6.8 per dollar, hitting its highest levels in nearly five months as China’s continued reopening bolstered the economic outlook. Guo Shuqing, party secretary of the People’s Bank of China, stated on Sunday that China’s economic growth would quickly rebound and return to its “normal” path as the government provides more financial support to households and private companies to help them recover from the Covid-induced slump. On the latest developments, Beijing opened sea and land crossings with Hong Kong and lifted a requirement for incoming travelers to quarantine, symbolizing an end to the strict zero-Covid policy that weighed on the economy. The yuan also benefited from a general dollar weakness as softer-than-expected US data tempered expectations that the Federal Reserve would continue raising interest rates aggressively.
2 days ago
Sensex Rises for 1st Time in 4 SessionsIndia Stock Market
The BSE Sensex jumped 765.7 points or 1.3% to 60,670.6 in morning trade on Monday, rising after three straight sessions of losses and tracking a rise in Asian markets following an upsurge on Wall Street Friday, amid hopes that an unexpected fall in US services activity and a slowdown in wage growth will ease expectations of aggressive monetary tightening by the Fed. In China, an editorial from the official newspaper of the Communist Party Sunday indicated that Beijing is entering a new phase in its battle against COVID after the removal of border controls with Hong Kong. Meantime, the first official numbers in India showed the economy is likely to grow 7% in the current FY, marginally higher than some recent independent estimates. Almost all sectors advanced, led by IT, metals, healthcare, and pharmaceuticals. Mahindra & Mahindra climbed 3.2%, amid strong gains from Tech Mahindra (3.0%) and Bharti Airtel (2.9%). Tata Consultancy soared 2.8% ahead of its Q3 performance result.
2 days ago
"""
articles, headlines =  new_magic(news_string)


news_cache = {"01/09/2023":{"headlines":headlines,"articles":articles}}