inverse_relation_indicators = [
    "Interest Rate",
    "Government Bond 10Y",
    "Terrorism Index",
    "External Debt",
    "Inflation Rate", 
    "Unemployment Rate",
    "Government Debt to GDP",
    "Budget Gap",
    "Imports", 
    "Consumer Price Index CPI",
    "CPI Housing Utilities",
    "Harmonised Consumer Prices",
    "Import Prices",
    "Producer Prices",
    "Bankruptcies",
    "Corruption Index",
    "Corruption Rank",
    "Lending Rate",
    "Loan Growth",
    "Interbank Rate",
    "Consumer Credit",
    "Households Debt to GDP",
    "Households Debt to Income",
    "Private Sector Credit",
    "Corporate Tax Rate",
    "Personal Income Tax Rate",
    "Sales Tax Rate",
    "Government Debt",
    "Government Debt to GDP",
    "Military Expenditure",
    "Initial Jobless Claims",
    "Job Vacancies",
    "Labour Costs",
    "Long Term Unemployment Rate",
    "Minimum Wages",
    "Unemployed Persons",
    "Unemployment Rate",
    "Youth Unemployment Rate",
    "Commodity Supplies",
    "Rate Hikes",
]