indicators = """
GDP Growth Rate,
Interest Rate,
Inflation Rate,
Industrial Profits,
Unemployment Rate,
Government Debt to GDP,
Balance of Trade,
Current Account to GDP,
Credit Rating,
Commodity,
Currency,
Government Bond 10Y,
Stock Market - Stocks - Shares,
Capacity Utilization,
Balance of Trade,
Capital Flows,
Crude Oil Production,
Current Account,
Current Account to GDP,
Exports,
Foreign Direct Investment,
Budget Gap,
Gold Reserves,
Imports,
Remittances,
Terms of Trade,
Terrorism Index,
Tourism Revenues,
Tourist Arrivals,
Weapons Sales,
Gasoline Futures,
Full Year GDP Growth,
GDP,
GDP Annual Growth Rate,
GDP Constant Prices,
GDP from Agriculture,
GDP from Construction,
GDP from Manufacturing,
GDP from Mining,
GDP from Public Administration,
GDP from Services,
GDP from Transport,
GDP from Utilities,
GDP Growth Rate,
GDP per Capita,
GDP per Capita PPP,
Gross Fixed Capital Formation,
Gross National Product,
Consumer Price Index CPI,
Core Consumer Prices,
CPI Housing Utilities,
Export Prices,
GDP Deflator,
Harmonised Consumer Prices,
Import Prices,
Producer Prices,
Bankruptcies,
Business Confidence,
Capacity Utilization,
Car Production,
Car Registrations,
Cement Production,
Changes in Inventories,
Competitiveness Index,
Competitiveness Rank,
Composite PMI,
Corporate Profits,
Corruption Index,
Corruption Rank,
Crude Oil Rigs,
Electricity Production,
Factory Orders,
Industrial Production,
Industrial Production Mom,
Internet Speed,
IP Addresses,
Leading Economic Index,
Manufacturing PMI,
Manufacturing Production,
Mining Production,
New Orders,
Services PMI,
Small Business Sentiment,
Steel Production,
Total Vehicle Sales,
ZEW Economic Sentiment Index,
Banks Balance Sheet,
Cash Reserve Ratio,
Central Bank Balance Sheet,
Foreign Exchange Reserves,
Interbank Rate,
Interest Rate,
Lending Rate,
Loan Growth,
Private Debt to GDP,
Consumer Confidence,
Consumer Credit,
Consumer Spending,
Disposable Personal Income,
Gasoline Prices,
Households Debt to GDP,
Households Debt to Income,
Personal Savings,
Personal Spending,
Private Sector Credit,
Retail Sales MoM,
Retail Sales YoY,
Corporate Tax Rate,
Personal Income Tax Rate,
Sales Tax Rate,
Building Permits,
Construction Output,
Home Ownership Rate,
Housing Index,
Housing Starts,
Credit Rating,
Fiscal Expenditure,
Government Budget,
Government Budget Value,
Government Debt,
Government Debt to GDP,
Government Revenues,
Government Spending,
Government Spending to GDP,
Military Expenditure,
Employed Persons,
Employment Change,
Employment Rate,
Full Time Employment,
Initial Jobless Claims,
Job Vacancies,
Labor Force Participation Rate,
Labour Costs,
Long Term Unemployment Rate,
Minimum Wages,
Non Farm Payrolls,
Part Time Employment,
Population,
Productivity,
Unemployed Persons,
Unemployment Rate,
Wage Growth,
Wages,
Wages in Manufacturing,
Youth Unemployment Rate,
Commodity Supplies,
Rate Hikes
"""

indicators_cache = {
    "inflation": [
        "Core Inflation Rate",
        "Food Inflation",
        "Harmonised Inflation Rate MoM",
        "Harmonised Inflation Rate YoY",
        "Inflation Expectations" "Inflation Rate MoM",
        "Producer Price Inflation MoM",
    ]
}
